namespace UI
{
    partial class AdminCat
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminCat));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminFillCatStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCatName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllCat = new System.Windows.Forms.ListView();
            this.AdminFindCatID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.AdminUpdateDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillCatID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.AdminCheckCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminFillCatStatus
            // 
            this.AdminFillCatStatus.AcceptsReturn = false;
            this.AdminFillCatStatus.AcceptsTab = false;
            this.AdminFillCatStatus.AnimationSpeed = 200;
            this.AdminFillCatStatus.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatStatus.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatStatus.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatStatus.BackgroundImage")));
            this.AdminFillCatStatus.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatStatus.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatStatus.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatStatus.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.AdminFillCatStatus.BorderRadius = 40;
            this.AdminFillCatStatus.BorderThickness = 1;
            this.AdminFillCatStatus.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatStatus.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillCatStatus.DefaultText = "";
            this.AdminFillCatStatus.FillColor = System.Drawing.Color.White;
            this.AdminFillCatStatus.HideSelection = true;
            this.AdminFillCatStatus.IconLeft = null;
            this.AdminFillCatStatus.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.IconPadding = 10;
            this.AdminFillCatStatus.IconRight = null;
            this.AdminFillCatStatus.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.Lines = new string[0];
            this.AdminFillCatStatus.Location = new System.Drawing.Point(642, 319);
            this.AdminFillCatStatus.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillCatStatus.MaxLength = 32767;
            this.AdminFillCatStatus.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCatStatus.Modified = false;
            this.AdminFillCatStatus.Multiline = false;
            this.AdminFillCatStatus.Name = "AdminFillCatStatus";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatStatus.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnIdleState = stateProperties8;
            this.AdminFillCatStatus.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillCatStatus.PasswordChar = '\0';
            this.AdminFillCatStatus.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatStatus.PlaceholderText = "Fill Cat\'s Status";
            this.AdminFillCatStatus.ReadOnly = false;
            this.AdminFillCatStatus.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatStatus.SelectedText = "";
            this.AdminFillCatStatus.SelectionLength = 0;
            this.AdminFillCatStatus.SelectionStart = 0;
            this.AdminFillCatStatus.ShortcutsEnabled = true;
            this.AdminFillCatStatus.Size = new System.Drawing.Size(253, 45);
            this.AdminFillCatStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatStatus.TabIndex = 64;
            this.AdminFillCatStatus.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatStatus.TextMarginBottom = 0;
            this.AdminFillCatStatus.TextMarginLeft = 3;
            this.AdminFillCatStatus.TextMarginTop = 0;
            this.AdminFillCatStatus.TextPlaceholder = "Fill Cat\'s Status";
            this.AdminFillCatStatus.UseSystemPasswordChar = false;
            this.AdminFillCatStatus.WordWrap = true;
            // 
            // AdminFillCatName
            // 
            this.AdminFillCatName.AcceptsReturn = false;
            this.AdminFillCatName.AcceptsTab = false;
            this.AdminFillCatName.AnimationSpeed = 200;
            this.AdminFillCatName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatName.BackgroundImage")));
            this.AdminFillCatName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatName.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.AdminFillCatName.BorderRadius = 40;
            this.AdminFillCatName.BorderThickness = 1;
            this.AdminFillCatName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillCatName.DefaultText = "";
            this.AdminFillCatName.FillColor = System.Drawing.Color.White;
            this.AdminFillCatName.HideSelection = true;
            this.AdminFillCatName.IconLeft = null;
            this.AdminFillCatName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.IconPadding = 10;
            this.AdminFillCatName.IconRight = null;
            this.AdminFillCatName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.Lines = new string[0];
            this.AdminFillCatName.Location = new System.Drawing.Point(642, 251);
            this.AdminFillCatName.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillCatName.MaxLength = 32767;
            this.AdminFillCatName.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCatName.Modified = false;
            this.AdminFillCatName.Multiline = false;
            this.AdminFillCatName.Name = "AdminFillCatName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnIdleState = stateProperties12;
            this.AdminFillCatName.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillCatName.PasswordChar = '\0';
            this.AdminFillCatName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatName.PlaceholderText = "Fill Cat\'s Name";
            this.AdminFillCatName.ReadOnly = false;
            this.AdminFillCatName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatName.SelectedText = "";
            this.AdminFillCatName.SelectionLength = 0;
            this.AdminFillCatName.SelectionStart = 0;
            this.AdminFillCatName.ShortcutsEnabled = true;
            this.AdminFillCatName.Size = new System.Drawing.Size(253, 45);
            this.AdminFillCatName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatName.TabIndex = 63;
            this.AdminFillCatName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatName.TextMarginBottom = 0;
            this.AdminFillCatName.TextMarginLeft = 3;
            this.AdminFillCatName.TextMarginTop = 0;
            this.AdminFillCatName.TextPlaceholder = "Fill Cat\'s Name";
            this.AdminFillCatName.UseSystemPasswordChar = false;
            this.AdminFillCatName.WordWrap = true;
            // 
            // AdminViewAllCat
            // 
            this.AdminViewAllCat.HideSelection = false;
            this.AdminViewAllCat.Location = new System.Drawing.Point(20, 14);
            this.AdminViewAllCat.Name = "AdminViewAllCat";
            this.AdminViewAllCat.Size = new System.Drawing.Size(606, 509);
            this.AdminViewAllCat.TabIndex = 62;
            this.AdminViewAllCat.UseCompatibleStateImageBehavior = false;
            this.AdminViewAllCat.SelectedIndexChanged += new System.EventHandler(this.AdminViewAllCat_SelectedIndexChanged);
            // 
            // AdminFindCatID
            // 
            this.AdminFindCatID.AcceptsReturn = false;
            this.AdminFindCatID.AcceptsTab = false;
            this.AdminFindCatID.AnimationSpeed = 200;
            this.AdminFindCatID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFindCatID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFindCatID.BackColor = System.Drawing.Color.Transparent;
            this.AdminFindCatID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFindCatID.BackgroundImage")));
            this.AdminFindCatID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFindCatID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFindCatID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFindCatID.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFindCatID.BorderRadius = 40;
            this.AdminFindCatID.BorderThickness = 1;
            this.AdminFindCatID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFindCatID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFindCatID.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFindCatID.DefaultText = "";
            this.AdminFindCatID.FillColor = System.Drawing.Color.White;
            this.AdminFindCatID.HideSelection = true;
            this.AdminFindCatID.IconLeft = null;
            this.AdminFindCatID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFindCatID.IconPadding = 10;
            this.AdminFindCatID.IconRight = null;
            this.AdminFindCatID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFindCatID.Lines = new string[0];
            this.AdminFindCatID.Location = new System.Drawing.Point(643, 20);
            this.AdminFindCatID.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFindCatID.MaxLength = 32767;
            this.AdminFindCatID.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFindCatID.Modified = false;
            this.AdminFindCatID.Multiline = false;
            this.AdminFindCatID.Name = "AdminFindCatID";
            stateProperties13.BorderColor = System.Drawing.Color.Transparent;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFindCatID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Transparent;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFindCatID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFindCatID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFindCatID.OnIdleState = stateProperties16;
            this.AdminFindCatID.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFindCatID.PasswordChar = '\0';
            this.AdminFindCatID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFindCatID.PlaceholderText = "Fill Cat\'s Id";
            this.AdminFindCatID.ReadOnly = false;
            this.AdminFindCatID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFindCatID.SelectedText = "";
            this.AdminFindCatID.SelectionLength = 0;
            this.AdminFindCatID.SelectionStart = 0;
            this.AdminFindCatID.ShortcutsEnabled = true;
            this.AdminFindCatID.Size = new System.Drawing.Size(253, 45);
            this.AdminFindCatID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFindCatID.TabIndex = 60;
            this.AdminFindCatID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFindCatID.TextMarginBottom = 0;
            this.AdminFindCatID.TextMarginLeft = 3;
            this.AdminFindCatID.TextMarginTop = 0;
            this.AdminFindCatID.TextPlaceholder = "Fill Cat\'s Id";
            this.AdminFindCatID.UseSystemPasswordChar = false;
            this.AdminFindCatID.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel8.Location = new System.Drawing.Point(661, 241);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(58, 17);
            this.bunifuLabel8.TabIndex = 169;
            this.bunifuLabel8.Text = "Tên mèo:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel1.Location = new System.Drawing.Point(661, 308);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(69, 17);
            this.bunifuLabel1.TabIndex = 170;
            this.bunifuLabel1.Text = "Trạng thái:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminUpdateDrink
            // 
            this.AdminUpdateDrink.AllowAnimations = true;
            this.AdminUpdateDrink.AllowMouseEffects = true;
            this.AdminUpdateDrink.AllowToggling = false;
            this.AdminUpdateDrink.AnimationSpeed = 200;
            this.AdminUpdateDrink.AutoGenerateColors = false;
            this.AdminUpdateDrink.AutoRoundBorders = false;
            this.AdminUpdateDrink.AutoSizeLeftIcon = true;
            this.AdminUpdateDrink.AutoSizeRightIcon = true;
            this.AdminUpdateDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateDrink.BackgroundImage")));
            this.AdminUpdateDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.ButtonText = "CẬP NHẬT";
            this.AdminUpdateDrink.ButtonTextMarginLeft = 0;
            this.AdminUpdateDrink.ColorContrastOnClick = 45;
            this.AdminUpdateDrink.ColorContrastOnHover = 45;
            this.AdminUpdateDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminUpdateDrink.CustomizableEdges = borderEdges2;
            this.AdminUpdateDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateDrink.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateDrink.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateDrink.IconMarginLeft = 11;
            this.AdminUpdateDrink.IconPadding = 10;
            this.AdminUpdateDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateDrink.IconSize = 25;
            this.AdminUpdateDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleBorderRadius = 45;
            this.AdminUpdateDrink.IdleBorderThickness = 1;
            this.AdminUpdateDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleIconLeftImage = null;
            this.AdminUpdateDrink.IdleIconRightImage = null;
            this.AdminUpdateDrink.IndicateFocus = false;
            this.AdminUpdateDrink.Location = new System.Drawing.Point(639, 391);
            this.AdminUpdateDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminUpdateDrink.Name = "AdminUpdateDrink";
            this.AdminUpdateDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.OnDisabledState.BorderRadius = 45;
            this.AdminUpdateDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateDrink.OnDisabledState.IconRightImage = null;
            this.AdminUpdateDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.BorderRadius = 45;
            this.AdminUpdateDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.onHoverState.BorderThickness = 1;
            this.AdminUpdateDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateDrink.onHoverState.IconLeftImage = null;
            this.AdminUpdateDrink.onHoverState.IconRightImage = null;
            this.AdminUpdateDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.BorderRadius = 45;
            this.AdminUpdateDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnIdleState.BorderThickness = 1;
            this.AdminUpdateDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnIdleState.IconLeftImage = null;
            this.AdminUpdateDrink.OnIdleState.IconRightImage = null;
            this.AdminUpdateDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.BorderRadius = 45;
            this.AdminUpdateDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnPressedState.BorderThickness = 1;
            this.AdminUpdateDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnPressedState.IconLeftImage = null;
            this.AdminUpdateDrink.OnPressedState.IconRightImage = null;
            this.AdminUpdateDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminUpdateDrink.TabIndex = 173;
            this.AdminUpdateDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateDrink.TextMarginLeft = 0;
            this.AdminUpdateDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteDrink
            // 
            this.AdminDeleteDrink.AllowAnimations = true;
            this.AdminDeleteDrink.AllowMouseEffects = true;
            this.AdminDeleteDrink.AllowToggling = false;
            this.AdminDeleteDrink.AnimationSpeed = 200;
            this.AdminDeleteDrink.AutoGenerateColors = false;
            this.AdminDeleteDrink.AutoRoundBorders = false;
            this.AdminDeleteDrink.AutoSizeLeftIcon = true;
            this.AdminDeleteDrink.AutoSizeRightIcon = true;
            this.AdminDeleteDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteDrink.BackgroundImage")));
            this.AdminDeleteDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.ButtonText = "XÓA BỎ";
            this.AdminDeleteDrink.ButtonTextMarginLeft = 0;
            this.AdminDeleteDrink.ColorContrastOnClick = 45;
            this.AdminDeleteDrink.ColorContrastOnHover = 45;
            this.AdminDeleteDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminDeleteDrink.CustomizableEdges = borderEdges3;
            this.AdminDeleteDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteDrink.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteDrink.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteDrink.IconMarginLeft = 11;
            this.AdminDeleteDrink.IconPadding = 10;
            this.AdminDeleteDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteDrink.IconSize = 25;
            this.AdminDeleteDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleBorderRadius = 45;
            this.AdminDeleteDrink.IdleBorderThickness = 1;
            this.AdminDeleteDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleIconLeftImage = null;
            this.AdminDeleteDrink.IdleIconRightImage = null;
            this.AdminDeleteDrink.IndicateFocus = false;
            this.AdminDeleteDrink.Location = new System.Drawing.Point(725, 391);
            this.AdminDeleteDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminDeleteDrink.Name = "AdminDeleteDrink";
            this.AdminDeleteDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.OnDisabledState.BorderRadius = 45;
            this.AdminDeleteDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteDrink.OnDisabledState.IconRightImage = null;
            this.AdminDeleteDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.BorderRadius = 45;
            this.AdminDeleteDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.onHoverState.BorderThickness = 1;
            this.AdminDeleteDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteDrink.onHoverState.IconLeftImage = null;
            this.AdminDeleteDrink.onHoverState.IconRightImage = null;
            this.AdminDeleteDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.BorderRadius = 45;
            this.AdminDeleteDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnIdleState.BorderThickness = 1;
            this.AdminDeleteDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnIdleState.IconLeftImage = null;
            this.AdminDeleteDrink.OnIdleState.IconRightImage = null;
            this.AdminDeleteDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.BorderRadius = 45;
            this.AdminDeleteDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnPressedState.BorderThickness = 1;
            this.AdminDeleteDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnPressedState.IconLeftImage = null;
            this.AdminDeleteDrink.OnPressedState.IconRightImage = null;
            this.AdminDeleteDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminDeleteDrink.TabIndex = 172;
            this.AdminDeleteDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteDrink.TextMarginLeft = 0;
            this.AdminDeleteDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddDrink
            // 
            this.AdminAddDrink.AllowAnimations = true;
            this.AdminAddDrink.AllowMouseEffects = true;
            this.AdminAddDrink.AllowToggling = false;
            this.AdminAddDrink.AnimationSpeed = 200;
            this.AdminAddDrink.AutoGenerateColors = false;
            this.AdminAddDrink.AutoRoundBorders = false;
            this.AdminAddDrink.AutoSizeLeftIcon = true;
            this.AdminAddDrink.AutoSizeRightIcon = true;
            this.AdminAddDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddDrink.BackgroundImage")));
            this.AdminAddDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.ButtonText = "THÊM MỚI";
            this.AdminAddDrink.ButtonTextMarginLeft = 0;
            this.AdminAddDrink.ColorContrastOnClick = 45;
            this.AdminAddDrink.ColorContrastOnHover = 45;
            this.AdminAddDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminAddDrink.CustomizableEdges = borderEdges4;
            this.AdminAddDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddDrink.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddDrink.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddDrink.IconMarginLeft = 11;
            this.AdminAddDrink.IconPadding = 10;
            this.AdminAddDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddDrink.IconSize = 25;
            this.AdminAddDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleBorderRadius = 45;
            this.AdminAddDrink.IdleBorderThickness = 1;
            this.AdminAddDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleIconLeftImage = null;
            this.AdminAddDrink.IdleIconRightImage = null;
            this.AdminAddDrink.IndicateFocus = false;
            this.AdminAddDrink.Location = new System.Drawing.Point(814, 391);
            this.AdminAddDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminAddDrink.Name = "AdminAddDrink";
            this.AdminAddDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.OnDisabledState.BorderRadius = 45;
            this.AdminAddDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnDisabledState.BorderThickness = 1;
            this.AdminAddDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.OnDisabledState.IconLeftImage = null;
            this.AdminAddDrink.OnDisabledState.IconRightImage = null;
            this.AdminAddDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.BorderRadius = 45;
            this.AdminAddDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.onHoverState.BorderThickness = 1;
            this.AdminAddDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddDrink.onHoverState.IconLeftImage = null;
            this.AdminAddDrink.onHoverState.IconRightImage = null;
            this.AdminAddDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.BorderRadius = 45;
            this.AdminAddDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnIdleState.BorderThickness = 1;
            this.AdminAddDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnIdleState.IconLeftImage = null;
            this.AdminAddDrink.OnIdleState.IconRightImage = null;
            this.AdminAddDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.BorderRadius = 45;
            this.AdminAddDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnPressedState.BorderThickness = 1;
            this.AdminAddDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnPressedState.IconLeftImage = null;
            this.AdminAddDrink.OnPressedState.IconRightImage = null;
            this.AdminAddDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminAddDrink.TabIndex = 171;
            this.AdminAddDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddDrink.TextMarginLeft = 0;
            this.AdminAddDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillCatID
            // 
            this.AdminFillCatID.AcceptsReturn = false;
            this.AdminFillCatID.AcceptsTab = false;
            this.AdminFillCatID.AnimationSpeed = 200;
            this.AdminFillCatID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatID.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatID.BackgroundImage")));
            this.AdminFillCatID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatID.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.AdminFillCatID.BorderRadius = 40;
            this.AdminFillCatID.BorderThickness = 1;
            this.AdminFillCatID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatID.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillCatID.DefaultText = "";
            this.AdminFillCatID.FillColor = System.Drawing.Color.White;
            this.AdminFillCatID.HideSelection = true;
            this.AdminFillCatID.IconLeft = null;
            this.AdminFillCatID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatID.IconPadding = 10;
            this.AdminFillCatID.IconRight = null;
            this.AdminFillCatID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatID.Lines = new string[0];
            this.AdminFillCatID.Location = new System.Drawing.Point(642, 189);
            this.AdminFillCatID.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillCatID.MaxLength = 32767;
            this.AdminFillCatID.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCatID.Modified = false;
            this.AdminFillCatID.Multiline = false;
            this.AdminFillCatID.Name = "AdminFillCatID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatID.OnIdleState = stateProperties4;
            this.AdminFillCatID.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillCatID.PasswordChar = '\0';
            this.AdminFillCatID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatID.PlaceholderText = "Fill Cat\'s Id";
            this.AdminFillCatID.ReadOnly = false;
            this.AdminFillCatID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatID.SelectedText = "";
            this.AdminFillCatID.SelectionLength = 0;
            this.AdminFillCatID.SelectionStart = 0;
            this.AdminFillCatID.ShortcutsEnabled = true;
            this.AdminFillCatID.Size = new System.Drawing.Size(253, 45);
            this.AdminFillCatID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatID.TabIndex = 174;
            this.AdminFillCatID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatID.TextMarginBottom = 0;
            this.AdminFillCatID.TextMarginLeft = 3;
            this.AdminFillCatID.TextMarginTop = 0;
            this.AdminFillCatID.TextPlaceholder = "Fill Cat\'s Id";
            this.AdminFillCatID.UseSystemPasswordChar = false;
            this.AdminFillCatID.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel2.Location = new System.Drawing.Point(661, 179);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(19, 17);
            this.bunifuLabel2.TabIndex = 175;
            this.bunifuLabel2.Text = "ID:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(640, 148);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(255, 15);
            this.bunifuLabel3.TabIndex = 176;
            this.bunifuLabel3.Text = "---------------------------------------------------";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminCheckCat
            // 
            this.AdminCheckCat.AllowAnimations = true;
            this.AdminCheckCat.AllowMouseEffects = true;
            this.AdminCheckCat.AllowToggling = false;
            this.AdminCheckCat.AnimationSpeed = 200;
            this.AdminCheckCat.AutoGenerateColors = false;
            this.AdminCheckCat.AutoRoundBorders = false;
            this.AdminCheckCat.AutoSizeLeftIcon = true;
            this.AdminCheckCat.AutoSizeRightIcon = true;
            this.AdminCheckCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckCat.BackgroundImage")));
            this.AdminCheckCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.ButtonText = "KIỂM TRA";
            this.AdminCheckCat.ButtonTextMarginLeft = 0;
            this.AdminCheckCat.ColorContrastOnClick = 45;
            this.AdminCheckCat.ColorContrastOnHover = 45;
            this.AdminCheckCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminCheckCat.CustomizableEdges = borderEdges1;
            this.AdminCheckCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckCat.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckCat.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckCat.IconMarginLeft = 11;
            this.AdminCheckCat.IconPadding = 10;
            this.AdminCheckCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckCat.IconSize = 25;
            this.AdminCheckCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.IdleBorderRadius = 42;
            this.AdminCheckCat.IdleBorderThickness = 1;
            this.AdminCheckCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.IdleIconLeftImage = null;
            this.AdminCheckCat.IdleIconRightImage = null;
            this.AdminCheckCat.IndicateFocus = false;
            this.AdminCheckCat.Location = new System.Drawing.Point(643, 74);
            this.AdminCheckCat.Margin = new System.Windows.Forms.Padding(4);
            this.AdminCheckCat.Name = "AdminCheckCat";
            this.AdminCheckCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCat.OnDisabledState.BorderRadius = 42;
            this.AdminCheckCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnDisabledState.BorderThickness = 1;
            this.AdminCheckCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCat.OnDisabledState.IconLeftImage = null;
            this.AdminCheckCat.OnDisabledState.IconRightImage = null;
            this.AdminCheckCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.onHoverState.BorderRadius = 42;
            this.AdminCheckCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.onHoverState.BorderThickness = 1;
            this.AdminCheckCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckCat.onHoverState.IconLeftImage = null;
            this.AdminCheckCat.onHoverState.IconRightImage = null;
            this.AdminCheckCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnIdleState.BorderRadius = 42;
            this.AdminCheckCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnIdleState.BorderThickness = 1;
            this.AdminCheckCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.OnIdleState.IconLeftImage = null;
            this.AdminCheckCat.OnIdleState.IconRightImage = null;
            this.AdminCheckCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnPressedState.BorderRadius = 42;
            this.AdminCheckCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnPressedState.BorderThickness = 1;
            this.AdminCheckCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.OnPressedState.IconLeftImage = null;
            this.AdminCheckCat.OnPressedState.IconRightImage = null;
            this.AdminCheckCat.Size = new System.Drawing.Size(253, 45);
            this.AdminCheckCat.TabIndex = 177;
            this.AdminCheckCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckCat.TextMarginLeft = 0;
            this.AdminCheckCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminCat
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.AdminCheckCat);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.AdminFillCatID);
            this.Controls.Add(this.AdminUpdateDrink);
            this.Controls.Add(this.AdminDeleteDrink);
            this.Controls.Add(this.AdminAddDrink);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.AdminFillCatStatus);
            this.Controls.Add(this.AdminFillCatName);
            this.Controls.Add(this.AdminViewAllCat);
            this.Controls.Add(this.AdminFindCatID);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "AdminCat";
            this.Size = new System.Drawing.Size(910, 540);
            this.Load += new System.EventHandler(this.AdminCat_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatStatus;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatName;
        private System.Windows.Forms.ListView AdminViewAllCat;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFindCatID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddDrink;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckCat;
    }
}
