namespace UI
{
    partial class AdminDrink
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminDrink));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminUpdateDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillDrinkPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkAvailable = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllCustomer = new System.Windows.Forms.ListView();
            this.AdminShowAllDrinks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillDrinkName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminUpdateDrink
            // 
            this.AdminUpdateDrink.AllowAnimations = true;
            this.AdminUpdateDrink.AllowMouseEffects = true;
            this.AdminUpdateDrink.AllowToggling = false;
            this.AdminUpdateDrink.AnimationSpeed = 200;
            this.AdminUpdateDrink.AutoGenerateColors = false;
            this.AdminUpdateDrink.AutoRoundBorders = false;
            this.AdminUpdateDrink.AutoSizeLeftIcon = true;
            this.AdminUpdateDrink.AutoSizeRightIcon = true;
            this.AdminUpdateDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateDrink.BackgroundImage")));
            this.AdminUpdateDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.ButtonText = "Update";
            this.AdminUpdateDrink.ButtonTextMarginLeft = 0;
            this.AdminUpdateDrink.ColorContrastOnClick = 45;
            this.AdminUpdateDrink.ColorContrastOnHover = 45;
            this.AdminUpdateDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminUpdateDrink.CustomizableEdges = borderEdges1;
            this.AdminUpdateDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateDrink.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateDrink.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateDrink.IconMarginLeft = 11;
            this.AdminUpdateDrink.IconPadding = 10;
            this.AdminUpdateDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateDrink.IconSize = 25;
            this.AdminUpdateDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleBorderRadius = 37;
            this.AdminUpdateDrink.IdleBorderThickness = 1;
            this.AdminUpdateDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleIconLeftImage = null;
            this.AdminUpdateDrink.IdleIconRightImage = null;
            this.AdminUpdateDrink.IndicateFocus = false;
            this.AdminUpdateDrink.Location = new System.Drawing.Point(716, 365);
            this.AdminUpdateDrink.Name = "AdminUpdateDrink";
            this.AdminUpdateDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateDrink.OnDisabledState.IconRightImage = null;
            this.AdminUpdateDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.BorderRadius = 37;
            this.AdminUpdateDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.onHoverState.BorderThickness = 1;
            this.AdminUpdateDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateDrink.onHoverState.IconLeftImage = null;
            this.AdminUpdateDrink.onHoverState.IconRightImage = null;
            this.AdminUpdateDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.BorderRadius = 37;
            this.AdminUpdateDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnIdleState.BorderThickness = 1;
            this.AdminUpdateDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnIdleState.IconLeftImage = null;
            this.AdminUpdateDrink.OnIdleState.IconRightImage = null;
            this.AdminUpdateDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.BorderRadius = 37;
            this.AdminUpdateDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnPressedState.BorderThickness = 1;
            this.AdminUpdateDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnPressedState.IconLeftImage = null;
            this.AdminUpdateDrink.OnPressedState.IconRightImage = null;
            this.AdminUpdateDrink.Size = new System.Drawing.Size(330, 36);
            this.AdminUpdateDrink.TabIndex = 58;
            this.AdminUpdateDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateDrink.TextMarginLeft = 0;
            this.AdminUpdateDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteDrink
            // 
            this.AdminDeleteDrink.AllowAnimations = true;
            this.AdminDeleteDrink.AllowMouseEffects = true;
            this.AdminDeleteDrink.AllowToggling = false;
            this.AdminDeleteDrink.AnimationSpeed = 200;
            this.AdminDeleteDrink.AutoGenerateColors = false;
            this.AdminDeleteDrink.AutoRoundBorders = false;
            this.AdminDeleteDrink.AutoSizeLeftIcon = true;
            this.AdminDeleteDrink.AutoSizeRightIcon = true;
            this.AdminDeleteDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteDrink.BackgroundImage")));
            this.AdminDeleteDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.ButtonText = "DELETE";
            this.AdminDeleteDrink.ButtonTextMarginLeft = 0;
            this.AdminDeleteDrink.ColorContrastOnClick = 45;
            this.AdminDeleteDrink.ColorContrastOnHover = 45;
            this.AdminDeleteDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminDeleteDrink.CustomizableEdges = borderEdges2;
            this.AdminDeleteDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteDrink.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteDrink.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteDrink.IconMarginLeft = 11;
            this.AdminDeleteDrink.IconPadding = 10;
            this.AdminDeleteDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteDrink.IconSize = 25;
            this.AdminDeleteDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleBorderRadius = 37;
            this.AdminDeleteDrink.IdleBorderThickness = 1;
            this.AdminDeleteDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleIconLeftImage = null;
            this.AdminDeleteDrink.IdleIconRightImage = null;
            this.AdminDeleteDrink.IndicateFocus = false;
            this.AdminDeleteDrink.Location = new System.Drawing.Point(886, 314);
            this.AdminDeleteDrink.Name = "AdminDeleteDrink";
            this.AdminDeleteDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteDrink.OnDisabledState.IconRightImage = null;
            this.AdminDeleteDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.BorderRadius = 37;
            this.AdminDeleteDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.onHoverState.BorderThickness = 1;
            this.AdminDeleteDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteDrink.onHoverState.IconLeftImage = null;
            this.AdminDeleteDrink.onHoverState.IconRightImage = null;
            this.AdminDeleteDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.BorderRadius = 37;
            this.AdminDeleteDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnIdleState.BorderThickness = 1;
            this.AdminDeleteDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnIdleState.IconLeftImage = null;
            this.AdminDeleteDrink.OnIdleState.IconRightImage = null;
            this.AdminDeleteDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.BorderRadius = 37;
            this.AdminDeleteDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnPressedState.BorderThickness = 1;
            this.AdminDeleteDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnPressedState.IconLeftImage = null;
            this.AdminDeleteDrink.OnPressedState.IconRightImage = null;
            this.AdminDeleteDrink.Size = new System.Drawing.Size(160, 36);
            this.AdminDeleteDrink.TabIndex = 57;
            this.AdminDeleteDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteDrink.TextMarginLeft = 0;
            this.AdminDeleteDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddDrink
            // 
            this.AdminAddDrink.AllowAnimations = true;
            this.AdminAddDrink.AllowMouseEffects = true;
            this.AdminAddDrink.AllowToggling = false;
            this.AdminAddDrink.AnimationSpeed = 200;
            this.AdminAddDrink.AutoGenerateColors = false;
            this.AdminAddDrink.AutoRoundBorders = false;
            this.AdminAddDrink.AutoSizeLeftIcon = true;
            this.AdminAddDrink.AutoSizeRightIcon = true;
            this.AdminAddDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddDrink.BackgroundImage")));
            this.AdminAddDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.ButtonText = "ADD";
            this.AdminAddDrink.ButtonTextMarginLeft = 0;
            this.AdminAddDrink.ColorContrastOnClick = 45;
            this.AdminAddDrink.ColorContrastOnHover = 45;
            this.AdminAddDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminAddDrink.CustomizableEdges = borderEdges3;
            this.AdminAddDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddDrink.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddDrink.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddDrink.IconMarginLeft = 11;
            this.AdminAddDrink.IconPadding = 10;
            this.AdminAddDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddDrink.IconSize = 25;
            this.AdminAddDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleBorderRadius = 37;
            this.AdminAddDrink.IdleBorderThickness = 1;
            this.AdminAddDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleIconLeftImage = null;
            this.AdminAddDrink.IdleIconRightImage = null;
            this.AdminAddDrink.IndicateFocus = false;
            this.AdminAddDrink.Location = new System.Drawing.Point(716, 314);
            this.AdminAddDrink.Name = "AdminAddDrink";
            this.AdminAddDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.OnDisabledState.BorderRadius = 37;
            this.AdminAddDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnDisabledState.BorderThickness = 1;
            this.AdminAddDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.OnDisabledState.IconLeftImage = null;
            this.AdminAddDrink.OnDisabledState.IconRightImage = null;
            this.AdminAddDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.BorderRadius = 37;
            this.AdminAddDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.onHoverState.BorderThickness = 1;
            this.AdminAddDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddDrink.onHoverState.IconLeftImage = null;
            this.AdminAddDrink.onHoverState.IconRightImage = null;
            this.AdminAddDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.BorderRadius = 37;
            this.AdminAddDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnIdleState.BorderThickness = 1;
            this.AdminAddDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnIdleState.IconLeftImage = null;
            this.AdminAddDrink.OnIdleState.IconRightImage = null;
            this.AdminAddDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.BorderRadius = 37;
            this.AdminAddDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnPressedState.BorderThickness = 1;
            this.AdminAddDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnPressedState.IconLeftImage = null;
            this.AdminAddDrink.OnPressedState.IconRightImage = null;
            this.AdminAddDrink.Size = new System.Drawing.Size(160, 36);
            this.AdminAddDrink.TabIndex = 56;
            this.AdminAddDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddDrink.TextMarginLeft = 0;
            this.AdminAddDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillDrinkPrice
            // 
            this.AdminFillDrinkPrice.AcceptsReturn = false;
            this.AdminFillDrinkPrice.AcceptsTab = false;
            this.AdminFillDrinkPrice.AnimationSpeed = 200;
            this.AdminFillDrinkPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkPrice.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkPrice.BackgroundImage")));
            this.AdminFillDrinkPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkPrice.BorderRadius = 1;
            this.AdminFillDrinkPrice.BorderThickness = 1;
            this.AdminFillDrinkPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillDrinkPrice.DefaultText = "";
            this.AdminFillDrinkPrice.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkPrice.HideSelection = true;
            this.AdminFillDrinkPrice.IconLeft = null;
            this.AdminFillDrinkPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.IconPadding = 10;
            this.AdminFillDrinkPrice.IconRight = null;
            this.AdminFillDrinkPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.Lines = new string[0];
            this.AdminFillDrinkPrice.Location = new System.Drawing.Point(716, 215);
            this.AdminFillDrinkPrice.MaxLength = 32767;
            this.AdminFillDrinkPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillDrinkPrice.Modified = false;
            this.AdminFillDrinkPrice.Multiline = false;
            this.AdminFillDrinkPrice.Name = "AdminFillDrinkPrice";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkPrice.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnIdleState = stateProperties4;
            this.AdminFillDrinkPrice.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillDrinkPrice.PasswordChar = '\0';
            this.AdminFillDrinkPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkPrice.PlaceholderText = "Fill your Drink\'s Price";
            this.AdminFillDrinkPrice.ReadOnly = false;
            this.AdminFillDrinkPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkPrice.SelectedText = "";
            this.AdminFillDrinkPrice.SelectionLength = 0;
            this.AdminFillDrinkPrice.SelectionStart = 0;
            this.AdminFillDrinkPrice.ShortcutsEnabled = true;
            this.AdminFillDrinkPrice.Size = new System.Drawing.Size(330, 37);
            this.AdminFillDrinkPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkPrice.TabIndex = 55;
            this.AdminFillDrinkPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkPrice.TextMarginBottom = 0;
            this.AdminFillDrinkPrice.TextMarginLeft = 3;
            this.AdminFillDrinkPrice.TextMarginTop = 0;
            this.AdminFillDrinkPrice.TextPlaceholder = "Fill your Drink\'s Price";
            this.AdminFillDrinkPrice.UseSystemPasswordChar = false;
            this.AdminFillDrinkPrice.WordWrap = true;
            // 
            // AdminFillDrinkAvailable
            // 
            this.AdminFillDrinkAvailable.AcceptsReturn = false;
            this.AdminFillDrinkAvailable.AcceptsTab = false;
            this.AdminFillDrinkAvailable.AnimationSpeed = 200;
            this.AdminFillDrinkAvailable.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkAvailable.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkAvailable.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkAvailable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkAvailable.BackgroundImage")));
            this.AdminFillDrinkAvailable.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkAvailable.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkAvailable.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkAvailable.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkAvailable.BorderRadius = 1;
            this.AdminFillDrinkAvailable.BorderThickness = 1;
            this.AdminFillDrinkAvailable.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkAvailable.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkAvailable.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillDrinkAvailable.DefaultText = "";
            this.AdminFillDrinkAvailable.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.HideSelection = true;
            this.AdminFillDrinkAvailable.IconLeft = null;
            this.AdminFillDrinkAvailable.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkAvailable.IconPadding = 10;
            this.AdminFillDrinkAvailable.IconRight = null;
            this.AdminFillDrinkAvailable.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkAvailable.Lines = new string[0];
            this.AdminFillDrinkAvailable.Location = new System.Drawing.Point(716, 271);
            this.AdminFillDrinkAvailable.MaxLength = 32767;
            this.AdminFillDrinkAvailable.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillDrinkAvailable.Modified = false;
            this.AdminFillDrinkAvailable.Multiline = false;
            this.AdminFillDrinkAvailable.Name = "AdminFillDrinkAvailable";
            stateProperties5.BorderColor = System.Drawing.Color.Transparent;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkAvailable.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkAvailable.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkAvailable.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkAvailable.OnIdleState = stateProperties8;
            this.AdminFillDrinkAvailable.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillDrinkAvailable.PasswordChar = '\0';
            this.AdminFillDrinkAvailable.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkAvailable.PlaceholderText = "Fill your Drink\'s Address";
            this.AdminFillDrinkAvailable.ReadOnly = false;
            this.AdminFillDrinkAvailable.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkAvailable.SelectedText = "";
            this.AdminFillDrinkAvailable.SelectionLength = 0;
            this.AdminFillDrinkAvailable.SelectionStart = 0;
            this.AdminFillDrinkAvailable.ShortcutsEnabled = true;
            this.AdminFillDrinkAvailable.Size = new System.Drawing.Size(330, 37);
            this.AdminFillDrinkAvailable.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkAvailable.TabIndex = 54;
            this.AdminFillDrinkAvailable.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkAvailable.TextMarginBottom = 0;
            this.AdminFillDrinkAvailable.TextMarginLeft = 3;
            this.AdminFillDrinkAvailable.TextMarginTop = 0;
            this.AdminFillDrinkAvailable.TextPlaceholder = "Fill your Drink\'s Address";
            this.AdminFillDrinkAvailable.UseSystemPasswordChar = false;
            this.AdminFillDrinkAvailable.WordWrap = true;
            // 
            // AdminFillDrinkType
            // 
            this.AdminFillDrinkType.AcceptsReturn = false;
            this.AdminFillDrinkType.AcceptsTab = false;
            this.AdminFillDrinkType.AnimationSpeed = 200;
            this.AdminFillDrinkType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkType.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkType.BackgroundImage")));
            this.AdminFillDrinkType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkType.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkType.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkType.BorderRadius = 1;
            this.AdminFillDrinkType.BorderThickness = 1;
            this.AdminFillDrinkType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillDrinkType.DefaultText = "";
            this.AdminFillDrinkType.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkType.HideSelection = true;
            this.AdminFillDrinkType.IconLeft = null;
            this.AdminFillDrinkType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.IconPadding = 10;
            this.AdminFillDrinkType.IconRight = null;
            this.AdminFillDrinkType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.Lines = new string[0];
            this.AdminFillDrinkType.Location = new System.Drawing.Point(716, 159);
            this.AdminFillDrinkType.MaxLength = 32767;
            this.AdminFillDrinkType.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillDrinkType.Modified = false;
            this.AdminFillDrinkType.Multiline = false;
            this.AdminFillDrinkType.Name = "AdminFillDrinkType";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkType.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnIdleState = stateProperties12;
            this.AdminFillDrinkType.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillDrinkType.PasswordChar = '\0';
            this.AdminFillDrinkType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkType.PlaceholderText = "Fill your Drink\'s Type\r\n";
            this.AdminFillDrinkType.ReadOnly = false;
            this.AdminFillDrinkType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkType.SelectedText = "";
            this.AdminFillDrinkType.SelectionLength = 0;
            this.AdminFillDrinkType.SelectionStart = 0;
            this.AdminFillDrinkType.ShortcutsEnabled = true;
            this.AdminFillDrinkType.Size = new System.Drawing.Size(330, 37);
            this.AdminFillDrinkType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkType.TabIndex = 50;
            this.AdminFillDrinkType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkType.TextMarginBottom = 0;
            this.AdminFillDrinkType.TextMarginLeft = 3;
            this.AdminFillDrinkType.TextMarginTop = 0;
            this.AdminFillDrinkType.TextPlaceholder = "Fill your Drink\'s Type\r\n";
            this.AdminFillDrinkType.UseSystemPasswordChar = false;
            this.AdminFillDrinkType.WordWrap = true;
            // 
            // AdminViewAllCustomer
            // 
            this.AdminViewAllCustomer.HideSelection = false;
            this.AdminViewAllCustomer.Location = new System.Drawing.Point(22, 22);
            this.AdminViewAllCustomer.Margin = new System.Windows.Forms.Padding(2);
            this.AdminViewAllCustomer.Name = "AdminViewAllCustomer";
            this.AdminViewAllCustomer.Size = new System.Drawing.Size(672, 616);
            this.AdminViewAllCustomer.TabIndex = 49;
            this.AdminViewAllCustomer.UseCompatibleStateImageBehavior = false;
            // 
            // AdminShowAllDrinks
            // 
            this.AdminShowAllDrinks.AllowAnimations = true;
            this.AdminShowAllDrinks.AllowMouseEffects = true;
            this.AdminShowAllDrinks.AllowToggling = false;
            this.AdminShowAllDrinks.AnimationSpeed = 200;
            this.AdminShowAllDrinks.AutoGenerateColors = false;
            this.AdminShowAllDrinks.AutoRoundBorders = false;
            this.AdminShowAllDrinks.AutoSizeLeftIcon = true;
            this.AdminShowAllDrinks.AutoSizeRightIcon = true;
            this.AdminShowAllDrinks.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowAllDrinks.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminShowAllDrinks.BackgroundImage")));
            this.AdminShowAllDrinks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllDrinks.ButtonText = "VIEW ALL YOUR DRINKS\r\n";
            this.AdminShowAllDrinks.ButtonTextMarginLeft = 0;
            this.AdminShowAllDrinks.ColorContrastOnClick = 45;
            this.AdminShowAllDrinks.ColorContrastOnHover = 45;
            this.AdminShowAllDrinks.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminShowAllDrinks.CustomizableEdges = borderEdges4;
            this.AdminShowAllDrinks.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminShowAllDrinks.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllDrinks.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllDrinks.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllDrinks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminShowAllDrinks.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowAllDrinks.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllDrinks.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminShowAllDrinks.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllDrinks.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminShowAllDrinks.IconMarginLeft = 11;
            this.AdminShowAllDrinks.IconPadding = 10;
            this.AdminShowAllDrinks.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminShowAllDrinks.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllDrinks.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminShowAllDrinks.IconSize = 25;
            this.AdminShowAllDrinks.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.IdleBorderRadius = 37;
            this.AdminShowAllDrinks.IdleBorderThickness = 1;
            this.AdminShowAllDrinks.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.IdleIconLeftImage = null;
            this.AdminShowAllDrinks.IdleIconRightImage = null;
            this.AdminShowAllDrinks.IndicateFocus = false;
            this.AdminShowAllDrinks.Location = new System.Drawing.Point(22, 647);
            this.AdminShowAllDrinks.Name = "AdminShowAllDrinks";
            this.AdminShowAllDrinks.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllDrinks.OnDisabledState.BorderRadius = 37;
            this.AdminShowAllDrinks.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllDrinks.OnDisabledState.BorderThickness = 1;
            this.AdminShowAllDrinks.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllDrinks.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllDrinks.OnDisabledState.IconLeftImage = null;
            this.AdminShowAllDrinks.OnDisabledState.IconRightImage = null;
            this.AdminShowAllDrinks.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.onHoverState.BorderRadius = 37;
            this.AdminShowAllDrinks.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllDrinks.onHoverState.BorderThickness = 1;
            this.AdminShowAllDrinks.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminShowAllDrinks.onHoverState.IconLeftImage = null;
            this.AdminShowAllDrinks.onHoverState.IconRightImage = null;
            this.AdminShowAllDrinks.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.OnIdleState.BorderRadius = 37;
            this.AdminShowAllDrinks.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllDrinks.OnIdleState.BorderThickness = 1;
            this.AdminShowAllDrinks.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllDrinks.OnIdleState.IconLeftImage = null;
            this.AdminShowAllDrinks.OnIdleState.IconRightImage = null;
            this.AdminShowAllDrinks.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.OnPressedState.BorderRadius = 37;
            this.AdminShowAllDrinks.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllDrinks.OnPressedState.BorderThickness = 1;
            this.AdminShowAllDrinks.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllDrinks.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllDrinks.OnPressedState.IconLeftImage = null;
            this.AdminShowAllDrinks.OnPressedState.IconRightImage = null;
            this.AdminShowAllDrinks.Size = new System.Drawing.Size(214, 36);
            this.AdminShowAllDrinks.TabIndex = 48;
            this.AdminShowAllDrinks.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminShowAllDrinks.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminShowAllDrinks.TextMarginLeft = 0;
            this.AdminShowAllDrinks.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminShowAllDrinks.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillDrinkName
            // 
            this.AdminFillDrinkName.AcceptsReturn = false;
            this.AdminFillDrinkName.AcceptsTab = false;
            this.AdminFillDrinkName.AnimationSpeed = 200;
            this.AdminFillDrinkName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkName.BackgroundImage")));
            this.AdminFillDrinkName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkName.BorderRadius = 1;
            this.AdminFillDrinkName.BorderThickness = 1;
            this.AdminFillDrinkName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillDrinkName.DefaultText = "";
            this.AdminFillDrinkName.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkName.HideSelection = true;
            this.AdminFillDrinkName.IconLeft = null;
            this.AdminFillDrinkName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.IconPadding = 10;
            this.AdminFillDrinkName.IconRight = null;
            this.AdminFillDrinkName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.Lines = new string[0];
            this.AdminFillDrinkName.Location = new System.Drawing.Point(716, 39);
            this.AdminFillDrinkName.MaxLength = 32767;
            this.AdminFillDrinkName.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillDrinkName.Modified = false;
            this.AdminFillDrinkName.Multiline = false;
            this.AdminFillDrinkName.Name = "AdminFillDrinkName";
            stateProperties13.BorderColor = System.Drawing.Color.Transparent;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Transparent;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnIdleState = stateProperties16;
            this.AdminFillDrinkName.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillDrinkName.PasswordChar = '\0';
            this.AdminFillDrinkName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkName.PlaceholderText = "Fill your Drink\'s Name";
            this.AdminFillDrinkName.ReadOnly = false;
            this.AdminFillDrinkName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkName.SelectedText = "";
            this.AdminFillDrinkName.SelectionLength = 0;
            this.AdminFillDrinkName.SelectionStart = 0;
            this.AdminFillDrinkName.ShortcutsEnabled = true;
            this.AdminFillDrinkName.Size = new System.Drawing.Size(330, 37);
            this.AdminFillDrinkName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkName.TabIndex = 47;
            this.AdminFillDrinkName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkName.TextMarginBottom = 0;
            this.AdminFillDrinkName.TextMarginLeft = 3;
            this.AdminFillDrinkName.TextMarginTop = 0;
            this.AdminFillDrinkName.TextPlaceholder = "Fill your Drink\'s Name";
            this.AdminFillDrinkName.UseSystemPasswordChar = false;
            this.AdminFillDrinkName.WordWrap = true;
            // 
            // AdminCheckDrink
            // 
            this.AdminCheckDrink.AllowAnimations = true;
            this.AdminCheckDrink.AllowMouseEffects = true;
            this.AdminCheckDrink.AllowToggling = false;
            this.AdminCheckDrink.AnimationSpeed = 200;
            this.AdminCheckDrink.AutoGenerateColors = false;
            this.AdminCheckDrink.AutoRoundBorders = false;
            this.AdminCheckDrink.AutoSizeLeftIcon = true;
            this.AdminCheckDrink.AutoSizeRightIcon = true;
            this.AdminCheckDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckDrink.BackgroundImage")));
            this.AdminCheckDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.ButtonText = "CHECK";
            this.AdminCheckDrink.ButtonTextMarginLeft = 0;
            this.AdminCheckDrink.ColorContrastOnClick = 45;
            this.AdminCheckDrink.ColorContrastOnHover = 45;
            this.AdminCheckDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminCheckDrink.CustomizableEdges = borderEdges5;
            this.AdminCheckDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckDrink.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckDrink.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckDrink.IconMarginLeft = 11;
            this.AdminCheckDrink.IconPadding = 10;
            this.AdminCheckDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckDrink.IconSize = 25;
            this.AdminCheckDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.IdleBorderRadius = 37;
            this.AdminCheckDrink.IdleBorderThickness = 1;
            this.AdminCheckDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.IdleIconLeftImage = null;
            this.AdminCheckDrink.IdleIconRightImage = null;
            this.AdminCheckDrink.IndicateFocus = false;
            this.AdminCheckDrink.Location = new System.Drawing.Point(716, 96);
            this.AdminCheckDrink.Name = "AdminCheckDrink";
            this.AdminCheckDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckDrink.OnDisabledState.BorderRadius = 37;
            this.AdminCheckDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnDisabledState.BorderThickness = 1;
            this.AdminCheckDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckDrink.OnDisabledState.IconLeftImage = null;
            this.AdminCheckDrink.OnDisabledState.IconRightImage = null;
            this.AdminCheckDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.onHoverState.BorderRadius = 37;
            this.AdminCheckDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.onHoverState.BorderThickness = 1;
            this.AdminCheckDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckDrink.onHoverState.IconLeftImage = null;
            this.AdminCheckDrink.onHoverState.IconRightImage = null;
            this.AdminCheckDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnIdleState.BorderRadius = 37;
            this.AdminCheckDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnIdleState.BorderThickness = 1;
            this.AdminCheckDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.OnIdleState.IconLeftImage = null;
            this.AdminCheckDrink.OnIdleState.IconRightImage = null;
            this.AdminCheckDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnPressedState.BorderRadius = 37;
            this.AdminCheckDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnPressedState.BorderThickness = 1;
            this.AdminCheckDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.OnPressedState.IconLeftImage = null;
            this.AdminCheckDrink.OnPressedState.IconRightImage = null;
            this.AdminCheckDrink.Size = new System.Drawing.Size(330, 36);
            this.AdminCheckDrink.TabIndex = 46;
            this.AdminCheckDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckDrink.TextMarginLeft = 0;
            this.AdminCheckDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDrink
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.AdminUpdateDrink);
            this.Controls.Add(this.AdminDeleteDrink);
            this.Controls.Add(this.AdminAddDrink);
            this.Controls.Add(this.AdminFillDrinkPrice);
            this.Controls.Add(this.AdminFillDrinkAvailable);
            this.Controls.Add(this.AdminFillDrinkType);
            this.Controls.Add(this.AdminViewAllCustomer);
            this.Controls.Add(this.AdminShowAllDrinks);
            this.Controls.Add(this.AdminFillDrinkName);
            this.Controls.Add(this.AdminCheckDrink);
            this.Name = "AdminDrink";
            this.Size = new System.Drawing.Size(1069, 705);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddDrink;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkPrice;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkAvailable;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkType;
        private System.Windows.Forms.ListView AdminViewAllCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminShowAllDrinks;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckDrink;
    }
}
