namespace UI
{
    partial class AdminTable
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminTable));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminUpdateTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillTableName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminShowAllTables = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillTableID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminTablesView = new System.Windows.Forms.DataGridView();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            ((System.ComponentModel.ISupportInitialize)(this.AdminTablesView)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminUpdateTable
            // 
            this.AdminUpdateTable.AllowAnimations = true;
            this.AdminUpdateTable.AllowMouseEffects = true;
            this.AdminUpdateTable.AllowToggling = false;
            this.AdminUpdateTable.AnimationSpeed = 200;
            this.AdminUpdateTable.AutoGenerateColors = false;
            this.AdminUpdateTable.AutoRoundBorders = false;
            this.AdminUpdateTable.AutoSizeLeftIcon = true;
            this.AdminUpdateTable.AutoSizeRightIcon = true;
            this.AdminUpdateTable.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateTable.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateTable.BackgroundImage")));
            this.AdminUpdateTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateTable.ButtonText = "Update";
            this.AdminUpdateTable.ButtonTextMarginLeft = 0;
            this.AdminUpdateTable.ColorContrastOnClick = 45;
            this.AdminUpdateTable.ColorContrastOnHover = 45;
            this.AdminUpdateTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.AdminUpdateTable.CustomizableEdges = borderEdges6;
            this.AdminUpdateTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateTable.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateTable.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateTable.IconMarginLeft = 11;
            this.AdminUpdateTable.IconPadding = 10;
            this.AdminUpdateTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateTable.IconSize = 25;
            this.AdminUpdateTable.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.IdleBorderRadius = 37;
            this.AdminUpdateTable.IdleBorderThickness = 1;
            this.AdminUpdateTable.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.IdleIconLeftImage = null;
            this.AdminUpdateTable.IdleIconRightImage = null;
            this.AdminUpdateTable.IndicateFocus = false;
            this.AdminUpdateTable.Location = new System.Drawing.Point(441, 249);
            this.AdminUpdateTable.Name = "AdminUpdateTable";
            this.AdminUpdateTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateTable.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateTable.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateTable.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateTable.OnDisabledState.IconRightImage = null;
            this.AdminUpdateTable.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.onHoverState.BorderRadius = 37;
            this.AdminUpdateTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateTable.onHoverState.BorderThickness = 1;
            this.AdminUpdateTable.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateTable.onHoverState.IconLeftImage = null;
            this.AdminUpdateTable.onHoverState.IconRightImage = null;
            this.AdminUpdateTable.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.OnIdleState.BorderRadius = 37;
            this.AdminUpdateTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateTable.OnIdleState.BorderThickness = 1;
            this.AdminUpdateTable.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateTable.OnIdleState.IconLeftImage = null;
            this.AdminUpdateTable.OnIdleState.IconRightImage = null;
            this.AdminUpdateTable.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.OnPressedState.BorderRadius = 37;
            this.AdminUpdateTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateTable.OnPressedState.BorderThickness = 1;
            this.AdminUpdateTable.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateTable.OnPressedState.IconLeftImage = null;
            this.AdminUpdateTable.OnPressedState.IconRightImage = null;
            this.AdminUpdateTable.Size = new System.Drawing.Size(270, 36);
            this.AdminUpdateTable.TabIndex = 58;
            this.AdminUpdateTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateTable.TextMarginLeft = 0;
            this.AdminUpdateTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateTable.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteTable
            // 
            this.AdminDeleteTable.AllowAnimations = true;
            this.AdminDeleteTable.AllowMouseEffects = true;
            this.AdminDeleteTable.AllowToggling = false;
            this.AdminDeleteTable.AnimationSpeed = 200;
            this.AdminDeleteTable.AutoGenerateColors = false;
            this.AdminDeleteTable.AutoRoundBorders = false;
            this.AdminDeleteTable.AutoSizeLeftIcon = true;
            this.AdminDeleteTable.AutoSizeRightIcon = true;
            this.AdminDeleteTable.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteTable.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteTable.BackgroundImage")));
            this.AdminDeleteTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteTable.ButtonText = "DELETE";
            this.AdminDeleteTable.ButtonTextMarginLeft = 0;
            this.AdminDeleteTable.ColorContrastOnClick = 45;
            this.AdminDeleteTable.ColorContrastOnHover = 45;
            this.AdminDeleteTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.AdminDeleteTable.CustomizableEdges = borderEdges7;
            this.AdminDeleteTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteTable.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteTable.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteTable.IconMarginLeft = 11;
            this.AdminDeleteTable.IconPadding = 10;
            this.AdminDeleteTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteTable.IconSize = 25;
            this.AdminDeleteTable.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.IdleBorderRadius = 37;
            this.AdminDeleteTable.IdleBorderThickness = 1;
            this.AdminDeleteTable.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.IdleIconLeftImage = null;
            this.AdminDeleteTable.IdleIconRightImage = null;
            this.AdminDeleteTable.IndicateFocus = false;
            this.AdminDeleteTable.Location = new System.Drawing.Point(611, 207);
            this.AdminDeleteTable.Name = "AdminDeleteTable";
            this.AdminDeleteTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteTable.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteTable.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteTable.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteTable.OnDisabledState.IconRightImage = null;
            this.AdminDeleteTable.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.onHoverState.BorderRadius = 37;
            this.AdminDeleteTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteTable.onHoverState.BorderThickness = 1;
            this.AdminDeleteTable.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteTable.onHoverState.IconLeftImage = null;
            this.AdminDeleteTable.onHoverState.IconRightImage = null;
            this.AdminDeleteTable.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.OnIdleState.BorderRadius = 37;
            this.AdminDeleteTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteTable.OnIdleState.BorderThickness = 1;
            this.AdminDeleteTable.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteTable.OnIdleState.IconLeftImage = null;
            this.AdminDeleteTable.OnIdleState.IconRightImage = null;
            this.AdminDeleteTable.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.OnPressedState.BorderRadius = 37;
            this.AdminDeleteTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteTable.OnPressedState.BorderThickness = 1;
            this.AdminDeleteTable.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteTable.OnPressedState.IconLeftImage = null;
            this.AdminDeleteTable.OnPressedState.IconRightImage = null;
            this.AdminDeleteTable.Size = new System.Drawing.Size(100, 36);
            this.AdminDeleteTable.TabIndex = 57;
            this.AdminDeleteTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteTable.TextMarginLeft = 0;
            this.AdminDeleteTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteTable.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddTable
            // 
            this.AdminAddTable.AllowAnimations = true;
            this.AdminAddTable.AllowMouseEffects = true;
            this.AdminAddTable.AllowToggling = false;
            this.AdminAddTable.AnimationSpeed = 200;
            this.AdminAddTable.AutoGenerateColors = false;
            this.AdminAddTable.AutoRoundBorders = false;
            this.AdminAddTable.AutoSizeLeftIcon = true;
            this.AdminAddTable.AutoSizeRightIcon = true;
            this.AdminAddTable.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddTable.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddTable.BackgroundImage")));
            this.AdminAddTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddTable.ButtonText = "ADD";
            this.AdminAddTable.ButtonTextMarginLeft = 0;
            this.AdminAddTable.ColorContrastOnClick = 45;
            this.AdminAddTable.ColorContrastOnHover = 45;
            this.AdminAddTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.AdminAddTable.CustomizableEdges = borderEdges8;
            this.AdminAddTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddTable.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddTable.ForeColor = System.Drawing.Color.White;
            this.AdminAddTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddTable.IconMarginLeft = 11;
            this.AdminAddTable.IconPadding = 10;
            this.AdminAddTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddTable.IconSize = 25;
            this.AdminAddTable.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.IdleBorderRadius = 37;
            this.AdminAddTable.IdleBorderThickness = 1;
            this.AdminAddTable.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.IdleIconLeftImage = null;
            this.AdminAddTable.IdleIconRightImage = null;
            this.AdminAddTable.IndicateFocus = false;
            this.AdminAddTable.Location = new System.Drawing.Point(441, 207);
            this.AdminAddTable.Name = "AdminAddTable";
            this.AdminAddTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddTable.OnDisabledState.BorderRadius = 37;
            this.AdminAddTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddTable.OnDisabledState.BorderThickness = 1;
            this.AdminAddTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddTable.OnDisabledState.IconLeftImage = null;
            this.AdminAddTable.OnDisabledState.IconRightImage = null;
            this.AdminAddTable.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.onHoverState.BorderRadius = 37;
            this.AdminAddTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddTable.onHoverState.BorderThickness = 1;
            this.AdminAddTable.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddTable.onHoverState.IconLeftImage = null;
            this.AdminAddTable.onHoverState.IconRightImage = null;
            this.AdminAddTable.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.OnIdleState.BorderRadius = 37;
            this.AdminAddTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddTable.OnIdleState.BorderThickness = 1;
            this.AdminAddTable.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddTable.OnIdleState.IconLeftImage = null;
            this.AdminAddTable.OnIdleState.IconRightImage = null;
            this.AdminAddTable.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.OnPressedState.BorderRadius = 37;
            this.AdminAddTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddTable.OnPressedState.BorderThickness = 1;
            this.AdminAddTable.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddTable.OnPressedState.IconLeftImage = null;
            this.AdminAddTable.OnPressedState.IconRightImage = null;
            this.AdminAddTable.Size = new System.Drawing.Size(100, 36);
            this.AdminAddTable.TabIndex = 56;
            this.AdminAddTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddTable.TextMarginLeft = 0;
            this.AdminAddTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddTable.UseDefaultRadiusAndThickness = true;
            this.AdminAddTable.Click += new System.EventHandler(this.AdminAddTable_Click);
            // 
            // AdminFillTableName
            // 
            this.AdminFillTableName.AcceptsReturn = false;
            this.AdminFillTableName.AcceptsTab = false;
            this.AdminFillTableName.AnimationSpeed = 200;
            this.AdminFillTableName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillTableName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillTableName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillTableName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillTableName.BackgroundImage")));
            this.AdminFillTableName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillTableName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillTableName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillTableName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillTableName.BorderRadius = 1;
            this.AdminFillTableName.BorderThickness = 1;
            this.AdminFillTableName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillTableName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillTableName.DefaultText = "";
            this.AdminFillTableName.FillColor = System.Drawing.Color.White;
            this.AdminFillTableName.HideSelection = true;
            this.AdminFillTableName.IconLeft = null;
            this.AdminFillTableName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableName.IconPadding = 10;
            this.AdminFillTableName.IconRight = null;
            this.AdminFillTableName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableName.Lines = new string[0];
            this.AdminFillTableName.Location = new System.Drawing.Point(441, 119);
            this.AdminFillTableName.MaxLength = 32767;
            this.AdminFillTableName.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillTableName.Modified = false;
            this.AdminFillTableName.Multiline = false;
            this.AdminFillTableName.Name = "AdminFillTableName";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillTableName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableName.OnIdleState = stateProperties12;
            this.AdminFillTableName.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillTableName.PasswordChar = '\0';
            this.AdminFillTableName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillTableName.PlaceholderText = "Fill your Table\'s Name";
            this.AdminFillTableName.ReadOnly = false;
            this.AdminFillTableName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillTableName.SelectedText = "";
            this.AdminFillTableName.SelectionLength = 0;
            this.AdminFillTableName.SelectionStart = 0;
            this.AdminFillTableName.ShortcutsEnabled = true;
            this.AdminFillTableName.Size = new System.Drawing.Size(270, 37);
            this.AdminFillTableName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillTableName.TabIndex = 50;
            this.AdminFillTableName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillTableName.TextMarginBottom = 0;
            this.AdminFillTableName.TextMarginLeft = 3;
            this.AdminFillTableName.TextMarginTop = 0;
            this.AdminFillTableName.TextPlaceholder = "Fill your Table\'s Name";
            this.AdminFillTableName.UseSystemPasswordChar = false;
            this.AdminFillTableName.WordWrap = true;
            // 
            // AdminShowAllTables
            // 
            this.AdminShowAllTables.AllowAnimations = true;
            this.AdminShowAllTables.AllowMouseEffects = true;
            this.AdminShowAllTables.AllowToggling = false;
            this.AdminShowAllTables.AnimationSpeed = 200;
            this.AdminShowAllTables.AutoGenerateColors = false;
            this.AdminShowAllTables.AutoRoundBorders = false;
            this.AdminShowAllTables.AutoSizeLeftIcon = true;
            this.AdminShowAllTables.AutoSizeRightIcon = true;
            this.AdminShowAllTables.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowAllTables.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminShowAllTables.BackgroundImage")));
            this.AdminShowAllTables.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllTables.ButtonText = "VIEW ALL YOUR TABLES";
            this.AdminShowAllTables.ButtonTextMarginLeft = 0;
            this.AdminShowAllTables.ColorContrastOnClick = 45;
            this.AdminShowAllTables.ColorContrastOnHover = 45;
            this.AdminShowAllTables.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.AdminShowAllTables.CustomizableEdges = borderEdges9;
            this.AdminShowAllTables.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminShowAllTables.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllTables.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllTables.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllTables.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminShowAllTables.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowAllTables.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllTables.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminShowAllTables.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllTables.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminShowAllTables.IconMarginLeft = 11;
            this.AdminShowAllTables.IconPadding = 10;
            this.AdminShowAllTables.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminShowAllTables.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllTables.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminShowAllTables.IconSize = 25;
            this.AdminShowAllTables.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.IdleBorderRadius = 37;
            this.AdminShowAllTables.IdleBorderThickness = 1;
            this.AdminShowAllTables.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.IdleIconLeftImage = null;
            this.AdminShowAllTables.IdleIconRightImage = null;
            this.AdminShowAllTables.IndicateFocus = false;
            this.AdminShowAllTables.Location = new System.Drawing.Point(22, 647);
            this.AdminShowAllTables.Name = "AdminShowAllTables";
            this.AdminShowAllTables.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllTables.OnDisabledState.BorderRadius = 37;
            this.AdminShowAllTables.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllTables.OnDisabledState.BorderThickness = 1;
            this.AdminShowAllTables.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllTables.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllTables.OnDisabledState.IconLeftImage = null;
            this.AdminShowAllTables.OnDisabledState.IconRightImage = null;
            this.AdminShowAllTables.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.onHoverState.BorderRadius = 37;
            this.AdminShowAllTables.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllTables.onHoverState.BorderThickness = 1;
            this.AdminShowAllTables.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminShowAllTables.onHoverState.IconLeftImage = null;
            this.AdminShowAllTables.onHoverState.IconRightImage = null;
            this.AdminShowAllTables.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.OnIdleState.BorderRadius = 37;
            this.AdminShowAllTables.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllTables.OnIdleState.BorderThickness = 1;
            this.AdminShowAllTables.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllTables.OnIdleState.IconLeftImage = null;
            this.AdminShowAllTables.OnIdleState.IconRightImage = null;
            this.AdminShowAllTables.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.OnPressedState.BorderRadius = 37;
            this.AdminShowAllTables.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllTables.OnPressedState.BorderThickness = 1;
            this.AdminShowAllTables.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllTables.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllTables.OnPressedState.IconLeftImage = null;
            this.AdminShowAllTables.OnPressedState.IconRightImage = null;
            this.AdminShowAllTables.Size = new System.Drawing.Size(214, 36);
            this.AdminShowAllTables.TabIndex = 48;
            this.AdminShowAllTables.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminShowAllTables.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminShowAllTables.TextMarginLeft = 0;
            this.AdminShowAllTables.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminShowAllTables.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillTableID
            // 
            this.AdminFillTableID.AcceptsReturn = false;
            this.AdminFillTableID.AcceptsTab = false;
            this.AdminFillTableID.AnimationSpeed = 200;
            this.AdminFillTableID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillTableID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillTableID.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillTableID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillTableID.BackgroundImage")));
            this.AdminFillTableID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillTableID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillTableID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillTableID.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillTableID.BorderRadius = 1;
            this.AdminFillTableID.BorderThickness = 1;
            this.AdminFillTableID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillTableID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillTableID.DefaultText = "";
            this.AdminFillTableID.FillColor = System.Drawing.Color.White;
            this.AdminFillTableID.HideSelection = true;
            this.AdminFillTableID.IconLeft = null;
            this.AdminFillTableID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableID.IconPadding = 10;
            this.AdminFillTableID.IconRight = null;
            this.AdminFillTableID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillTableID.Lines = new string[0];
            this.AdminFillTableID.Location = new System.Drawing.Point(441, 34);
            this.AdminFillTableID.MaxLength = 32767;
            this.AdminFillTableID.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillTableID.Modified = false;
            this.AdminFillTableID.Multiline = false;
            this.AdminFillTableID.Name = "AdminFillTableID";
            stateProperties13.BorderColor = System.Drawing.Color.Transparent;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Transparent;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillTableID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillTableID.OnIdleState = stateProperties16;
            this.AdminFillTableID.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillTableID.PasswordChar = '\0';
            this.AdminFillTableID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillTableID.PlaceholderText = "Fill Table\'s Id";
            this.AdminFillTableID.ReadOnly = false;
            this.AdminFillTableID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillTableID.SelectedText = "";
            this.AdminFillTableID.SelectionLength = 0;
            this.AdminFillTableID.SelectionStart = 0;
            this.AdminFillTableID.ShortcutsEnabled = true;
            this.AdminFillTableID.Size = new System.Drawing.Size(270, 37);
            this.AdminFillTableID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillTableID.TabIndex = 47;
            this.AdminFillTableID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillTableID.TextMarginBottom = 0;
            this.AdminFillTableID.TextMarginLeft = 3;
            this.AdminFillTableID.TextMarginTop = 0;
            this.AdminFillTableID.TextPlaceholder = "Fill Table\'s Id";
            this.AdminFillTableID.UseSystemPasswordChar = false;
            this.AdminFillTableID.WordWrap = true;
            // 
            // AdminCheckTable
            // 
            this.AdminCheckTable.AllowAnimations = true;
            this.AdminCheckTable.AllowMouseEffects = true;
            this.AdminCheckTable.AllowToggling = false;
            this.AdminCheckTable.AnimationSpeed = 200;
            this.AdminCheckTable.AutoGenerateColors = false;
            this.AdminCheckTable.AutoRoundBorders = false;
            this.AdminCheckTable.AutoSizeLeftIcon = true;
            this.AdminCheckTable.AutoSizeRightIcon = true;
            this.AdminCheckTable.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckTable.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckTable.BackgroundImage")));
            this.AdminCheckTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckTable.ButtonText = "CHECK";
            this.AdminCheckTable.ButtonTextMarginLeft = 0;
            this.AdminCheckTable.ColorContrastOnClick = 45;
            this.AdminCheckTable.ColorContrastOnHover = 45;
            this.AdminCheckTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.AdminCheckTable.CustomizableEdges = borderEdges10;
            this.AdminCheckTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckTable.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckTable.ForeColor = System.Drawing.Color.White;
            this.AdminCheckTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckTable.IconMarginLeft = 11;
            this.AdminCheckTable.IconPadding = 10;
            this.AdminCheckTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckTable.IconSize = 25;
            this.AdminCheckTable.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.IdleBorderRadius = 37;
            this.AdminCheckTable.IdleBorderThickness = 1;
            this.AdminCheckTable.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.IdleIconLeftImage = null;
            this.AdminCheckTable.IdleIconRightImage = null;
            this.AdminCheckTable.IndicateFocus = false;
            this.AdminCheckTable.Location = new System.Drawing.Point(441, 77);
            this.AdminCheckTable.Name = "AdminCheckTable";
            this.AdminCheckTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckTable.OnDisabledState.BorderRadius = 37;
            this.AdminCheckTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckTable.OnDisabledState.BorderThickness = 1;
            this.AdminCheckTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckTable.OnDisabledState.IconLeftImage = null;
            this.AdminCheckTable.OnDisabledState.IconRightImage = null;
            this.AdminCheckTable.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.onHoverState.BorderRadius = 37;
            this.AdminCheckTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckTable.onHoverState.BorderThickness = 1;
            this.AdminCheckTable.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckTable.onHoverState.IconLeftImage = null;
            this.AdminCheckTable.onHoverState.IconRightImage = null;
            this.AdminCheckTable.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.OnIdleState.BorderRadius = 37;
            this.AdminCheckTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckTable.OnIdleState.BorderThickness = 1;
            this.AdminCheckTable.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckTable.OnIdleState.IconLeftImage = null;
            this.AdminCheckTable.OnIdleState.IconRightImage = null;
            this.AdminCheckTable.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.OnPressedState.BorderRadius = 37;
            this.AdminCheckTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckTable.OnPressedState.BorderThickness = 1;
            this.AdminCheckTable.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckTable.OnPressedState.IconLeftImage = null;
            this.AdminCheckTable.OnPressedState.IconRightImage = null;
            this.AdminCheckTable.Size = new System.Drawing.Size(270, 36);
            this.AdminCheckTable.TabIndex = 46;
            this.AdminCheckTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckTable.TextMarginLeft = 0;
            this.AdminCheckTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckTable.UseDefaultRadiusAndThickness = true;
            this.AdminCheckTable.Click += new System.EventHandler(this.AdminCheckTable_Click);
            // 
            // AdminTablesView
            // 
            this.AdminTablesView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.AdminTablesView.Location = new System.Drawing.Point(22, 34);
            this.AdminTablesView.Name = "AdminTablesView";
            this.AdminTablesView.RowHeadersWidth = 62;
            this.AdminTablesView.Size = new System.Drawing.Size(397, 424);
            this.AdminTablesView.TabIndex = 59;
            // 
            // comboBox1
            // 
            this.comboBox1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "Available",
            "Booked"});
            this.comboBox1.Location = new System.Drawing.Point(441, 162);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(270, 28);
            this.comboBox1.TabIndex = 60;
            // 
            // AdminTable
            // 
            this.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.AdminTablesView);
            this.Controls.Add(this.AdminUpdateTable);
            this.Controls.Add(this.AdminDeleteTable);
            this.Controls.Add(this.AdminAddTable);
            this.Controls.Add(this.AdminFillTableName);
            this.Controls.Add(this.AdminShowAllTables);
            this.Controls.Add(this.AdminFillTableID);
            this.Controls.Add(this.AdminCheckTable);
            this.Name = "AdminTable";
            this.Size = new System.Drawing.Size(731, 483);
            this.Load += new System.EventHandler(this.AdminTable_Load);
            ((System.ComponentModel.ISupportInitialize)(this.AdminTablesView)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateTable;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteTable;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddTable;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillTableName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminShowAllTables;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillTableID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckTable;
        private System.Windows.Forms.DataGridView AdminTablesView;
        private System.Windows.Forms.ComboBox comboBox1;
    }
}
