namespace UI
{
    partial class AdminFP
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminFP));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.AdminPanelGrid = new System.Windows.Forms.Panel();
            this.pictureBox10 = new System.Windows.Forms.PictureBox();
            this.AdminUserImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.AdminUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminReviewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminCustomerBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFinancialBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminEmployeeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminOrderBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminMenuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminMainPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.AdminPanelGrid.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AdminUserImg)).BeginInit();
            this.SuspendLayout();
            // 
            // AdminPanelGrid
            // 
            this.AdminPanelGrid.BackColor = System.Drawing.Color.LightSalmon;
            this.AdminPanelGrid.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.AdminPanelGrid.Controls.Add(this.pictureBox10);
            this.AdminPanelGrid.Controls.Add(this.AdminReviewBtn);
            this.AdminPanelGrid.Controls.Add(this.AdminUserImg);
            this.AdminPanelGrid.Controls.Add(this.AdminCustomerBtn);
            this.AdminPanelGrid.Controls.Add(this.AdminUser);
            this.AdminPanelGrid.Controls.Add(this.AdminMenuBtn);
            this.AdminPanelGrid.Controls.Add(this.AdminFinancialBtn);
            this.AdminPanelGrid.Controls.Add(this.AdminOrderBtn);
            this.AdminPanelGrid.Controls.Add(this.AdminEmployeeBtn);
            this.AdminPanelGrid.Dock = System.Windows.Forms.DockStyle.Left;
            this.AdminPanelGrid.Location = new System.Drawing.Point(0, 0);
            this.AdminPanelGrid.Margin = new System.Windows.Forms.Padding(2);
            this.AdminPanelGrid.Name = "AdminPanelGrid";
            this.AdminPanelGrid.Size = new System.Drawing.Size(232, 484);
            this.AdminPanelGrid.TabIndex = 0;
            this.AdminPanelGrid.Paint += new System.Windows.Forms.PaintEventHandler(this.AdminPanelGrid_Paint);
            // 
            // pictureBox10
            // 
            this.pictureBox10.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox10.Image")));
            this.pictureBox10.Location = new System.Drawing.Point(0, 322);
            this.pictureBox10.Name = "pictureBox10";
            this.pictureBox10.Size = new System.Drawing.Size(232, 162);
            this.pictureBox10.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox10.TabIndex = 28;
            this.pictureBox10.TabStop = false;
            // 
            // AdminUserImg
            // 
            this.AdminUserImg.AllowFocused = false;
            this.AdminUserImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.AdminUserImg.AutoSizeHeight = true;
            this.AdminUserImg.BackColor = System.Drawing.Color.Transparent;
            this.AdminUserImg.BorderRadius = 32;
            this.AdminUserImg.Image = ((System.Drawing.Image)(resources.GetObject("AdminUserImg.Image")));
            this.AdminUserImg.IsCircle = true;
            this.AdminUserImg.Location = new System.Drawing.Point(27, 11);
            this.AdminUserImg.Margin = new System.Windows.Forms.Padding(2);
            this.AdminUserImg.Name = "AdminUserImg";
            this.AdminUserImg.Size = new System.Drawing.Size(65, 65);
            this.AdminUserImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.AdminUserImg.TabIndex = 1;
            this.AdminUserImg.TabStop = false;
            this.AdminUserImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // AdminUser
            // 
            this.AdminUser.AllowAnimations = true;
            this.AdminUser.AllowMouseEffects = true;
            this.AdminUser.AllowToggling = false;
            this.AdminUser.AnimationSpeed = 200;
            this.AdminUser.AutoGenerateColors = false;
            this.AdminUser.AutoRoundBorders = false;
            this.AdminUser.AutoSizeLeftIcon = true;
            this.AdminUser.AutoSizeRightIcon = true;
            this.AdminUser.BackColor = System.Drawing.Color.Transparent;
            this.AdminUser.BackColor1 = System.Drawing.Color.White;
            this.AdminUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUser.BackgroundImage")));
            this.AdminUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUser.ButtonText = "ADMIN";
            this.AdminUser.ButtonTextMarginLeft = 0;
            this.AdminUser.ColorContrastOnClick = 45;
            this.AdminUser.ColorContrastOnHover = 45;
            this.AdminUser.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminUser.CustomizableEdges = borderEdges3;
            this.AdminUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUser.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUser.ForeColor = System.Drawing.Color.LightSalmon;
            this.AdminUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUser.IconMarginLeft = 11;
            this.AdminUser.IconPadding = 10;
            this.AdminUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUser.IconSize = 25;
            this.AdminUser.IdleBorderColor = System.Drawing.Color.White;
            this.AdminUser.IdleBorderRadius = 37;
            this.AdminUser.IdleBorderThickness = 1;
            this.AdminUser.IdleFillColor = System.Drawing.Color.White;
            this.AdminUser.IdleIconLeftImage = null;
            this.AdminUser.IdleIconRightImage = null;
            this.AdminUser.IndicateFocus = false;
            this.AdminUser.Location = new System.Drawing.Point(68, 27);
            this.AdminUser.Margin = new System.Windows.Forms.Padding(2);
            this.AdminUser.Name = "AdminUser";
            this.AdminUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUser.OnDisabledState.BorderRadius = 37;
            this.AdminUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUser.OnDisabledState.BorderThickness = 1;
            this.AdminUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUser.OnDisabledState.IconLeftImage = null;
            this.AdminUser.OnDisabledState.IconRightImage = null;
            this.AdminUser.onHoverState.BorderColor = System.Drawing.Color.White;
            this.AdminUser.onHoverState.BorderRadius = 37;
            this.AdminUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUser.onHoverState.BorderThickness = 1;
            this.AdminUser.onHoverState.FillColor = System.Drawing.Color.White;
            this.AdminUser.onHoverState.ForeColor = System.Drawing.Color.LightSalmon;
            this.AdminUser.onHoverState.IconLeftImage = null;
            this.AdminUser.onHoverState.IconRightImage = null;
            this.AdminUser.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.AdminUser.OnIdleState.BorderRadius = 37;
            this.AdminUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUser.OnIdleState.BorderThickness = 1;
            this.AdminUser.OnIdleState.FillColor = System.Drawing.Color.White;
            this.AdminUser.OnIdleState.ForeColor = System.Drawing.Color.LightSalmon;
            this.AdminUser.OnIdleState.IconLeftImage = null;
            this.AdminUser.OnIdleState.IconRightImage = null;
            this.AdminUser.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.AdminUser.OnPressedState.BorderRadius = 37;
            this.AdminUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUser.OnPressedState.BorderThickness = 1;
            this.AdminUser.OnPressedState.FillColor = System.Drawing.Color.White;
            this.AdminUser.OnPressedState.ForeColor = System.Drawing.Color.LightSalmon;
            this.AdminUser.OnPressedState.IconLeftImage = null;
            this.AdminUser.OnPressedState.IconRightImage = null;
            this.AdminUser.Size = new System.Drawing.Size(139, 38);
            this.AdminUser.TabIndex = 27;
            this.AdminUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUser.TextMarginLeft = 0;
            this.AdminUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUser.UseDefaultRadiusAndThickness = true;
            // 
            // AdminReviewBtn
            // 
            this.AdminReviewBtn.AllowAnimations = true;
            this.AdminReviewBtn.AllowMouseEffects = true;
            this.AdminReviewBtn.AllowToggling = false;
            this.AdminReviewBtn.AnimationSpeed = 200;
            this.AdminReviewBtn.AutoGenerateColors = false;
            this.AdminReviewBtn.AutoRoundBorders = false;
            this.AdminReviewBtn.AutoSizeLeftIcon = true;
            this.AdminReviewBtn.AutoSizeRightIcon = true;
            this.AdminReviewBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminReviewBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminReviewBtn.BackgroundImage")));
            this.AdminReviewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminReviewBtn.ButtonText = "REVIEW";
            this.AdminReviewBtn.ButtonTextMarginLeft = 0;
            this.AdminReviewBtn.ColorContrastOnClick = 45;
            this.AdminReviewBtn.ColorContrastOnHover = 45;
            this.AdminReviewBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminReviewBtn.CustomizableEdges = borderEdges1;
            this.AdminReviewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminReviewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminReviewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminReviewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminReviewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminReviewBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminReviewBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminReviewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminReviewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminReviewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminReviewBtn.IconMarginLeft = 11;
            this.AdminReviewBtn.IconPadding = 10;
            this.AdminReviewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminReviewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminReviewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminReviewBtn.IconSize = 25;
            this.AdminReviewBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.IdleBorderRadius = 1;
            this.AdminReviewBtn.IdleBorderThickness = 1;
            this.AdminReviewBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.IdleIconLeftImage = null;
            this.AdminReviewBtn.IdleIconRightImage = null;
            this.AdminReviewBtn.IndicateFocus = false;
            this.AdminReviewBtn.Location = new System.Drawing.Point(0, 279);
            this.AdminReviewBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminReviewBtn.Name = "AdminReviewBtn";
            this.AdminReviewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminReviewBtn.OnDisabledState.BorderRadius = 1;
            this.AdminReviewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminReviewBtn.OnDisabledState.BorderThickness = 1;
            this.AdminReviewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminReviewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminReviewBtn.OnDisabledState.IconLeftImage = null;
            this.AdminReviewBtn.OnDisabledState.IconRightImage = null;
            this.AdminReviewBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.onHoverState.BorderRadius = 1;
            this.AdminReviewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminReviewBtn.onHoverState.BorderThickness = 1;
            this.AdminReviewBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminReviewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminReviewBtn.onHoverState.IconLeftImage = null;
            this.AdminReviewBtn.onHoverState.IconRightImage = null;
            this.AdminReviewBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.OnIdleState.BorderRadius = 1;
            this.AdminReviewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminReviewBtn.OnIdleState.BorderThickness = 1;
            this.AdminReviewBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminReviewBtn.OnIdleState.IconLeftImage = null;
            this.AdminReviewBtn.OnIdleState.IconRightImage = null;
            this.AdminReviewBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminReviewBtn.OnPressedState.BorderRadius = 1;
            this.AdminReviewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminReviewBtn.OnPressedState.BorderThickness = 1;
            this.AdminReviewBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminReviewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminReviewBtn.OnPressedState.IconLeftImage = null;
            this.AdminReviewBtn.OnPressedState.IconRightImage = null;
            this.AdminReviewBtn.Size = new System.Drawing.Size(232, 38);
            this.AdminReviewBtn.TabIndex = 26;
            this.AdminReviewBtn.TabStop = false;
            this.AdminReviewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminReviewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminReviewBtn.TextMarginLeft = 0;
            this.AdminReviewBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminReviewBtn.UseDefaultRadiusAndThickness = true;
            this.AdminReviewBtn.Click += new System.EventHandler(this.AdminReviewBtn_Click);
            // 
            // AdminCustomerBtn
            // 
            this.AdminCustomerBtn.AllowAnimations = true;
            this.AdminCustomerBtn.AllowMouseEffects = true;
            this.AdminCustomerBtn.AllowToggling = false;
            this.AdminCustomerBtn.AnimationSpeed = 200;
            this.AdminCustomerBtn.AutoGenerateColors = false;
            this.AdminCustomerBtn.AutoRoundBorders = false;
            this.AdminCustomerBtn.AutoSizeLeftIcon = true;
            this.AdminCustomerBtn.AutoSizeRightIcon = true;
            this.AdminCustomerBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminCustomerBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCustomerBtn.BackgroundImage")));
            this.AdminCustomerBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCustomerBtn.ButtonText = "CUSTOMER";
            this.AdminCustomerBtn.ButtonTextMarginLeft = 0;
            this.AdminCustomerBtn.ColorContrastOnClick = 45;
            this.AdminCustomerBtn.ColorContrastOnHover = 45;
            this.AdminCustomerBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminCustomerBtn.CustomizableEdges = borderEdges2;
            this.AdminCustomerBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCustomerBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCustomerBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCustomerBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCustomerBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCustomerBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCustomerBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminCustomerBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCustomerBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCustomerBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCustomerBtn.IconMarginLeft = 11;
            this.AdminCustomerBtn.IconPadding = 10;
            this.AdminCustomerBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCustomerBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCustomerBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCustomerBtn.IconSize = 25;
            this.AdminCustomerBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.IdleBorderRadius = 1;
            this.AdminCustomerBtn.IdleBorderThickness = 1;
            this.AdminCustomerBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.IdleIconLeftImage = null;
            this.AdminCustomerBtn.IdleIconRightImage = null;
            this.AdminCustomerBtn.IndicateFocus = false;
            this.AdminCustomerBtn.Location = new System.Drawing.Point(2, 241);
            this.AdminCustomerBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminCustomerBtn.Name = "AdminCustomerBtn";
            this.AdminCustomerBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCustomerBtn.OnDisabledState.BorderRadius = 1;
            this.AdminCustomerBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCustomerBtn.OnDisabledState.BorderThickness = 1;
            this.AdminCustomerBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCustomerBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCustomerBtn.OnDisabledState.IconLeftImage = null;
            this.AdminCustomerBtn.OnDisabledState.IconRightImage = null;
            this.AdminCustomerBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.onHoverState.BorderRadius = 1;
            this.AdminCustomerBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCustomerBtn.onHoverState.BorderThickness = 1;
            this.AdminCustomerBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminCustomerBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCustomerBtn.onHoverState.IconLeftImage = null;
            this.AdminCustomerBtn.onHoverState.IconRightImage = null;
            this.AdminCustomerBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.OnIdleState.BorderRadius = 1;
            this.AdminCustomerBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCustomerBtn.OnIdleState.BorderThickness = 1;
            this.AdminCustomerBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminCustomerBtn.OnIdleState.IconLeftImage = null;
            this.AdminCustomerBtn.OnIdleState.IconRightImage = null;
            this.AdminCustomerBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCustomerBtn.OnPressedState.BorderRadius = 1;
            this.AdminCustomerBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCustomerBtn.OnPressedState.BorderThickness = 1;
            this.AdminCustomerBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminCustomerBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminCustomerBtn.OnPressedState.IconLeftImage = null;
            this.AdminCustomerBtn.OnPressedState.IconRightImage = null;
            this.AdminCustomerBtn.Size = new System.Drawing.Size(230, 38);
            this.AdminCustomerBtn.TabIndex = 25;
            this.AdminCustomerBtn.TabStop = false;
            this.AdminCustomerBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCustomerBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCustomerBtn.TextMarginLeft = 0;
            this.AdminCustomerBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCustomerBtn.UseDefaultRadiusAndThickness = true;
            this.AdminCustomerBtn.Click += new System.EventHandler(this.AdminCustomerBtn_Click);
            // 
            // AdminFinancialBtn
            // 
            this.AdminFinancialBtn.AllowAnimations = true;
            this.AdminFinancialBtn.AllowMouseEffects = true;
            this.AdminFinancialBtn.AllowToggling = false;
            this.AdminFinancialBtn.AnimationSpeed = 200;
            this.AdminFinancialBtn.AutoGenerateColors = false;
            this.AdminFinancialBtn.AutoRoundBorders = false;
            this.AdminFinancialBtn.AutoSizeLeftIcon = true;
            this.AdminFinancialBtn.AutoSizeRightIcon = true;
            this.AdminFinancialBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminFinancialBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFinancialBtn.BackgroundImage")));
            this.AdminFinancialBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminFinancialBtn.ButtonText = "FINANCIAL";
            this.AdminFinancialBtn.ButtonTextMarginLeft = 0;
            this.AdminFinancialBtn.ColorContrastOnClick = 45;
            this.AdminFinancialBtn.ColorContrastOnHover = 45;
            this.AdminFinancialBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminFinancialBtn.CustomizableEdges = borderEdges5;
            this.AdminFinancialBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminFinancialBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminFinancialBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFinancialBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminFinancialBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminFinancialBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFinancialBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminFinancialBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminFinancialBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminFinancialBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminFinancialBtn.IconMarginLeft = 11;
            this.AdminFinancialBtn.IconPadding = 10;
            this.AdminFinancialBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminFinancialBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminFinancialBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminFinancialBtn.IconSize = 25;
            this.AdminFinancialBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.IdleBorderRadius = 1;
            this.AdminFinancialBtn.IdleBorderThickness = 1;
            this.AdminFinancialBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.IdleIconLeftImage = null;
            this.AdminFinancialBtn.IdleIconRightImage = null;
            this.AdminFinancialBtn.IndicateFocus = false;
            this.AdminFinancialBtn.Location = new System.Drawing.Point(0, 203);
            this.AdminFinancialBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminFinancialBtn.Name = "AdminFinancialBtn";
            this.AdminFinancialBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminFinancialBtn.OnDisabledState.BorderRadius = 1;
            this.AdminFinancialBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminFinancialBtn.OnDisabledState.BorderThickness = 1;
            this.AdminFinancialBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFinancialBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminFinancialBtn.OnDisabledState.IconLeftImage = null;
            this.AdminFinancialBtn.OnDisabledState.IconRightImage = null;
            this.AdminFinancialBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.onHoverState.BorderRadius = 1;
            this.AdminFinancialBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminFinancialBtn.onHoverState.BorderThickness = 1;
            this.AdminFinancialBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminFinancialBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminFinancialBtn.onHoverState.IconLeftImage = null;
            this.AdminFinancialBtn.onHoverState.IconRightImage = null;
            this.AdminFinancialBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.OnIdleState.BorderRadius = 1;
            this.AdminFinancialBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminFinancialBtn.OnIdleState.BorderThickness = 1;
            this.AdminFinancialBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminFinancialBtn.OnIdleState.IconLeftImage = null;
            this.AdminFinancialBtn.OnIdleState.IconRightImage = null;
            this.AdminFinancialBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminFinancialBtn.OnPressedState.BorderRadius = 1;
            this.AdminFinancialBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminFinancialBtn.OnPressedState.BorderThickness = 1;
            this.AdminFinancialBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminFinancialBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminFinancialBtn.OnPressedState.IconLeftImage = null;
            this.AdminFinancialBtn.OnPressedState.IconRightImage = null;
            this.AdminFinancialBtn.Size = new System.Drawing.Size(232, 38);
            this.AdminFinancialBtn.TabIndex = 24;
            this.AdminFinancialBtn.TabStop = false;
            this.AdminFinancialBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminFinancialBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminFinancialBtn.TextMarginLeft = 0;
            this.AdminFinancialBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminFinancialBtn.UseDefaultRadiusAndThickness = true;
            this.AdminFinancialBtn.Click += new System.EventHandler(this.AdminFinancialBtn_Click);
            // 
            // AdminEmployeeBtn
            // 
            this.AdminEmployeeBtn.AllowAnimations = true;
            this.AdminEmployeeBtn.AllowMouseEffects = true;
            this.AdminEmployeeBtn.AllowToggling = false;
            this.AdminEmployeeBtn.AnimationSpeed = 200;
            this.AdminEmployeeBtn.AutoGenerateColors = false;
            this.AdminEmployeeBtn.AutoRoundBorders = false;
            this.AdminEmployeeBtn.AutoSizeLeftIcon = true;
            this.AdminEmployeeBtn.AutoSizeRightIcon = true;
            this.AdminEmployeeBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminEmployeeBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminEmployeeBtn.BackgroundImage")));
            this.AdminEmployeeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminEmployeeBtn.ButtonText = "EMPLOYEE";
            this.AdminEmployeeBtn.ButtonTextMarginLeft = 0;
            this.AdminEmployeeBtn.ColorContrastOnClick = 45;
            this.AdminEmployeeBtn.ColorContrastOnHover = 45;
            this.AdminEmployeeBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.AdminEmployeeBtn.CustomizableEdges = borderEdges7;
            this.AdminEmployeeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminEmployeeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminEmployeeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminEmployeeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminEmployeeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminEmployeeBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminEmployeeBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminEmployeeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminEmployeeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminEmployeeBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminEmployeeBtn.IconMarginLeft = 11;
            this.AdminEmployeeBtn.IconPadding = 10;
            this.AdminEmployeeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminEmployeeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminEmployeeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminEmployeeBtn.IconSize = 25;
            this.AdminEmployeeBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.IdleBorderRadius = 1;
            this.AdminEmployeeBtn.IdleBorderThickness = 1;
            this.AdminEmployeeBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.IdleIconLeftImage = null;
            this.AdminEmployeeBtn.IdleIconRightImage = null;
            this.AdminEmployeeBtn.IndicateFocus = false;
            this.AdminEmployeeBtn.Location = new System.Drawing.Point(0, 165);
            this.AdminEmployeeBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminEmployeeBtn.Name = "AdminEmployeeBtn";
            this.AdminEmployeeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminEmployeeBtn.OnDisabledState.BorderRadius = 1;
            this.AdminEmployeeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminEmployeeBtn.OnDisabledState.BorderThickness = 1;
            this.AdminEmployeeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminEmployeeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminEmployeeBtn.OnDisabledState.IconLeftImage = null;
            this.AdminEmployeeBtn.OnDisabledState.IconRightImage = null;
            this.AdminEmployeeBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.onHoverState.BorderRadius = 1;
            this.AdminEmployeeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminEmployeeBtn.onHoverState.BorderThickness = 1;
            this.AdminEmployeeBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminEmployeeBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminEmployeeBtn.onHoverState.IconLeftImage = null;
            this.AdminEmployeeBtn.onHoverState.IconRightImage = null;
            this.AdminEmployeeBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.OnIdleState.BorderRadius = 1;
            this.AdminEmployeeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminEmployeeBtn.OnIdleState.BorderThickness = 1;
            this.AdminEmployeeBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminEmployeeBtn.OnIdleState.IconLeftImage = null;
            this.AdminEmployeeBtn.OnIdleState.IconRightImage = null;
            this.AdminEmployeeBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminEmployeeBtn.OnPressedState.BorderRadius = 1;
            this.AdminEmployeeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminEmployeeBtn.OnPressedState.BorderThickness = 1;
            this.AdminEmployeeBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminEmployeeBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminEmployeeBtn.OnPressedState.IconLeftImage = null;
            this.AdminEmployeeBtn.OnPressedState.IconRightImage = null;
            this.AdminEmployeeBtn.Size = new System.Drawing.Size(232, 38);
            this.AdminEmployeeBtn.TabIndex = 23;
            this.AdminEmployeeBtn.TabStop = false;
            this.AdminEmployeeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminEmployeeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminEmployeeBtn.TextMarginLeft = 0;
            this.AdminEmployeeBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminEmployeeBtn.UseDefaultRadiusAndThickness = true;
            this.AdminEmployeeBtn.Click += new System.EventHandler(this.AdminEmployeeBtn_Click);
            // 
            // AdminOrderBtn
            // 
            this.AdminOrderBtn.AllowAnimations = true;
            this.AdminOrderBtn.AllowMouseEffects = true;
            this.AdminOrderBtn.AllowToggling = false;
            this.AdminOrderBtn.AnimationSpeed = 200;
            this.AdminOrderBtn.AutoGenerateColors = false;
            this.AdminOrderBtn.AutoRoundBorders = false;
            this.AdminOrderBtn.AutoSizeLeftIcon = true;
            this.AdminOrderBtn.AutoSizeRightIcon = true;
            this.AdminOrderBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminOrderBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminOrderBtn.BackgroundImage")));
            this.AdminOrderBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminOrderBtn.ButtonText = "ORDER";
            this.AdminOrderBtn.ButtonTextMarginLeft = 0;
            this.AdminOrderBtn.ColorContrastOnClick = 45;
            this.AdminOrderBtn.ColorContrastOnHover = 45;
            this.AdminOrderBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.AdminOrderBtn.CustomizableEdges = borderEdges6;
            this.AdminOrderBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminOrderBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminOrderBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminOrderBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminOrderBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminOrderBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminOrderBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminOrderBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminOrderBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminOrderBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminOrderBtn.IconMarginLeft = 11;
            this.AdminOrderBtn.IconPadding = 10;
            this.AdminOrderBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminOrderBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminOrderBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminOrderBtn.IconSize = 25;
            this.AdminOrderBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.IdleBorderRadius = 1;
            this.AdminOrderBtn.IdleBorderThickness = 1;
            this.AdminOrderBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.IdleIconLeftImage = null;
            this.AdminOrderBtn.IdleIconRightImage = null;
            this.AdminOrderBtn.IndicateFocus = false;
            this.AdminOrderBtn.Location = new System.Drawing.Point(0, 127);
            this.AdminOrderBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminOrderBtn.Name = "AdminOrderBtn";
            this.AdminOrderBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminOrderBtn.OnDisabledState.BorderRadius = 1;
            this.AdminOrderBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminOrderBtn.OnDisabledState.BorderThickness = 1;
            this.AdminOrderBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminOrderBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminOrderBtn.OnDisabledState.IconLeftImage = null;
            this.AdminOrderBtn.OnDisabledState.IconRightImage = null;
            this.AdminOrderBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.onHoverState.BorderRadius = 1;
            this.AdminOrderBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminOrderBtn.onHoverState.BorderThickness = 1;
            this.AdminOrderBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminOrderBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminOrderBtn.onHoverState.IconLeftImage = null;
            this.AdminOrderBtn.onHoverState.IconRightImage = null;
            this.AdminOrderBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.OnIdleState.BorderRadius = 1;
            this.AdminOrderBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminOrderBtn.OnIdleState.BorderThickness = 1;
            this.AdminOrderBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminOrderBtn.OnIdleState.IconLeftImage = null;
            this.AdminOrderBtn.OnIdleState.IconRightImage = null;
            this.AdminOrderBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminOrderBtn.OnPressedState.BorderRadius = 1;
            this.AdminOrderBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminOrderBtn.OnPressedState.BorderThickness = 1;
            this.AdminOrderBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminOrderBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminOrderBtn.OnPressedState.IconLeftImage = null;
            this.AdminOrderBtn.OnPressedState.IconRightImage = null;
            this.AdminOrderBtn.Size = new System.Drawing.Size(232, 38);
            this.AdminOrderBtn.TabIndex = 22;
            this.AdminOrderBtn.TabStop = false;
            this.AdminOrderBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminOrderBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminOrderBtn.TextMarginLeft = 0;
            this.AdminOrderBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminOrderBtn.UseDefaultRadiusAndThickness = true;
            this.AdminOrderBtn.Click += new System.EventHandler(this.AdminOrderBtn_Click);
            // 
            // AdminMenuBtn
            // 
            this.AdminMenuBtn.AllowAnimations = true;
            this.AdminMenuBtn.AllowMouseEffects = true;
            this.AdminMenuBtn.AllowToggling = false;
            this.AdminMenuBtn.AnimationSpeed = 200;
            this.AdminMenuBtn.AutoGenerateColors = false;
            this.AdminMenuBtn.AutoRoundBorders = false;
            this.AdminMenuBtn.AutoSizeLeftIcon = true;
            this.AdminMenuBtn.AutoSizeRightIcon = true;
            this.AdminMenuBtn.BackColor = System.Drawing.Color.Transparent;
            this.AdminMenuBtn.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminMenuBtn.BackgroundImage")));
            this.AdminMenuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminMenuBtn.ButtonText = "MENU";
            this.AdminMenuBtn.ButtonTextMarginLeft = 0;
            this.AdminMenuBtn.ColorContrastOnClick = 45;
            this.AdminMenuBtn.ColorContrastOnHover = 45;
            this.AdminMenuBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminMenuBtn.CustomizableEdges = borderEdges4;
            this.AdminMenuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminMenuBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminMenuBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminMenuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminMenuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminMenuBtn.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminMenuBtn.ForeColor = System.Drawing.Color.Snow;
            this.AdminMenuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminMenuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminMenuBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminMenuBtn.IconMarginLeft = 11;
            this.AdminMenuBtn.IconPadding = 10;
            this.AdminMenuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminMenuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminMenuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminMenuBtn.IconSize = 25;
            this.AdminMenuBtn.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.IdleBorderRadius = 1;
            this.AdminMenuBtn.IdleBorderThickness = 1;
            this.AdminMenuBtn.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.IdleIconLeftImage = null;
            this.AdminMenuBtn.IdleIconRightImage = null;
            this.AdminMenuBtn.IndicateFocus = false;
            this.AdminMenuBtn.Location = new System.Drawing.Point(0, 89);
            this.AdminMenuBtn.Margin = new System.Windows.Forms.Padding(2);
            this.AdminMenuBtn.Name = "AdminMenuBtn";
            this.AdminMenuBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminMenuBtn.OnDisabledState.BorderRadius = 1;
            this.AdminMenuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminMenuBtn.OnDisabledState.BorderThickness = 1;
            this.AdminMenuBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminMenuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminMenuBtn.OnDisabledState.IconLeftImage = null;
            this.AdminMenuBtn.OnDisabledState.IconRightImage = null;
            this.AdminMenuBtn.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.onHoverState.BorderRadius = 1;
            this.AdminMenuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminMenuBtn.onHoverState.BorderThickness = 1;
            this.AdminMenuBtn.onHoverState.FillColor = System.Drawing.Color.Coral;
            this.AdminMenuBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminMenuBtn.onHoverState.IconLeftImage = null;
            this.AdminMenuBtn.onHoverState.IconRightImage = null;
            this.AdminMenuBtn.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.OnIdleState.BorderRadius = 1;
            this.AdminMenuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminMenuBtn.OnIdleState.BorderThickness = 1;
            this.AdminMenuBtn.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.OnIdleState.ForeColor = System.Drawing.Color.Snow;
            this.AdminMenuBtn.OnIdleState.IconLeftImage = null;
            this.AdminMenuBtn.OnIdleState.IconRightImage = null;
            this.AdminMenuBtn.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminMenuBtn.OnPressedState.BorderRadius = 1;
            this.AdminMenuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminMenuBtn.OnPressedState.BorderThickness = 1;
            this.AdminMenuBtn.OnPressedState.FillColor = System.Drawing.Color.Coral;
            this.AdminMenuBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.AdminMenuBtn.OnPressedState.IconLeftImage = null;
            this.AdminMenuBtn.OnPressedState.IconRightImage = null;
            this.AdminMenuBtn.Size = new System.Drawing.Size(232, 38);
            this.AdminMenuBtn.TabIndex = 21;
            this.AdminMenuBtn.TabStop = false;
            this.AdminMenuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminMenuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminMenuBtn.TextMarginLeft = 0;
            this.AdminMenuBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminMenuBtn.UseDefaultRadiusAndThickness = true;
            this.AdminMenuBtn.Click += new System.EventHandler(this.AdminMenuBtn_Click);
            // 
            // AdminMainPanel
            // 
            this.AdminMainPanel.BackgroundColor = System.Drawing.Color.Transparent;
            this.AdminMainPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminMainPanel.BackgroundImage")));
            this.AdminMainPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.AdminMainPanel.BorderColor = System.Drawing.Color.Transparent;
            this.AdminMainPanel.BorderRadius = 1;
            this.AdminMainPanel.BorderThickness = 1;
            this.AdminMainPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AdminMainPanel.Location = new System.Drawing.Point(232, 0);
            this.AdminMainPanel.Margin = new System.Windows.Forms.Padding(2);
            this.AdminMainPanel.Name = "AdminMainPanel";
            this.AdminMainPanel.ShowBorders = true;
            this.AdminMainPanel.Size = new System.Drawing.Size(706, 484);
            this.AdminMainPanel.TabIndex = 1;
            this.AdminMainPanel.Click += new System.EventHandler(this.AdminMainPanel_Click);
            // 
            // AdminFP
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(938, 484);
            this.Controls.Add(this.AdminMainPanel);
            this.Controls.Add(this.AdminPanelGrid);
            this.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "AdminFP";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.AdminFP_Load);
            this.AdminPanelGrid.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AdminUserImg)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel AdminPanelGrid;
        private Bunifu.UI.WinForms.BunifuPictureBox AdminUserImg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminReviewBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCustomerBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminFinancialBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminEmployeeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminOrderBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminMenuBtn;
        private Bunifu.UI.WinForms.BunifuPanel AdminMainPanel;
        private System.Windows.Forms.PictureBox pictureBox10;
    }
}

