namespace UI
{
    partial class AdminCat
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminCat));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminUpdateCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillCatStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCatName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllCat = new System.Windows.Forms.ListView();
            this.AdminShowAllCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillCatId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminUpdateCat
            // 
            this.AdminUpdateCat.AllowAnimations = true;
            this.AdminUpdateCat.AllowMouseEffects = true;
            this.AdminUpdateCat.AllowToggling = false;
            this.AdminUpdateCat.AnimationSpeed = 200;
            this.AdminUpdateCat.AutoGenerateColors = false;
            this.AdminUpdateCat.AutoRoundBorders = false;
            this.AdminUpdateCat.AutoSizeLeftIcon = true;
            this.AdminUpdateCat.AutoSizeRightIcon = true;
            this.AdminUpdateCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateCat.BackgroundImage")));
            this.AdminUpdateCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCat.ButtonText = "Update";
            this.AdminUpdateCat.ButtonTextMarginLeft = 0;
            this.AdminUpdateCat.ColorContrastOnClick = 45;
            this.AdminUpdateCat.ColorContrastOnHover = 45;
            this.AdminUpdateCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminUpdateCat.CustomizableEdges = borderEdges1;
            this.AdminUpdateCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateCat.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateCat.IconMarginLeft = 11;
            this.AdminUpdateCat.IconPadding = 10;
            this.AdminUpdateCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateCat.IconSize = 25;
            this.AdminUpdateCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.IdleBorderRadius = 37;
            this.AdminUpdateCat.IdleBorderThickness = 1;
            this.AdminUpdateCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.IdleIconLeftImage = null;
            this.AdminUpdateCat.IdleIconRightImage = null;
            this.AdminUpdateCat.IndicateFocus = false;
            this.AdminUpdateCat.Location = new System.Drawing.Point(716, 323);
            this.AdminUpdateCat.Name = "AdminUpdateCat";
            this.AdminUpdateCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateCat.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCat.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateCat.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateCat.OnDisabledState.IconRightImage = null;
            this.AdminUpdateCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.onHoverState.BorderRadius = 37;
            this.AdminUpdateCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCat.onHoverState.BorderThickness = 1;
            this.AdminUpdateCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateCat.onHoverState.IconLeftImage = null;
            this.AdminUpdateCat.onHoverState.IconRightImage = null;
            this.AdminUpdateCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.OnIdleState.BorderRadius = 37;
            this.AdminUpdateCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCat.OnIdleState.BorderThickness = 1;
            this.AdminUpdateCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCat.OnIdleState.IconLeftImage = null;
            this.AdminUpdateCat.OnIdleState.IconRightImage = null;
            this.AdminUpdateCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.OnPressedState.BorderRadius = 37;
            this.AdminUpdateCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCat.OnPressedState.BorderThickness = 1;
            this.AdminUpdateCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCat.OnPressedState.IconLeftImage = null;
            this.AdminUpdateCat.OnPressedState.IconRightImage = null;
            this.AdminUpdateCat.Size = new System.Drawing.Size(330, 36);
            this.AdminUpdateCat.TabIndex = 67;
            this.AdminUpdateCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateCat.TextMarginLeft = 0;
            this.AdminUpdateCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteCat
            // 
            this.AdminDeleteCat.AllowAnimations = true;
            this.AdminDeleteCat.AllowMouseEffects = true;
            this.AdminDeleteCat.AllowToggling = false;
            this.AdminDeleteCat.AnimationSpeed = 200;
            this.AdminDeleteCat.AutoGenerateColors = false;
            this.AdminDeleteCat.AutoRoundBorders = false;
            this.AdminDeleteCat.AutoSizeLeftIcon = true;
            this.AdminDeleteCat.AutoSizeRightIcon = true;
            this.AdminDeleteCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteCat.BackgroundImage")));
            this.AdminDeleteCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCat.ButtonText = "DELETE";
            this.AdminDeleteCat.ButtonTextMarginLeft = 0;
            this.AdminDeleteCat.ColorContrastOnClick = 45;
            this.AdminDeleteCat.ColorContrastOnHover = 45;
            this.AdminDeleteCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminDeleteCat.CustomizableEdges = borderEdges2;
            this.AdminDeleteCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteCat.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteCat.IconMarginLeft = 11;
            this.AdminDeleteCat.IconPadding = 10;
            this.AdminDeleteCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteCat.IconSize = 25;
            this.AdminDeleteCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.IdleBorderRadius = 37;
            this.AdminDeleteCat.IdleBorderThickness = 1;
            this.AdminDeleteCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.IdleIconLeftImage = null;
            this.AdminDeleteCat.IdleIconRightImage = null;
            this.AdminDeleteCat.IndicateFocus = false;
            this.AdminDeleteCat.Location = new System.Drawing.Point(886, 272);
            this.AdminDeleteCat.Name = "AdminDeleteCat";
            this.AdminDeleteCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteCat.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCat.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteCat.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteCat.OnDisabledState.IconRightImage = null;
            this.AdminDeleteCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.onHoverState.BorderRadius = 37;
            this.AdminDeleteCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCat.onHoverState.BorderThickness = 1;
            this.AdminDeleteCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteCat.onHoverState.IconLeftImage = null;
            this.AdminDeleteCat.onHoverState.IconRightImage = null;
            this.AdminDeleteCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.OnIdleState.BorderRadius = 37;
            this.AdminDeleteCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCat.OnIdleState.BorderThickness = 1;
            this.AdminDeleteCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCat.OnIdleState.IconLeftImage = null;
            this.AdminDeleteCat.OnIdleState.IconRightImage = null;
            this.AdminDeleteCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.OnPressedState.BorderRadius = 37;
            this.AdminDeleteCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCat.OnPressedState.BorderThickness = 1;
            this.AdminDeleteCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCat.OnPressedState.IconLeftImage = null;
            this.AdminDeleteCat.OnPressedState.IconRightImage = null;
            this.AdminDeleteCat.Size = new System.Drawing.Size(160, 36);
            this.AdminDeleteCat.TabIndex = 66;
            this.AdminDeleteCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteCat.TextMarginLeft = 0;
            this.AdminDeleteCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddCat
            // 
            this.AdminAddCat.AllowAnimations = true;
            this.AdminAddCat.AllowMouseEffects = true;
            this.AdminAddCat.AllowToggling = false;
            this.AdminAddCat.AnimationSpeed = 200;
            this.AdminAddCat.AutoGenerateColors = false;
            this.AdminAddCat.AutoRoundBorders = false;
            this.AdminAddCat.AutoSizeLeftIcon = true;
            this.AdminAddCat.AutoSizeRightIcon = true;
            this.AdminAddCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddCat.BackgroundImage")));
            this.AdminAddCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCat.ButtonText = "ADD";
            this.AdminAddCat.ButtonTextMarginLeft = 0;
            this.AdminAddCat.ColorContrastOnClick = 45;
            this.AdminAddCat.ColorContrastOnHover = 45;
            this.AdminAddCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminAddCat.CustomizableEdges = borderEdges3;
            this.AdminAddCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddCat.ForeColor = System.Drawing.Color.White;
            this.AdminAddCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddCat.IconMarginLeft = 11;
            this.AdminAddCat.IconPadding = 10;
            this.AdminAddCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddCat.IconSize = 25;
            this.AdminAddCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.IdleBorderRadius = 37;
            this.AdminAddCat.IdleBorderThickness = 1;
            this.AdminAddCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.IdleIconLeftImage = null;
            this.AdminAddCat.IdleIconRightImage = null;
            this.AdminAddCat.IndicateFocus = false;
            this.AdminAddCat.Location = new System.Drawing.Point(716, 272);
            this.AdminAddCat.Name = "AdminAddCat";
            this.AdminAddCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddCat.OnDisabledState.BorderRadius = 37;
            this.AdminAddCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCat.OnDisabledState.BorderThickness = 1;
            this.AdminAddCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddCat.OnDisabledState.IconLeftImage = null;
            this.AdminAddCat.OnDisabledState.IconRightImage = null;
            this.AdminAddCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.onHoverState.BorderRadius = 37;
            this.AdminAddCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCat.onHoverState.BorderThickness = 1;
            this.AdminAddCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddCat.onHoverState.IconLeftImage = null;
            this.AdminAddCat.onHoverState.IconRightImage = null;
            this.AdminAddCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.OnIdleState.BorderRadius = 37;
            this.AdminAddCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCat.OnIdleState.BorderThickness = 1;
            this.AdminAddCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddCat.OnIdleState.IconLeftImage = null;
            this.AdminAddCat.OnIdleState.IconRightImage = null;
            this.AdminAddCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.OnPressedState.BorderRadius = 37;
            this.AdminAddCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCat.OnPressedState.BorderThickness = 1;
            this.AdminAddCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddCat.OnPressedState.IconLeftImage = null;
            this.AdminAddCat.OnPressedState.IconRightImage = null;
            this.AdminAddCat.Size = new System.Drawing.Size(160, 36);
            this.AdminAddCat.TabIndex = 65;
            this.AdminAddCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddCat.TextMarginLeft = 0;
            this.AdminAddCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillCatStatus
            // 
            this.AdminFillCatStatus.AcceptsReturn = false;
            this.AdminFillCatStatus.AcceptsTab = false;
            this.AdminFillCatStatus.AnimationSpeed = 200;
            this.AdminFillCatStatus.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatStatus.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatStatus.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatStatus.BackgroundImage")));
            this.AdminFillCatStatus.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatStatus.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatStatus.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatStatus.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCatStatus.BorderRadius = 1;
            this.AdminFillCatStatus.BorderThickness = 1;
            this.AdminFillCatStatus.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatStatus.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCatStatus.DefaultText = "";
            this.AdminFillCatStatus.FillColor = System.Drawing.Color.White;
            this.AdminFillCatStatus.HideSelection = true;
            this.AdminFillCatStatus.IconLeft = null;
            this.AdminFillCatStatus.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.IconPadding = 10;
            this.AdminFillCatStatus.IconRight = null;
            this.AdminFillCatStatus.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatStatus.Lines = new string[0];
            this.AdminFillCatStatus.Location = new System.Drawing.Point(716, 215);
            this.AdminFillCatStatus.MaxLength = 32767;
            this.AdminFillCatStatus.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillCatStatus.Modified = false;
            this.AdminFillCatStatus.Multiline = false;
            this.AdminFillCatStatus.Name = "AdminFillCatStatus";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatStatus.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatStatus.OnIdleState = stateProperties4;
            this.AdminFillCatStatus.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillCatStatus.PasswordChar = '\0';
            this.AdminFillCatStatus.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatStatus.PlaceholderText = "Fill your Cat\'s Status";
            this.AdminFillCatStatus.ReadOnly = false;
            this.AdminFillCatStatus.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatStatus.SelectedText = "";
            this.AdminFillCatStatus.SelectionLength = 0;
            this.AdminFillCatStatus.SelectionStart = 0;
            this.AdminFillCatStatus.ShortcutsEnabled = true;
            this.AdminFillCatStatus.Size = new System.Drawing.Size(330, 37);
            this.AdminFillCatStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatStatus.TabIndex = 64;
            this.AdminFillCatStatus.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatStatus.TextMarginBottom = 0;
            this.AdminFillCatStatus.TextMarginLeft = 3;
            this.AdminFillCatStatus.TextMarginTop = 0;
            this.AdminFillCatStatus.TextPlaceholder = "Fill your Cat\'s Status";
            this.AdminFillCatStatus.UseSystemPasswordChar = false;
            this.AdminFillCatStatus.WordWrap = true;
            // 
            // AdminFillCatName
            // 
            this.AdminFillCatName.AcceptsReturn = false;
            this.AdminFillCatName.AcceptsTab = false;
            this.AdminFillCatName.AnimationSpeed = 200;
            this.AdminFillCatName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatName.BackgroundImage")));
            this.AdminFillCatName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCatName.BorderRadius = 1;
            this.AdminFillCatName.BorderThickness = 1;
            this.AdminFillCatName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCatName.DefaultText = "";
            this.AdminFillCatName.FillColor = System.Drawing.Color.White;
            this.AdminFillCatName.HideSelection = true;
            this.AdminFillCatName.IconLeft = null;
            this.AdminFillCatName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.IconPadding = 10;
            this.AdminFillCatName.IconRight = null;
            this.AdminFillCatName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatName.Lines = new string[0];
            this.AdminFillCatName.Location = new System.Drawing.Point(716, 159);
            this.AdminFillCatName.MaxLength = 32767;
            this.AdminFillCatName.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillCatName.Modified = false;
            this.AdminFillCatName.Multiline = false;
            this.AdminFillCatName.Name = "AdminFillCatName";
            stateProperties5.BorderColor = System.Drawing.Color.Transparent;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatName.OnIdleState = stateProperties8;
            this.AdminFillCatName.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillCatName.PasswordChar = '\0';
            this.AdminFillCatName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatName.PlaceholderText = "Fill your Cat\'s Name";
            this.AdminFillCatName.ReadOnly = false;
            this.AdminFillCatName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatName.SelectedText = "";
            this.AdminFillCatName.SelectionLength = 0;
            this.AdminFillCatName.SelectionStart = 0;
            this.AdminFillCatName.ShortcutsEnabled = true;
            this.AdminFillCatName.Size = new System.Drawing.Size(330, 37);
            this.AdminFillCatName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatName.TabIndex = 63;
            this.AdminFillCatName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatName.TextMarginBottom = 0;
            this.AdminFillCatName.TextMarginLeft = 3;
            this.AdminFillCatName.TextMarginTop = 0;
            this.AdminFillCatName.TextPlaceholder = "Fill your Cat\'s Name";
            this.AdminFillCatName.UseSystemPasswordChar = false;
            this.AdminFillCatName.WordWrap = true;
            // 
            // AdminViewAllCat
            // 
            this.AdminViewAllCat.HideSelection = false;
            this.AdminViewAllCat.Location = new System.Drawing.Point(22, 22);
            this.AdminViewAllCat.Margin = new System.Windows.Forms.Padding(2);
            this.AdminViewAllCat.Name = "AdminViewAllCat";
            this.AdminViewAllCat.Size = new System.Drawing.Size(672, 616);
            this.AdminViewAllCat.TabIndex = 62;
            this.AdminViewAllCat.UseCompatibleStateImageBehavior = false;
            // 
            // AdminShowAllCat
            // 
            this.AdminShowAllCat.AllowAnimations = true;
            this.AdminShowAllCat.AllowMouseEffects = true;
            this.AdminShowAllCat.AllowToggling = false;
            this.AdminShowAllCat.AnimationSpeed = 200;
            this.AdminShowAllCat.AutoGenerateColors = false;
            this.AdminShowAllCat.AutoRoundBorders = false;
            this.AdminShowAllCat.AutoSizeLeftIcon = true;
            this.AdminShowAllCat.AutoSizeRightIcon = true;
            this.AdminShowAllCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowAllCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminShowAllCat.BackgroundImage")));
            this.AdminShowAllCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCat.ButtonText = "VIEW ALL YOUR CAT";
            this.AdminShowAllCat.ButtonTextMarginLeft = 0;
            this.AdminShowAllCat.ColorContrastOnClick = 45;
            this.AdminShowAllCat.ColorContrastOnHover = 45;
            this.AdminShowAllCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminShowAllCat.CustomizableEdges = borderEdges4;
            this.AdminShowAllCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminShowAllCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminShowAllCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowAllCat.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminShowAllCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminShowAllCat.IconMarginLeft = 11;
            this.AdminShowAllCat.IconPadding = 10;
            this.AdminShowAllCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminShowAllCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminShowAllCat.IconSize = 25;
            this.AdminShowAllCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.IdleBorderRadius = 37;
            this.AdminShowAllCat.IdleBorderThickness = 1;
            this.AdminShowAllCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.IdleIconLeftImage = null;
            this.AdminShowAllCat.IdleIconRightImage = null;
            this.AdminShowAllCat.IndicateFocus = false;
            this.AdminShowAllCat.Location = new System.Drawing.Point(22, 647);
            this.AdminShowAllCat.Name = "AdminShowAllCat";
            this.AdminShowAllCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllCat.OnDisabledState.BorderRadius = 37;
            this.AdminShowAllCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCat.OnDisabledState.BorderThickness = 1;
            this.AdminShowAllCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllCat.OnDisabledState.IconLeftImage = null;
            this.AdminShowAllCat.OnDisabledState.IconRightImage = null;
            this.AdminShowAllCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.onHoverState.BorderRadius = 37;
            this.AdminShowAllCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCat.onHoverState.BorderThickness = 1;
            this.AdminShowAllCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminShowAllCat.onHoverState.IconLeftImage = null;
            this.AdminShowAllCat.onHoverState.IconRightImage = null;
            this.AdminShowAllCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.OnIdleState.BorderRadius = 37;
            this.AdminShowAllCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCat.OnIdleState.BorderThickness = 1;
            this.AdminShowAllCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCat.OnIdleState.IconLeftImage = null;
            this.AdminShowAllCat.OnIdleState.IconRightImage = null;
            this.AdminShowAllCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.OnPressedState.BorderRadius = 37;
            this.AdminShowAllCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCat.OnPressedState.BorderThickness = 1;
            this.AdminShowAllCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCat.OnPressedState.IconLeftImage = null;
            this.AdminShowAllCat.OnPressedState.IconRightImage = null;
            this.AdminShowAllCat.Size = new System.Drawing.Size(214, 36);
            this.AdminShowAllCat.TabIndex = 61;
            this.AdminShowAllCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminShowAllCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminShowAllCat.TextMarginLeft = 0;
            this.AdminShowAllCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminShowAllCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillCatId
            // 
            this.AdminFillCatId.AcceptsReturn = false;
            this.AdminFillCatId.AcceptsTab = false;
            this.AdminFillCatId.AnimationSpeed = 200;
            this.AdminFillCatId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCatId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCatId.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCatId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCatId.BackgroundImage")));
            this.AdminFillCatId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCatId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCatId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCatId.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCatId.BorderRadius = 1;
            this.AdminFillCatId.BorderThickness = 1;
            this.AdminFillCatId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCatId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatId.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCatId.DefaultText = "";
            this.AdminFillCatId.FillColor = System.Drawing.Color.White;
            this.AdminFillCatId.HideSelection = true;
            this.AdminFillCatId.IconLeft = null;
            this.AdminFillCatId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatId.IconPadding = 10;
            this.AdminFillCatId.IconRight = null;
            this.AdminFillCatId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCatId.Lines = new string[0];
            this.AdminFillCatId.Location = new System.Drawing.Point(716, 39);
            this.AdminFillCatId.MaxLength = 32767;
            this.AdminFillCatId.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillCatId.Modified = false;
            this.AdminFillCatId.Multiline = false;
            this.AdminFillCatId.Name = "AdminFillCatId";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatId.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCatId.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatId.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCatId.OnIdleState = stateProperties12;
            this.AdminFillCatId.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillCatId.PasswordChar = '\0';
            this.AdminFillCatId.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCatId.PlaceholderText = "Fill Cat\'s Id";
            this.AdminFillCatId.ReadOnly = false;
            this.AdminFillCatId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCatId.SelectedText = "";
            this.AdminFillCatId.SelectionLength = 0;
            this.AdminFillCatId.SelectionStart = 0;
            this.AdminFillCatId.ShortcutsEnabled = true;
            this.AdminFillCatId.Size = new System.Drawing.Size(330, 37);
            this.AdminFillCatId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCatId.TabIndex = 60;
            this.AdminFillCatId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCatId.TextMarginBottom = 0;
            this.AdminFillCatId.TextMarginLeft = 3;
            this.AdminFillCatId.TextMarginTop = 0;
            this.AdminFillCatId.TextPlaceholder = "Fill Cat\'s Id";
            this.AdminFillCatId.UseSystemPasswordChar = false;
            this.AdminFillCatId.WordWrap = true;
            // 
            // AdminCheckCat
            // 
            this.AdminCheckCat.AllowAnimations = true;
            this.AdminCheckCat.AllowMouseEffects = true;
            this.AdminCheckCat.AllowToggling = false;
            this.AdminCheckCat.AnimationSpeed = 200;
            this.AdminCheckCat.AutoGenerateColors = false;
            this.AdminCheckCat.AutoRoundBorders = false;
            this.AdminCheckCat.AutoSizeLeftIcon = true;
            this.AdminCheckCat.AutoSizeRightIcon = true;
            this.AdminCheckCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckCat.BackgroundImage")));
            this.AdminCheckCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.ButtonText = "CHECK";
            this.AdminCheckCat.ButtonTextMarginLeft = 0;
            this.AdminCheckCat.ColorContrastOnClick = 45;
            this.AdminCheckCat.ColorContrastOnHover = 45;
            this.AdminCheckCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminCheckCat.CustomizableEdges = borderEdges5;
            this.AdminCheckCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckCat.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckCat.IconMarginLeft = 11;
            this.AdminCheckCat.IconPadding = 10;
            this.AdminCheckCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckCat.IconSize = 25;
            this.AdminCheckCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.IdleBorderRadius = 37;
            this.AdminCheckCat.IdleBorderThickness = 1;
            this.AdminCheckCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.IdleIconLeftImage = null;
            this.AdminCheckCat.IdleIconRightImage = null;
            this.AdminCheckCat.IndicateFocus = false;
            this.AdminCheckCat.Location = new System.Drawing.Point(716, 96);
            this.AdminCheckCat.Name = "AdminCheckCat";
            this.AdminCheckCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCat.OnDisabledState.BorderRadius = 37;
            this.AdminCheckCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnDisabledState.BorderThickness = 1;
            this.AdminCheckCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCat.OnDisabledState.IconLeftImage = null;
            this.AdminCheckCat.OnDisabledState.IconRightImage = null;
            this.AdminCheckCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.onHoverState.BorderRadius = 37;
            this.AdminCheckCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.onHoverState.BorderThickness = 1;
            this.AdminCheckCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckCat.onHoverState.IconLeftImage = null;
            this.AdminCheckCat.onHoverState.IconRightImage = null;
            this.AdminCheckCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnIdleState.BorderRadius = 37;
            this.AdminCheckCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnIdleState.BorderThickness = 1;
            this.AdminCheckCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.OnIdleState.IconLeftImage = null;
            this.AdminCheckCat.OnIdleState.IconRightImage = null;
            this.AdminCheckCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnPressedState.BorderRadius = 37;
            this.AdminCheckCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCat.OnPressedState.BorderThickness = 1;
            this.AdminCheckCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCat.OnPressedState.IconLeftImage = null;
            this.AdminCheckCat.OnPressedState.IconRightImage = null;
            this.AdminCheckCat.Size = new System.Drawing.Size(330, 36);
            this.AdminCheckCat.TabIndex = 59;
            this.AdminCheckCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckCat.TextMarginLeft = 0;
            this.AdminCheckCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminCat
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.Controls.Add(this.AdminUpdateCat);
            this.Controls.Add(this.AdminDeleteCat);
            this.Controls.Add(this.AdminAddCat);
            this.Controls.Add(this.AdminFillCatStatus);
            this.Controls.Add(this.AdminFillCatName);
            this.Controls.Add(this.AdminViewAllCat);
            this.Controls.Add(this.AdminShowAllCat);
            this.Controls.Add(this.AdminFillCatId);
            this.Controls.Add(this.AdminCheckCat);
            this.Name = "AdminCat";
            this.Size = new System.Drawing.Size(1069, 705);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddCat;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatStatus;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatName;
        private System.Windows.Forms.ListView AdminViewAllCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminShowAllCat;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCatId;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckCat;
    }
}
