namespace UI
{
    partial class AdminAdjust
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminAdjust));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminAdjustCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAdjustEmployee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAdjustCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAdjustTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAdjustDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAdjustProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminAdjustCustomer
            // 
            this.AdminAdjustCustomer.AllowAnimations = true;
            this.AdminAdjustCustomer.AllowMouseEffects = true;
            this.AdminAdjustCustomer.AllowToggling = false;
            this.AdminAdjustCustomer.AnimationSpeed = 200;
            this.AdminAdjustCustomer.AutoGenerateColors = false;
            this.AdminAdjustCustomer.AutoRoundBorders = false;
            this.AdminAdjustCustomer.AutoSizeLeftIcon = true;
            this.AdminAdjustCustomer.AutoSizeRightIcon = true;
            this.AdminAdjustCustomer.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustCustomer.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustCustomer.BackgroundImage")));
            this.AdminAdjustCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCustomer.ButtonText = "CUSTOMER";
            this.AdminAdjustCustomer.ButtonTextMarginLeft = 0;
            this.AdminAdjustCustomer.ColorContrastOnClick = 45;
            this.AdminAdjustCustomer.ColorContrastOnHover = 45;
            this.AdminAdjustCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.AdminAdjustCustomer.CustomizableEdges = borderEdges6;
            this.AdminAdjustCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustCustomer.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustCustomer.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustCustomer.IconMarginLeft = 11;
            this.AdminAdjustCustomer.IconPadding = 10;
            this.AdminAdjustCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustCustomer.IconSize = 25;
            this.AdminAdjustCustomer.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.IdleBorderRadius = 37;
            this.AdminAdjustCustomer.IdleBorderThickness = 1;
            this.AdminAdjustCustomer.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.IdleIconLeftImage = null;
            this.AdminAdjustCustomer.IdleIconRightImage = null;
            this.AdminAdjustCustomer.IndicateFocus = false;
            this.AdminAdjustCustomer.Location = new System.Drawing.Point(82, 67);
            this.AdminAdjustCustomer.Name = "AdminAdjustCustomer";
            this.AdminAdjustCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustCustomer.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCustomer.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustCustomer.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustCustomer.OnDisabledState.IconRightImage = null;
            this.AdminAdjustCustomer.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.onHoverState.BorderRadius = 37;
            this.AdminAdjustCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCustomer.onHoverState.BorderThickness = 1;
            this.AdminAdjustCustomer.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustCustomer.onHoverState.IconLeftImage = null;
            this.AdminAdjustCustomer.onHoverState.IconRightImage = null;
            this.AdminAdjustCustomer.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.OnIdleState.BorderRadius = 37;
            this.AdminAdjustCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCustomer.OnIdleState.BorderThickness = 1;
            this.AdminAdjustCustomer.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCustomer.OnIdleState.IconLeftImage = null;
            this.AdminAdjustCustomer.OnIdleState.IconRightImage = null;
            this.AdminAdjustCustomer.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.OnPressedState.BorderRadius = 37;
            this.AdminAdjustCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCustomer.OnPressedState.BorderThickness = 1;
            this.AdminAdjustCustomer.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCustomer.OnPressedState.IconLeftImage = null;
            this.AdminAdjustCustomer.OnPressedState.IconRightImage = null;
            this.AdminAdjustCustomer.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustCustomer.TabIndex = 66;
            this.AdminAdjustCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustCustomer.TextMarginLeft = 0;
            this.AdminAdjustCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustCustomer.UseDefaultRadiusAndThickness = true;
            this.AdminAdjustCustomer.Click += new System.EventHandler(this.AdminAdjustCustomer_Click);
            // 
            // AdminAdjustEmployee
            // 
            this.AdminAdjustEmployee.AllowAnimations = true;
            this.AdminAdjustEmployee.AllowMouseEffects = true;
            this.AdminAdjustEmployee.AllowToggling = false;
            this.AdminAdjustEmployee.AnimationSpeed = 200;
            this.AdminAdjustEmployee.AutoGenerateColors = false;
            this.AdminAdjustEmployee.AutoRoundBorders = false;
            this.AdminAdjustEmployee.AutoSizeLeftIcon = true;
            this.AdminAdjustEmployee.AutoSizeRightIcon = true;
            this.AdminAdjustEmployee.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustEmployee.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustEmployee.BackgroundImage")));
            this.AdminAdjustEmployee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustEmployee.ButtonText = "EMPLOYEE";
            this.AdminAdjustEmployee.ButtonTextMarginLeft = 0;
            this.AdminAdjustEmployee.ColorContrastOnClick = 45;
            this.AdminAdjustEmployee.ColorContrastOnHover = 45;
            this.AdminAdjustEmployee.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminAdjustEmployee.CustomizableEdges = borderEdges5;
            this.AdminAdjustEmployee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustEmployee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustEmployee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustEmployee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustEmployee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustEmployee.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustEmployee.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustEmployee.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustEmployee.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustEmployee.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustEmployee.IconMarginLeft = 11;
            this.AdminAdjustEmployee.IconPadding = 10;
            this.AdminAdjustEmployee.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustEmployee.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustEmployee.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustEmployee.IconSize = 25;
            this.AdminAdjustEmployee.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.IdleBorderRadius = 37;
            this.AdminAdjustEmployee.IdleBorderThickness = 1;
            this.AdminAdjustEmployee.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.IdleIconLeftImage = null;
            this.AdminAdjustEmployee.IdleIconRightImage = null;
            this.AdminAdjustEmployee.IndicateFocus = false;
            this.AdminAdjustEmployee.Location = new System.Drawing.Point(302, 67);
            this.AdminAdjustEmployee.Name = "AdminAdjustEmployee";
            this.AdminAdjustEmployee.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustEmployee.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustEmployee.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustEmployee.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustEmployee.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustEmployee.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustEmployee.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustEmployee.OnDisabledState.IconRightImage = null;
            this.AdminAdjustEmployee.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.onHoverState.BorderRadius = 37;
            this.AdminAdjustEmployee.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustEmployee.onHoverState.BorderThickness = 1;
            this.AdminAdjustEmployee.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustEmployee.onHoverState.IconLeftImage = null;
            this.AdminAdjustEmployee.onHoverState.IconRightImage = null;
            this.AdminAdjustEmployee.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.OnIdleState.BorderRadius = 37;
            this.AdminAdjustEmployee.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustEmployee.OnIdleState.BorderThickness = 1;
            this.AdminAdjustEmployee.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustEmployee.OnIdleState.IconLeftImage = null;
            this.AdminAdjustEmployee.OnIdleState.IconRightImage = null;
            this.AdminAdjustEmployee.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.OnPressedState.BorderRadius = 37;
            this.AdminAdjustEmployee.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustEmployee.OnPressedState.BorderThickness = 1;
            this.AdminAdjustEmployee.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustEmployee.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustEmployee.OnPressedState.IconLeftImage = null;
            this.AdminAdjustEmployee.OnPressedState.IconRightImage = null;
            this.AdminAdjustEmployee.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustEmployee.TabIndex = 67;
            this.AdminAdjustEmployee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustEmployee.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustEmployee.TextMarginLeft = 0;
            this.AdminAdjustEmployee.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustEmployee.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAdjustCat
            // 
            this.AdminAdjustCat.AllowAnimations = true;
            this.AdminAdjustCat.AllowMouseEffects = true;
            this.AdminAdjustCat.AllowToggling = false;
            this.AdminAdjustCat.AnimationSpeed = 200;
            this.AdminAdjustCat.AutoGenerateColors = false;
            this.AdminAdjustCat.AutoRoundBorders = false;
            this.AdminAdjustCat.AutoSizeLeftIcon = true;
            this.AdminAdjustCat.AutoSizeRightIcon = true;
            this.AdminAdjustCat.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustCat.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustCat.BackgroundImage")));
            this.AdminAdjustCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCat.ButtonText = "CAT";
            this.AdminAdjustCat.ButtonTextMarginLeft = 0;
            this.AdminAdjustCat.ColorContrastOnClick = 45;
            this.AdminAdjustCat.ColorContrastOnHover = 45;
            this.AdminAdjustCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminAdjustCat.CustomizableEdges = borderEdges4;
            this.AdminAdjustCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustCat.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustCat.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustCat.IconMarginLeft = 11;
            this.AdminAdjustCat.IconPadding = 10;
            this.AdminAdjustCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustCat.IconSize = 25;
            this.AdminAdjustCat.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.IdleBorderRadius = 37;
            this.AdminAdjustCat.IdleBorderThickness = 1;
            this.AdminAdjustCat.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.IdleIconLeftImage = null;
            this.AdminAdjustCat.IdleIconRightImage = null;
            this.AdminAdjustCat.IndicateFocus = false;
            this.AdminAdjustCat.Location = new System.Drawing.Point(529, 67);
            this.AdminAdjustCat.Name = "AdminAdjustCat";
            this.AdminAdjustCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustCat.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCat.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustCat.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustCat.OnDisabledState.IconRightImage = null;
            this.AdminAdjustCat.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.onHoverState.BorderRadius = 37;
            this.AdminAdjustCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCat.onHoverState.BorderThickness = 1;
            this.AdminAdjustCat.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustCat.onHoverState.IconLeftImage = null;
            this.AdminAdjustCat.onHoverState.IconRightImage = null;
            this.AdminAdjustCat.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.OnIdleState.BorderRadius = 37;
            this.AdminAdjustCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCat.OnIdleState.BorderThickness = 1;
            this.AdminAdjustCat.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCat.OnIdleState.IconLeftImage = null;
            this.AdminAdjustCat.OnIdleState.IconRightImage = null;
            this.AdminAdjustCat.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.OnPressedState.BorderRadius = 37;
            this.AdminAdjustCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustCat.OnPressedState.BorderThickness = 1;
            this.AdminAdjustCat.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustCat.OnPressedState.IconLeftImage = null;
            this.AdminAdjustCat.OnPressedState.IconRightImage = null;
            this.AdminAdjustCat.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustCat.TabIndex = 68;
            this.AdminAdjustCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustCat.TextMarginLeft = 0;
            this.AdminAdjustCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustCat.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAdjustTable
            // 
            this.AdminAdjustTable.AllowAnimations = true;
            this.AdminAdjustTable.AllowMouseEffects = true;
            this.AdminAdjustTable.AllowToggling = false;
            this.AdminAdjustTable.AnimationSpeed = 200;
            this.AdminAdjustTable.AutoGenerateColors = false;
            this.AdminAdjustTable.AutoRoundBorders = false;
            this.AdminAdjustTable.AutoSizeLeftIcon = true;
            this.AdminAdjustTable.AutoSizeRightIcon = true;
            this.AdminAdjustTable.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustTable.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustTable.BackgroundImage")));
            this.AdminAdjustTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustTable.ButtonText = "TABLE";
            this.AdminAdjustTable.ButtonTextMarginLeft = 0;
            this.AdminAdjustTable.ColorContrastOnClick = 45;
            this.AdminAdjustTable.ColorContrastOnHover = 45;
            this.AdminAdjustTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminAdjustTable.CustomizableEdges = borderEdges1;
            this.AdminAdjustTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustTable.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustTable.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustTable.IconMarginLeft = 11;
            this.AdminAdjustTable.IconPadding = 10;
            this.AdminAdjustTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustTable.IconSize = 25;
            this.AdminAdjustTable.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.IdleBorderRadius = 37;
            this.AdminAdjustTable.IdleBorderThickness = 1;
            this.AdminAdjustTable.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.IdleIconLeftImage = null;
            this.AdminAdjustTable.IdleIconRightImage = null;
            this.AdminAdjustTable.IndicateFocus = false;
            this.AdminAdjustTable.Location = new System.Drawing.Point(82, 251);
            this.AdminAdjustTable.Name = "AdminAdjustTable";
            this.AdminAdjustTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustTable.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustTable.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustTable.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustTable.OnDisabledState.IconRightImage = null;
            this.AdminAdjustTable.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.onHoverState.BorderRadius = 37;
            this.AdminAdjustTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustTable.onHoverState.BorderThickness = 1;
            this.AdminAdjustTable.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustTable.onHoverState.IconLeftImage = null;
            this.AdminAdjustTable.onHoverState.IconRightImage = null;
            this.AdminAdjustTable.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.OnIdleState.BorderRadius = 37;
            this.AdminAdjustTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustTable.OnIdleState.BorderThickness = 1;
            this.AdminAdjustTable.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustTable.OnIdleState.IconLeftImage = null;
            this.AdminAdjustTable.OnIdleState.IconRightImage = null;
            this.AdminAdjustTable.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.OnPressedState.BorderRadius = 37;
            this.AdminAdjustTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustTable.OnPressedState.BorderThickness = 1;
            this.AdminAdjustTable.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustTable.OnPressedState.IconLeftImage = null;
            this.AdminAdjustTable.OnPressedState.IconRightImage = null;
            this.AdminAdjustTable.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustTable.TabIndex = 71;
            this.AdminAdjustTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustTable.TextMarginLeft = 0;
            this.AdminAdjustTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustTable.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAdjustDrink
            // 
            this.AdminAdjustDrink.AllowAnimations = true;
            this.AdminAdjustDrink.AllowMouseEffects = true;
            this.AdminAdjustDrink.AllowToggling = false;
            this.AdminAdjustDrink.AnimationSpeed = 200;
            this.AdminAdjustDrink.AutoGenerateColors = false;
            this.AdminAdjustDrink.AutoRoundBorders = false;
            this.AdminAdjustDrink.AutoSizeLeftIcon = true;
            this.AdminAdjustDrink.AutoSizeRightIcon = true;
            this.AdminAdjustDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustDrink.BackgroundImage")));
            this.AdminAdjustDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustDrink.ButtonText = "DRINK";
            this.AdminAdjustDrink.ButtonTextMarginLeft = 0;
            this.AdminAdjustDrink.ColorContrastOnClick = 45;
            this.AdminAdjustDrink.ColorContrastOnHover = 45;
            this.AdminAdjustDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminAdjustDrink.CustomizableEdges = borderEdges2;
            this.AdminAdjustDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustDrink.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustDrink.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustDrink.IconMarginLeft = 11;
            this.AdminAdjustDrink.IconPadding = 10;
            this.AdminAdjustDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustDrink.IconSize = 25;
            this.AdminAdjustDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.IdleBorderRadius = 37;
            this.AdminAdjustDrink.IdleBorderThickness = 1;
            this.AdminAdjustDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.IdleIconLeftImage = null;
            this.AdminAdjustDrink.IdleIconRightImage = null;
            this.AdminAdjustDrink.IndicateFocus = false;
            this.AdminAdjustDrink.Location = new System.Drawing.Point(302, 251);
            this.AdminAdjustDrink.Name = "AdminAdjustDrink";
            this.AdminAdjustDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustDrink.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustDrink.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustDrink.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustDrink.OnDisabledState.IconRightImage = null;
            this.AdminAdjustDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.onHoverState.BorderRadius = 37;
            this.AdminAdjustDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustDrink.onHoverState.BorderThickness = 1;
            this.AdminAdjustDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustDrink.onHoverState.IconLeftImage = null;
            this.AdminAdjustDrink.onHoverState.IconRightImage = null;
            this.AdminAdjustDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.OnIdleState.BorderRadius = 37;
            this.AdminAdjustDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustDrink.OnIdleState.BorderThickness = 1;
            this.AdminAdjustDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustDrink.OnIdleState.IconLeftImage = null;
            this.AdminAdjustDrink.OnIdleState.IconRightImage = null;
            this.AdminAdjustDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.OnPressedState.BorderRadius = 37;
            this.AdminAdjustDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustDrink.OnPressedState.BorderThickness = 1;
            this.AdminAdjustDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustDrink.OnPressedState.IconLeftImage = null;
            this.AdminAdjustDrink.OnPressedState.IconRightImage = null;
            this.AdminAdjustDrink.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustDrink.TabIndex = 70;
            this.AdminAdjustDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustDrink.TextMarginLeft = 0;
            this.AdminAdjustDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustDrink.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAdjustProduct
            // 
            this.AdminAdjustProduct.AllowAnimations = true;
            this.AdminAdjustProduct.AllowMouseEffects = true;
            this.AdminAdjustProduct.AllowToggling = false;
            this.AdminAdjustProduct.AnimationSpeed = 200;
            this.AdminAdjustProduct.AutoGenerateColors = false;
            this.AdminAdjustProduct.AutoRoundBorders = false;
            this.AdminAdjustProduct.AutoSizeLeftIcon = true;
            this.AdminAdjustProduct.AutoSizeRightIcon = true;
            this.AdminAdjustProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminAdjustProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAdjustProduct.BackgroundImage")));
            this.AdminAdjustProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustProduct.ButtonText = "PRODUCT";
            this.AdminAdjustProduct.ButtonTextMarginLeft = 0;
            this.AdminAdjustProduct.ColorContrastOnClick = 45;
            this.AdminAdjustProduct.ColorContrastOnHover = 45;
            this.AdminAdjustProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminAdjustProduct.CustomizableEdges = borderEdges3;
            this.AdminAdjustProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAdjustProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAdjustProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAdjustProduct.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAdjustProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAdjustProduct.IconMarginLeft = 11;
            this.AdminAdjustProduct.IconPadding = 10;
            this.AdminAdjustProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAdjustProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAdjustProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAdjustProduct.IconSize = 25;
            this.AdminAdjustProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.IdleBorderRadius = 37;
            this.AdminAdjustProduct.IdleBorderThickness = 1;
            this.AdminAdjustProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.IdleIconLeftImage = null;
            this.AdminAdjustProduct.IdleIconRightImage = null;
            this.AdminAdjustProduct.IndicateFocus = false;
            this.AdminAdjustProduct.Location = new System.Drawing.Point(529, 251);
            this.AdminAdjustProduct.Name = "AdminAdjustProduct";
            this.AdminAdjustProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAdjustProduct.OnDisabledState.BorderRadius = 37;
            this.AdminAdjustProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustProduct.OnDisabledState.BorderThickness = 1;
            this.AdminAdjustProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAdjustProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAdjustProduct.OnDisabledState.IconLeftImage = null;
            this.AdminAdjustProduct.OnDisabledState.IconRightImage = null;
            this.AdminAdjustProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.onHoverState.BorderRadius = 37;
            this.AdminAdjustProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustProduct.onHoverState.BorderThickness = 1;
            this.AdminAdjustProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAdjustProduct.onHoverState.IconLeftImage = null;
            this.AdminAdjustProduct.onHoverState.IconRightImage = null;
            this.AdminAdjustProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.OnIdleState.BorderRadius = 37;
            this.AdminAdjustProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustProduct.OnIdleState.BorderThickness = 1;
            this.AdminAdjustProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustProduct.OnIdleState.IconLeftImage = null;
            this.AdminAdjustProduct.OnIdleState.IconRightImage = null;
            this.AdminAdjustProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.OnPressedState.BorderRadius = 37;
            this.AdminAdjustProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAdjustProduct.OnPressedState.BorderThickness = 1;
            this.AdminAdjustProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAdjustProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAdjustProduct.OnPressedState.IconLeftImage = null;
            this.AdminAdjustProduct.OnPressedState.IconRightImage = null;
            this.AdminAdjustProduct.Size = new System.Drawing.Size(150, 53);
            this.AdminAdjustProduct.TabIndex = 69;
            this.AdminAdjustProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAdjustProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAdjustProduct.TextMarginLeft = 0;
            this.AdminAdjustProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAdjustProduct.UseDefaultRadiusAndThickness = true;
            this.AdminAdjustProduct.Click += new System.EventHandler(this.AdminAdjustProduct_Click);
            // 
            // AdminAdjust
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.AdminAdjustTable);
            this.Controls.Add(this.AdminAdjustDrink);
            this.Controls.Add(this.AdminAdjustProduct);
            this.Controls.Add(this.AdminAdjustCat);
            this.Controls.Add(this.AdminAdjustEmployee);
            this.Controls.Add(this.AdminAdjustCustomer);
            this.Name = "AdminAdjust";
            this.Size = new System.Drawing.Size(723, 573);
            this.Load += new System.EventHandler(this.AdminAdjust_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustTable;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustEmployee;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAdjustCustomer;
    }
}
