namespace UI
{
    partial class AdminDrink
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminDrink));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminUpdateDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillDrinkPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminViewAllYourDrinks = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.AdminFillDrinkSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkAvailable = new Bunifu.UI.WinForms.BunifuDropdown();
            this.btnImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminUpdateDrink
            // 
            this.AdminUpdateDrink.AllowAnimations = true;
            this.AdminUpdateDrink.AllowMouseEffects = true;
            this.AdminUpdateDrink.AllowToggling = false;
            this.AdminUpdateDrink.AnimationSpeed = 200;
            this.AdminUpdateDrink.AutoGenerateColors = false;
            this.AdminUpdateDrink.AutoRoundBorders = false;
            this.AdminUpdateDrink.AutoSizeLeftIcon = true;
            this.AdminUpdateDrink.AutoSizeRightIcon = true;
            this.AdminUpdateDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateDrink.BackgroundImage")));
            this.AdminUpdateDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.ButtonText = "UPDATE";
            this.AdminUpdateDrink.ButtonTextMarginLeft = 0;
            this.AdminUpdateDrink.ColorContrastOnClick = 45;
            this.AdminUpdateDrink.ColorContrastOnHover = 45;
            this.AdminUpdateDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminUpdateDrink.CustomizableEdges = borderEdges2;
            this.AdminUpdateDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateDrink.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.AdminUpdateDrink.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateDrink.IconMarginLeft = 11;
            this.AdminUpdateDrink.IconPadding = 10;
            this.AdminUpdateDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateDrink.IconSize = 25;
            this.AdminUpdateDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleBorderRadius = 45;
            this.AdminUpdateDrink.IdleBorderThickness = 1;
            this.AdminUpdateDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.IdleIconLeftImage = null;
            this.AdminUpdateDrink.IdleIconRightImage = null;
            this.AdminUpdateDrink.IndicateFocus = false;
            this.AdminUpdateDrink.Location = new System.Drawing.Point(459, 409);
            this.AdminUpdateDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminUpdateDrink.Name = "AdminUpdateDrink";
            this.AdminUpdateDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateDrink.OnDisabledState.BorderRadius = 45;
            this.AdminUpdateDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateDrink.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateDrink.OnDisabledState.IconRightImage = null;
            this.AdminUpdateDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.BorderRadius = 45;
            this.AdminUpdateDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.onHoverState.BorderThickness = 1;
            this.AdminUpdateDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateDrink.onHoverState.IconLeftImage = null;
            this.AdminUpdateDrink.onHoverState.IconRightImage = null;
            this.AdminUpdateDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.BorderRadius = 45;
            this.AdminUpdateDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnIdleState.BorderThickness = 1;
            this.AdminUpdateDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnIdleState.IconLeftImage = null;
            this.AdminUpdateDrink.OnIdleState.IconRightImage = null;
            this.AdminUpdateDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.BorderRadius = 45;
            this.AdminUpdateDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateDrink.OnPressedState.BorderThickness = 1;
            this.AdminUpdateDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateDrink.OnPressedState.IconLeftImage = null;
            this.AdminUpdateDrink.OnPressedState.IconRightImage = null;
            this.AdminUpdateDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminUpdateDrink.TabIndex = 58;
            this.AdminUpdateDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateDrink.TextMarginLeft = 0;
            this.AdminUpdateDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateDrink.UseDefaultRadiusAndThickness = true;
            this.AdminUpdateDrink.Click += new System.EventHandler(this.AdminUpdateDrink_Click);
            // 
            // AdminDeleteDrink
            // 
            this.AdminDeleteDrink.AllowAnimations = true;
            this.AdminDeleteDrink.AllowMouseEffects = true;
            this.AdminDeleteDrink.AllowToggling = false;
            this.AdminDeleteDrink.AnimationSpeed = 200;
            this.AdminDeleteDrink.AutoGenerateColors = false;
            this.AdminDeleteDrink.AutoRoundBorders = false;
            this.AdminDeleteDrink.AutoSizeLeftIcon = true;
            this.AdminDeleteDrink.AutoSizeRightIcon = true;
            this.AdminDeleteDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteDrink.BackgroundImage")));
            this.AdminDeleteDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.ButtonText = "DELETE";
            this.AdminDeleteDrink.ButtonTextMarginLeft = 0;
            this.AdminDeleteDrink.ColorContrastOnClick = 45;
            this.AdminDeleteDrink.ColorContrastOnHover = 45;
            this.AdminDeleteDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminDeleteDrink.CustomizableEdges = borderEdges3;
            this.AdminDeleteDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteDrink.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.AdminDeleteDrink.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteDrink.IconMarginLeft = 11;
            this.AdminDeleteDrink.IconPadding = 10;
            this.AdminDeleteDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteDrink.IconSize = 25;
            this.AdminDeleteDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleBorderRadius = 45;
            this.AdminDeleteDrink.IdleBorderThickness = 1;
            this.AdminDeleteDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.IdleIconLeftImage = null;
            this.AdminDeleteDrink.IdleIconRightImage = null;
            this.AdminDeleteDrink.IndicateFocus = false;
            this.AdminDeleteDrink.Location = new System.Drawing.Point(545, 409);
            this.AdminDeleteDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminDeleteDrink.Name = "AdminDeleteDrink";
            this.AdminDeleteDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteDrink.OnDisabledState.BorderRadius = 45;
            this.AdminDeleteDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteDrink.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteDrink.OnDisabledState.IconRightImage = null;
            this.AdminDeleteDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.BorderRadius = 45;
            this.AdminDeleteDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.onHoverState.BorderThickness = 1;
            this.AdminDeleteDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteDrink.onHoverState.IconLeftImage = null;
            this.AdminDeleteDrink.onHoverState.IconRightImage = null;
            this.AdminDeleteDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.BorderRadius = 45;
            this.AdminDeleteDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnIdleState.BorderThickness = 1;
            this.AdminDeleteDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnIdleState.IconLeftImage = null;
            this.AdminDeleteDrink.OnIdleState.IconRightImage = null;
            this.AdminDeleteDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.BorderRadius = 45;
            this.AdminDeleteDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteDrink.OnPressedState.BorderThickness = 1;
            this.AdminDeleteDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteDrink.OnPressedState.IconLeftImage = null;
            this.AdminDeleteDrink.OnPressedState.IconRightImage = null;
            this.AdminDeleteDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminDeleteDrink.TabIndex = 57;
            this.AdminDeleteDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteDrink.TextMarginLeft = 0;
            this.AdminDeleteDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteDrink.UseDefaultRadiusAndThickness = true;
            this.AdminDeleteDrink.Click += new System.EventHandler(this.AdminDeleteDrink_Click);
            // 
            // AdminAddDrink
            // 
            this.AdminAddDrink.AllowAnimations = true;
            this.AdminAddDrink.AllowMouseEffects = true;
            this.AdminAddDrink.AllowToggling = false;
            this.AdminAddDrink.AnimationSpeed = 200;
            this.AdminAddDrink.AutoGenerateColors = false;
            this.AdminAddDrink.AutoRoundBorders = false;
            this.AdminAddDrink.AutoSizeLeftIcon = true;
            this.AdminAddDrink.AutoSizeRightIcon = true;
            this.AdminAddDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddDrink.BackgroundImage")));
            this.AdminAddDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.ButtonText = "ADD";
            this.AdminAddDrink.ButtonTextMarginLeft = 0;
            this.AdminAddDrink.ColorContrastOnClick = 45;
            this.AdminAddDrink.ColorContrastOnHover = 45;
            this.AdminAddDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminAddDrink.CustomizableEdges = borderEdges4;
            this.AdminAddDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddDrink.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold);
            this.AdminAddDrink.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddDrink.IconMarginLeft = 11;
            this.AdminAddDrink.IconPadding = 10;
            this.AdminAddDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddDrink.IconSize = 25;
            this.AdminAddDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleBorderRadius = 45;
            this.AdminAddDrink.IdleBorderThickness = 1;
            this.AdminAddDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.IdleIconLeftImage = null;
            this.AdminAddDrink.IdleIconRightImage = null;
            this.AdminAddDrink.IndicateFocus = false;
            this.AdminAddDrink.Location = new System.Drawing.Point(634, 409);
            this.AdminAddDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminAddDrink.Name = "AdminAddDrink";
            this.AdminAddDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddDrink.OnDisabledState.BorderRadius = 45;
            this.AdminAddDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnDisabledState.BorderThickness = 1;
            this.AdminAddDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddDrink.OnDisabledState.IconLeftImage = null;
            this.AdminAddDrink.OnDisabledState.IconRightImage = null;
            this.AdminAddDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.BorderRadius = 45;
            this.AdminAddDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.onHoverState.BorderThickness = 1;
            this.AdminAddDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddDrink.onHoverState.IconLeftImage = null;
            this.AdminAddDrink.onHoverState.IconRightImage = null;
            this.AdminAddDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.BorderRadius = 45;
            this.AdminAddDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnIdleState.BorderThickness = 1;
            this.AdminAddDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnIdleState.IconLeftImage = null;
            this.AdminAddDrink.OnIdleState.IconRightImage = null;
            this.AdminAddDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.BorderRadius = 45;
            this.AdminAddDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddDrink.OnPressedState.BorderThickness = 1;
            this.AdminAddDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddDrink.OnPressedState.IconLeftImage = null;
            this.AdminAddDrink.OnPressedState.IconRightImage = null;
            this.AdminAddDrink.Size = new System.Drawing.Size(81, 45);
            this.AdminAddDrink.TabIndex = 56;
            this.AdminAddDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddDrink.TextMarginLeft = 0;
            this.AdminAddDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddDrink.UseDefaultRadiusAndThickness = true;
            this.AdminAddDrink.Click += new System.EventHandler(this.AdminAddDrink_Click);
            // 
            // AdminFillDrinkPrice
            // 
            this.AdminFillDrinkPrice.AcceptsReturn = false;
            this.AdminFillDrinkPrice.AcceptsTab = false;
            this.AdminFillDrinkPrice.AnimationSpeed = 200;
            this.AdminFillDrinkPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkPrice.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkPrice.BackgroundImage")));
            this.AdminFillDrinkPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkPrice.BorderRadius = 1;
            this.AdminFillDrinkPrice.BorderThickness = 1;
            this.AdminFillDrinkPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkPrice.DefaultText = "";
            this.AdminFillDrinkPrice.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkPrice.HideSelection = true;
            this.AdminFillDrinkPrice.IconLeft = null;
            this.AdminFillDrinkPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.IconPadding = 10;
            this.AdminFillDrinkPrice.IconRight = null;
            this.AdminFillDrinkPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.Lines = new string[0];
            this.AdminFillDrinkPrice.Location = new System.Drawing.Point(596, 204);
            this.AdminFillDrinkPrice.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkPrice.MaxLength = 32767;
            this.AdminFillDrinkPrice.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkPrice.Modified = false;
            this.AdminFillDrinkPrice.Multiline = false;
            this.AdminFillDrinkPrice.Name = "AdminFillDrinkPrice";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkPrice.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnIdleState = stateProperties12;
            this.AdminFillDrinkPrice.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkPrice.PasswordChar = '\0';
            this.AdminFillDrinkPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkPrice.PlaceholderText = "Price";
            this.AdminFillDrinkPrice.ReadOnly = false;
            this.AdminFillDrinkPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkPrice.SelectedText = "";
            this.AdminFillDrinkPrice.SelectionLength = 0;
            this.AdminFillDrinkPrice.SelectionStart = 0;
            this.AdminFillDrinkPrice.ShortcutsEnabled = true;
            this.AdminFillDrinkPrice.Size = new System.Drawing.Size(119, 42);
            this.AdminFillDrinkPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkPrice.TabIndex = 55;
            this.AdminFillDrinkPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkPrice.TextMarginBottom = 0;
            this.AdminFillDrinkPrice.TextMarginLeft = 3;
            this.AdminFillDrinkPrice.TextMarginTop = 0;
            this.AdminFillDrinkPrice.TextPlaceholder = "Price";
            this.AdminFillDrinkPrice.UseSystemPasswordChar = false;
            this.AdminFillDrinkPrice.WordWrap = true;
            this.AdminFillDrinkPrice.TextChanged += new System.EventHandler(this.AdminFillDrinkPrice_TextChanged);
            // 
            // AdminFillDrinkType
            // 
            this.AdminFillDrinkType.AcceptsReturn = false;
            this.AdminFillDrinkType.AcceptsTab = false;
            this.AdminFillDrinkType.AnimationSpeed = 200;
            this.AdminFillDrinkType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkType.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkType.BackgroundImage")));
            this.AdminFillDrinkType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkType.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkType.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkType.BorderRadius = 1;
            this.AdminFillDrinkType.BorderThickness = 1;
            this.AdminFillDrinkType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkType.DefaultText = "";
            this.AdminFillDrinkType.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkType.HideSelection = true;
            this.AdminFillDrinkType.IconLeft = null;
            this.AdminFillDrinkType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.IconPadding = 10;
            this.AdminFillDrinkType.IconRight = null;
            this.AdminFillDrinkType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.Lines = new string[0];
            this.AdminFillDrinkType.Location = new System.Drawing.Point(595, 253);
            this.AdminFillDrinkType.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkType.MaxLength = 32767;
            this.AdminFillDrinkType.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkType.Modified = false;
            this.AdminFillDrinkType.Multiline = false;
            this.AdminFillDrinkType.Name = "AdminFillDrinkType";
            stateProperties13.BorderColor = System.Drawing.Color.Transparent;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Transparent;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkType.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnIdleState = stateProperties16;
            this.AdminFillDrinkType.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkType.PasswordChar = '\0';
            this.AdminFillDrinkType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkType.PlaceholderText = "Type\r\n";
            this.AdminFillDrinkType.ReadOnly = false;
            this.AdminFillDrinkType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkType.SelectedText = "";
            this.AdminFillDrinkType.SelectionLength = 0;
            this.AdminFillDrinkType.SelectionStart = 0;
            this.AdminFillDrinkType.ShortcutsEnabled = true;
            this.AdminFillDrinkType.Size = new System.Drawing.Size(120, 42);
            this.AdminFillDrinkType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkType.TabIndex = 50;
            this.AdminFillDrinkType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkType.TextMarginBottom = 0;
            this.AdminFillDrinkType.TextMarginLeft = 3;
            this.AdminFillDrinkType.TextMarginTop = 0;
            this.AdminFillDrinkType.TextPlaceholder = "Type\r\n";
            this.AdminFillDrinkType.UseSystemPasswordChar = false;
            this.AdminFillDrinkType.WordWrap = true;
            // 
            // AdminFillDrinkID
            // 
            this.AdminFillDrinkID.AcceptsReturn = false;
            this.AdminFillDrinkID.AcceptsTab = false;
            this.AdminFillDrinkID.AnimationSpeed = 200;
            this.AdminFillDrinkID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkID.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkID.BackgroundImage")));
            this.AdminFillDrinkID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkID.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkID.BorderRadius = 1;
            this.AdminFillDrinkID.BorderThickness = 1;
            this.AdminFillDrinkID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkID.DefaultText = "";
            this.AdminFillDrinkID.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkID.HideSelection = true;
            this.AdminFillDrinkID.IconLeft = null;
            this.AdminFillDrinkID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.IconPadding = 10;
            this.AdminFillDrinkID.IconRight = null;
            this.AdminFillDrinkID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.Lines = new string[0];
            this.AdminFillDrinkID.Location = new System.Drawing.Point(596, 154);
            this.AdminFillDrinkID.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkID.MaxLength = 32767;
            this.AdminFillDrinkID.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkID.Modified = false;
            this.AdminFillDrinkID.Multiline = false;
            this.AdminFillDrinkID.Name = "AdminFillDrinkID";
            stateProperties17.BorderColor = System.Drawing.Color.Transparent;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Transparent;
            stateProperties18.FillColor = System.Drawing.Color.Transparent;
            stateProperties18.ForeColor = System.Drawing.Color.Transparent;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkID.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Transparent;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnIdleState = stateProperties20;
            this.AdminFillDrinkID.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkID.PasswordChar = '\0';
            this.AdminFillDrinkID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkID.PlaceholderText = "ID";
            this.AdminFillDrinkID.ReadOnly = false;
            this.AdminFillDrinkID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkID.SelectedText = "";
            this.AdminFillDrinkID.SelectionLength = 0;
            this.AdminFillDrinkID.SelectionStart = 0;
            this.AdminFillDrinkID.ShortcutsEnabled = true;
            this.AdminFillDrinkID.Size = new System.Drawing.Size(119, 42);
            this.AdminFillDrinkID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkID.TabIndex = 47;
            this.AdminFillDrinkID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkID.TextMarginBottom = 0;
            this.AdminFillDrinkID.TextMarginLeft = 3;
            this.AdminFillDrinkID.TextMarginTop = 0;
            this.AdminFillDrinkID.TextPlaceholder = "ID";
            this.AdminFillDrinkID.UseSystemPasswordChar = false;
            this.AdminFillDrinkID.WordWrap = true;
            // 
            // AdminCheckDrink
            // 
            this.AdminCheckDrink.AllowAnimations = true;
            this.AdminCheckDrink.AllowMouseEffects = true;
            this.AdminCheckDrink.AllowToggling = false;
            this.AdminCheckDrink.AnimationSpeed = 200;
            this.AdminCheckDrink.AutoGenerateColors = false;
            this.AdminCheckDrink.AutoRoundBorders = false;
            this.AdminCheckDrink.AutoSizeLeftIcon = true;
            this.AdminCheckDrink.AutoSizeRightIcon = true;
            this.AdminCheckDrink.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckDrink.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckDrink.BackgroundImage")));
            this.AdminCheckDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.ButtonText = "CHECK";
            this.AdminCheckDrink.ButtonTextMarginLeft = 0;
            this.AdminCheckDrink.ColorContrastOnClick = 45;
            this.AdminCheckDrink.ColorContrastOnHover = 45;
            this.AdminCheckDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminCheckDrink.CustomizableEdges = borderEdges5;
            this.AdminCheckDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckDrink.Font = new System.Drawing.Font("Century Gothic", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckDrink.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckDrink.IconMarginLeft = 11;
            this.AdminCheckDrink.IconPadding = 10;
            this.AdminCheckDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckDrink.IconSize = 25;
            this.AdminCheckDrink.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.IdleBorderRadius = 42;
            this.AdminCheckDrink.IdleBorderThickness = 1;
            this.AdminCheckDrink.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.IdleIconLeftImage = null;
            this.AdminCheckDrink.IdleIconRightImage = null;
            this.AdminCheckDrink.IndicateFocus = false;
            this.AdminCheckDrink.Location = new System.Drawing.Point(459, 76);
            this.AdminCheckDrink.Margin = new System.Windows.Forms.Padding(4);
            this.AdminCheckDrink.Name = "AdminCheckDrink";
            this.AdminCheckDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckDrink.OnDisabledState.BorderRadius = 42;
            this.AdminCheckDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnDisabledState.BorderThickness = 1;
            this.AdminCheckDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckDrink.OnDisabledState.IconLeftImage = null;
            this.AdminCheckDrink.OnDisabledState.IconRightImage = null;
            this.AdminCheckDrink.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.onHoverState.BorderRadius = 42;
            this.AdminCheckDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.onHoverState.BorderThickness = 1;
            this.AdminCheckDrink.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckDrink.onHoverState.IconLeftImage = null;
            this.AdminCheckDrink.onHoverState.IconRightImage = null;
            this.AdminCheckDrink.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnIdleState.BorderRadius = 42;
            this.AdminCheckDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnIdleState.BorderThickness = 1;
            this.AdminCheckDrink.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.OnIdleState.IconLeftImage = null;
            this.AdminCheckDrink.OnIdleState.IconRightImage = null;
            this.AdminCheckDrink.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnPressedState.BorderRadius = 42;
            this.AdminCheckDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckDrink.OnPressedState.BorderThickness = 1;
            this.AdminCheckDrink.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckDrink.OnPressedState.IconLeftImage = null;
            this.AdminCheckDrink.OnPressedState.IconRightImage = null;
            this.AdminCheckDrink.Size = new System.Drawing.Size(256, 45);
            this.AdminCheckDrink.TabIndex = 46;
            this.AdminCheckDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckDrink.TextMarginLeft = 0;
            this.AdminCheckDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckDrink.UseDefaultRadiusAndThickness = true;
            this.AdminCheckDrink.Click += new System.EventHandler(this.AdminCheckDrink_Click);
            // 
            // AdminViewAllYourDrinks
            // 
            this.AdminViewAllYourDrinks.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.AdminViewAllYourDrinks.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.AdminViewAllYourDrinks.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.AdminViewAllYourDrinks.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.AdminViewAllYourDrinks.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.AdminViewAllYourDrinks.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.AdminViewAllYourDrinks.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.AdminViewAllYourDrinks.ColumnHeadersHeight = 40;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.Name = null;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.AdminViewAllYourDrinks.DefaultCellStyle = dataGridViewCellStyle3;
            this.AdminViewAllYourDrinks.EnableHeadersVisualStyles = false;
            this.AdminViewAllYourDrinks.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.HeaderBgColor = System.Drawing.Color.Empty;
            this.AdminViewAllYourDrinks.HeaderForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.Location = new System.Drawing.Point(16, 14);
            this.AdminViewAllYourDrinks.Name = "AdminViewAllYourDrinks";
            this.AdminViewAllYourDrinks.RowHeadersVisible = false;
            this.AdminViewAllYourDrinks.RowHeadersWidth = 62;
            this.AdminViewAllYourDrinks.RowTemplate.Height = 40;
            this.AdminViewAllYourDrinks.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.AdminViewAllYourDrinks.Size = new System.Drawing.Size(417, 449);
            this.AdminViewAllYourDrinks.TabIndex = 59;
            this.AdminViewAllYourDrinks.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.AdminViewAllYourDrinks.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.AdminViewAllYourDrinks_CellContentClick);
            // 
            // AdminFillDrinkSearch
            // 
            this.AdminFillDrinkSearch.AcceptsReturn = false;
            this.AdminFillDrinkSearch.AcceptsTab = false;
            this.AdminFillDrinkSearch.AnimationSpeed = 200;
            this.AdminFillDrinkSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkSearch.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkSearch.BackgroundImage")));
            this.AdminFillDrinkSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkSearch.BorderRadius = 1;
            this.AdminFillDrinkSearch.BorderThickness = 1;
            this.AdminFillDrinkSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkSearch.DefaultText = "";
            this.AdminFillDrinkSearch.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkSearch.HideSelection = true;
            this.AdminFillDrinkSearch.IconLeft = null;
            this.AdminFillDrinkSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.IconPadding = 10;
            this.AdminFillDrinkSearch.IconRight = null;
            this.AdminFillDrinkSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.Lines = new string[0];
            this.AdminFillDrinkSearch.Location = new System.Drawing.Point(460, 14);
            this.AdminFillDrinkSearch.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkSearch.MaxLength = 32767;
            this.AdminFillDrinkSearch.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkSearch.Modified = false;
            this.AdminFillDrinkSearch.Multiline = false;
            this.AdminFillDrinkSearch.Name = "AdminFillDrinkSearch";
            stateProperties5.BorderColor = System.Drawing.Color.Transparent;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkSearch.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnIdleState = stateProperties8;
            this.AdminFillDrinkSearch.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkSearch.PasswordChar = '\0';
            this.AdminFillDrinkSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkSearch.PlaceholderText = "Fill your Drink\'s ID";
            this.AdminFillDrinkSearch.ReadOnly = false;
            this.AdminFillDrinkSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkSearch.SelectedText = "";
            this.AdminFillDrinkSearch.SelectionLength = 0;
            this.AdminFillDrinkSearch.SelectionStart = 0;
            this.AdminFillDrinkSearch.ShortcutsEnabled = true;
            this.AdminFillDrinkSearch.Size = new System.Drawing.Size(255, 45);
            this.AdminFillDrinkSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkSearch.TabIndex = 60;
            this.AdminFillDrinkSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkSearch.TextMarginBottom = 0;
            this.AdminFillDrinkSearch.TextMarginLeft = 3;
            this.AdminFillDrinkSearch.TextMarginTop = 0;
            this.AdminFillDrinkSearch.TextPlaceholder = "Fill your Drink\'s ID";
            this.AdminFillDrinkSearch.UseSystemPasswordChar = false;
            this.AdminFillDrinkSearch.WordWrap = true;
            // 
            // AdminFillDrinkName
            // 
            this.AdminFillDrinkName.AcceptsReturn = false;
            this.AdminFillDrinkName.AcceptsTab = false;
            this.AdminFillDrinkName.AnimationSpeed = 200;
            this.AdminFillDrinkName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkName.BackgroundImage")));
            this.AdminFillDrinkName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillDrinkName.BorderRadius = 1;
            this.AdminFillDrinkName.BorderThickness = 1;
            this.AdminFillDrinkName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkName.DefaultText = "";
            this.AdminFillDrinkName.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkName.HideSelection = true;
            this.AdminFillDrinkName.IconLeft = null;
            this.AdminFillDrinkName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.IconPadding = 10;
            this.AdminFillDrinkName.IconRight = null;
            this.AdminFillDrinkName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.Lines = new string[0];
            this.AdminFillDrinkName.Location = new System.Drawing.Point(459, 303);
            this.AdminFillDrinkName.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkName.MaxLength = 32767;
            this.AdminFillDrinkName.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkName.Modified = false;
            this.AdminFillDrinkName.Multiline = false;
            this.AdminFillDrinkName.Name = "AdminFillDrinkName";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnIdleState = stateProperties4;
            this.AdminFillDrinkName.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkName.PasswordChar = '\0';
            this.AdminFillDrinkName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkName.PlaceholderText = "Name";
            this.AdminFillDrinkName.ReadOnly = false;
            this.AdminFillDrinkName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkName.SelectedText = "";
            this.AdminFillDrinkName.SelectionLength = 0;
            this.AdminFillDrinkName.SelectionStart = 0;
            this.AdminFillDrinkName.ShortcutsEnabled = true;
            this.AdminFillDrinkName.Size = new System.Drawing.Size(256, 41);
            this.AdminFillDrinkName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkName.TabIndex = 61;
            this.AdminFillDrinkName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkName.TextMarginBottom = 0;
            this.AdminFillDrinkName.TextMarginLeft = 3;
            this.AdminFillDrinkName.TextMarginTop = 0;
            this.AdminFillDrinkName.TextPlaceholder = "Name";
            this.AdminFillDrinkName.UseSystemPasswordChar = false;
            this.AdminFillDrinkName.WordWrap = true;
            // 
            // AdminFillDrinkAvailable
            // 
            this.AdminFillDrinkAvailable.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkAvailable.BackgroundColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.BorderColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkAvailable.BorderRadius = 0;
            this.AdminFillDrinkAvailable.Color = System.Drawing.Color.Silver;
            this.AdminFillDrinkAvailable.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.AdminFillDrinkAvailable.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.AdminFillDrinkAvailable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkAvailable.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.AdminFillDrinkAvailable.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.AdminFillDrinkAvailable.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkAvailable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.AdminFillDrinkAvailable.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.AdminFillDrinkAvailable.DropDownHeight = 300;
            this.AdminFillDrinkAvailable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.AdminFillDrinkAvailable.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.AdminFillDrinkAvailable.FillDropDown = true;
            this.AdminFillDrinkAvailable.FillIndicator = false;
            this.AdminFillDrinkAvailable.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.AdminFillDrinkAvailable.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkAvailable.ForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkAvailable.FormattingEnabled = true;
            this.AdminFillDrinkAvailable.Icon = null;
            this.AdminFillDrinkAvailable.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.AdminFillDrinkAvailable.IndicatorColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.AdminFillDrinkAvailable.IntegralHeight = false;
            this.AdminFillDrinkAvailable.ItemBackColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.ItemBorderColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.ItemForeColor = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.ItemHeight = 35;
            this.AdminFillDrinkAvailable.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkAvailable.ItemHighLightForeColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.Items.AddRange(new object[] {
            "Available",
            "Unavailable"});
            this.AdminFillDrinkAvailable.ItemTopMargin = 3;
            this.AdminFillDrinkAvailable.Location = new System.Drawing.Point(460, 349);
            this.AdminFillDrinkAvailable.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkAvailable.Name = "AdminFillDrinkAvailable";
            this.AdminFillDrinkAvailable.Size = new System.Drawing.Size(153, 41);
            this.AdminFillDrinkAvailable.TabIndex = 63;
            this.AdminFillDrinkAvailable.Text = "Status";
            this.AdminFillDrinkAvailable.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.AdminFillDrinkAvailable.TextLeftMargin = 5;
            // 
            // btnImage
            // 
            this.btnImage.AllowAnimations = true;
            this.btnImage.AllowMouseEffects = true;
            this.btnImage.AllowToggling = false;
            this.btnImage.AnimationSpeed = 200;
            this.btnImage.AutoGenerateColors = false;
            this.btnImage.AutoRoundBorders = false;
            this.btnImage.AutoSizeLeftIcon = true;
            this.btnImage.AutoSizeRightIcon = true;
            this.btnImage.BackColor = System.Drawing.Color.Transparent;
            this.btnImage.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImage.BackgroundImage")));
            this.btnImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.ButtonText = "Image";
            this.btnImage.ButtonTextMarginLeft = 0;
            this.btnImage.ColorContrastOnClick = 45;
            this.btnImage.ColorContrastOnHover = 45;
            this.btnImage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnImage.CustomizableEdges = borderEdges1;
            this.btnImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnImage.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnImage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnImage.IconMarginLeft = 11;
            this.btnImage.IconPadding = 10;
            this.btnImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnImage.IconSize = 25;
            this.btnImage.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IdleBorderRadius = 10;
            this.btnImage.IdleBorderThickness = 1;
            this.btnImage.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.IdleIconLeftImage = null;
            this.btnImage.IdleIconRightImage = null;
            this.btnImage.IndicateFocus = false;
            this.btnImage.Location = new System.Drawing.Point(621, 349);
            this.btnImage.Margin = new System.Windows.Forms.Padding(4);
            this.btnImage.Name = "btnImage";
            this.btnImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.OnDisabledState.BorderRadius = 10;
            this.btnImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnDisabledState.BorderThickness = 1;
            this.btnImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.OnDisabledState.IconLeftImage = null;
            this.btnImage.OnDisabledState.IconRightImage = null;
            this.btnImage.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.onHoverState.BorderRadius = 10;
            this.btnImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.onHoverState.BorderThickness = 1;
            this.btnImage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnImage.onHoverState.IconLeftImage = null;
            this.btnImage.onHoverState.IconRightImage = null;
            this.btnImage.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.BorderRadius = 10;
            this.btnImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnIdleState.BorderThickness = 1;
            this.btnImage.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.IconLeftImage = null;
            this.btnImage.OnIdleState.IconRightImage = null;
            this.btnImage.OnPressedState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.OnPressedState.BorderRadius = 10;
            this.btnImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnPressedState.BorderThickness = 1;
            this.btnImage.OnPressedState.FillColor = System.Drawing.Color.Sienna;
            this.btnImage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImage.OnPressedState.IconLeftImage = null;
            this.btnImage.OnPressedState.IconRightImage = null;
            this.btnImage.Size = new System.Drawing.Size(94, 41);
            this.btnImage.TabIndex = 65;
            this.btnImage.TabStop = false;
            this.btnImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImage.TextMarginLeft = 0;
            this.btnImage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnImage.UseDefaultRadiusAndThickness = true;
            this.btnImage.Click += new System.EventHandler(this.btnImage_Click);
            // 
            // pictureBox
            // 
            this.pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pictureBox.Location = new System.Drawing.Point(461, 154);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(127, 141);
            this.pictureBox.TabIndex = 67;
            this.pictureBox.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(463, 128);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(180, 15);
            this.bunifuLabel1.TabIndex = 68;
            this.bunifuLabel1.Text = "------------------------------------";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminDrink
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.btnImage);
            this.Controls.Add(this.AdminFillDrinkAvailable);
            this.Controls.Add(this.AdminFillDrinkName);
            this.Controls.Add(this.AdminFillDrinkSearch);
            this.Controls.Add(this.AdminViewAllYourDrinks);
            this.Controls.Add(this.AdminUpdateDrink);
            this.Controls.Add(this.AdminDeleteDrink);
            this.Controls.Add(this.AdminAddDrink);
            this.Controls.Add(this.AdminFillDrinkPrice);
            this.Controls.Add(this.AdminFillDrinkType);
            this.Controls.Add(this.AdminFillDrinkID);
            this.Controls.Add(this.AdminCheckDrink);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "AdminDrink";
            this.Size = new System.Drawing.Size(731, 484);
            this.Load += new System.EventHandler(this.AdminDrink_Load_1);
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddDrink;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkPrice;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkType;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckDrink;
        private Bunifu.UI.WinForms.BunifuDataGridView AdminViewAllYourDrinks;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkName;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkSearch;
        private Bunifu.UI.WinForms.BunifuDropdown AdminFillDrinkAvailable;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnImage;
        private System.Windows.Forms.PictureBox pictureBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}
