namespace UI
{
    partial class AdminProduct
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminProduct));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminUpdateProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillEmployeeGender = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductAvailable = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllCustomer = new System.Windows.Forms.ListView();
            this.AdminShowAllProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminUpdateProduct
            // 
            this.AdminUpdateProduct.AllowAnimations = true;
            this.AdminUpdateProduct.AllowMouseEffects = true;
            this.AdminUpdateProduct.AllowToggling = false;
            this.AdminUpdateProduct.AnimationSpeed = 200;
            this.AdminUpdateProduct.AutoGenerateColors = false;
            this.AdminUpdateProduct.AutoRoundBorders = false;
            this.AdminUpdateProduct.AutoSizeLeftIcon = true;
            this.AdminUpdateProduct.AutoSizeRightIcon = true;
            this.AdminUpdateProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateProduct.BackgroundImage")));
            this.AdminUpdateProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.ButtonText = "Update";
            this.AdminUpdateProduct.ButtonTextMarginLeft = 0;
            this.AdminUpdateProduct.ColorContrastOnClick = 45;
            this.AdminUpdateProduct.ColorContrastOnHover = 45;
            this.AdminUpdateProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AdminUpdateProduct.CustomizableEdges = borderEdges1;
            this.AdminUpdateProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateProduct.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateProduct.IconMarginLeft = 11;
            this.AdminUpdateProduct.IconPadding = 10;
            this.AdminUpdateProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateProduct.IconSize = 25;
            this.AdminUpdateProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.IdleBorderRadius = 37;
            this.AdminUpdateProduct.IdleBorderThickness = 1;
            this.AdminUpdateProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.IdleIconLeftImage = null;
            this.AdminUpdateProduct.IdleIconRightImage = null;
            this.AdminUpdateProduct.IndicateFocus = false;
            this.AdminUpdateProduct.Location = new System.Drawing.Point(716, 433);
            this.AdminUpdateProduct.Name = "AdminUpdateProduct";
            this.AdminUpdateProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateProduct.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateProduct.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateProduct.OnDisabledState.IconRightImage = null;
            this.AdminUpdateProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.onHoverState.BorderRadius = 37;
            this.AdminUpdateProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.onHoverState.BorderThickness = 1;
            this.AdminUpdateProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateProduct.onHoverState.IconLeftImage = null;
            this.AdminUpdateProduct.onHoverState.IconRightImage = null;
            this.AdminUpdateProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnIdleState.BorderRadius = 37;
            this.AdminUpdateProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnIdleState.BorderThickness = 1;
            this.AdminUpdateProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.OnIdleState.IconLeftImage = null;
            this.AdminUpdateProduct.OnIdleState.IconRightImage = null;
            this.AdminUpdateProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnPressedState.BorderRadius = 37;
            this.AdminUpdateProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnPressedState.BorderThickness = 1;
            this.AdminUpdateProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.OnPressedState.IconLeftImage = null;
            this.AdminUpdateProduct.OnPressedState.IconRightImage = null;
            this.AdminUpdateProduct.Size = new System.Drawing.Size(330, 36);
            this.AdminUpdateProduct.TabIndex = 58;
            this.AdminUpdateProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateProduct.TextMarginLeft = 0;
            this.AdminUpdateProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteProduct
            // 
            this.AdminDeleteProduct.AllowAnimations = true;
            this.AdminDeleteProduct.AllowMouseEffects = true;
            this.AdminDeleteProduct.AllowToggling = false;
            this.AdminDeleteProduct.AnimationSpeed = 200;
            this.AdminDeleteProduct.AutoGenerateColors = false;
            this.AdminDeleteProduct.AutoRoundBorders = false;
            this.AdminDeleteProduct.AutoSizeLeftIcon = true;
            this.AdminDeleteProduct.AutoSizeRightIcon = true;
            this.AdminDeleteProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteProduct.BackgroundImage")));
            this.AdminDeleteProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.ButtonText = "DELETE";
            this.AdminDeleteProduct.ButtonTextMarginLeft = 0;
            this.AdminDeleteProduct.ColorContrastOnClick = 45;
            this.AdminDeleteProduct.ColorContrastOnHover = 45;
            this.AdminDeleteProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AdminDeleteProduct.CustomizableEdges = borderEdges2;
            this.AdminDeleteProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteProduct.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteProduct.IconMarginLeft = 11;
            this.AdminDeleteProduct.IconPadding = 10;
            this.AdminDeleteProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteProduct.IconSize = 25;
            this.AdminDeleteProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.IdleBorderRadius = 37;
            this.AdminDeleteProduct.IdleBorderThickness = 1;
            this.AdminDeleteProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.IdleIconLeftImage = null;
            this.AdminDeleteProduct.IdleIconRightImage = null;
            this.AdminDeleteProduct.IndicateFocus = false;
            this.AdminDeleteProduct.Location = new System.Drawing.Point(886, 382);
            this.AdminDeleteProduct.Name = "AdminDeleteProduct";
            this.AdminDeleteProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteProduct.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteProduct.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteProduct.OnDisabledState.IconRightImage = null;
            this.AdminDeleteProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.onHoverState.BorderRadius = 37;
            this.AdminDeleteProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.onHoverState.BorderThickness = 1;
            this.AdminDeleteProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteProduct.onHoverState.IconLeftImage = null;
            this.AdminDeleteProduct.onHoverState.IconRightImage = null;
            this.AdminDeleteProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnIdleState.BorderRadius = 37;
            this.AdminDeleteProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnIdleState.BorderThickness = 1;
            this.AdminDeleteProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.OnIdleState.IconLeftImage = null;
            this.AdminDeleteProduct.OnIdleState.IconRightImage = null;
            this.AdminDeleteProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnPressedState.BorderRadius = 37;
            this.AdminDeleteProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnPressedState.BorderThickness = 1;
            this.AdminDeleteProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.OnPressedState.IconLeftImage = null;
            this.AdminDeleteProduct.OnPressedState.IconRightImage = null;
            this.AdminDeleteProduct.Size = new System.Drawing.Size(160, 36);
            this.AdminDeleteProduct.TabIndex = 57;
            this.AdminDeleteProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteProduct.TextMarginLeft = 0;
            this.AdminDeleteProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddProduct
            // 
            this.AdminAddProduct.AllowAnimations = true;
            this.AdminAddProduct.AllowMouseEffects = true;
            this.AdminAddProduct.AllowToggling = false;
            this.AdminAddProduct.AnimationSpeed = 200;
            this.AdminAddProduct.AutoGenerateColors = false;
            this.AdminAddProduct.AutoRoundBorders = false;
            this.AdminAddProduct.AutoSizeLeftIcon = true;
            this.AdminAddProduct.AutoSizeRightIcon = true;
            this.AdminAddProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddProduct.BackgroundImage")));
            this.AdminAddProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.ButtonText = "ADD";
            this.AdminAddProduct.ButtonTextMarginLeft = 0;
            this.AdminAddProduct.ColorContrastOnClick = 45;
            this.AdminAddProduct.ColorContrastOnHover = 45;
            this.AdminAddProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.AdminAddProduct.CustomizableEdges = borderEdges3;
            this.AdminAddProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddProduct.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddProduct.IconMarginLeft = 11;
            this.AdminAddProduct.IconPadding = 10;
            this.AdminAddProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddProduct.IconSize = 25;
            this.AdminAddProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.IdleBorderRadius = 37;
            this.AdminAddProduct.IdleBorderThickness = 1;
            this.AdminAddProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.IdleIconLeftImage = null;
            this.AdminAddProduct.IdleIconRightImage = null;
            this.AdminAddProduct.IndicateFocus = false;
            this.AdminAddProduct.Location = new System.Drawing.Point(716, 382);
            this.AdminAddProduct.Name = "AdminAddProduct";
            this.AdminAddProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddProduct.OnDisabledState.BorderRadius = 37;
            this.AdminAddProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnDisabledState.BorderThickness = 1;
            this.AdminAddProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddProduct.OnDisabledState.IconLeftImage = null;
            this.AdminAddProduct.OnDisabledState.IconRightImage = null;
            this.AdminAddProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.onHoverState.BorderRadius = 37;
            this.AdminAddProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.onHoverState.BorderThickness = 1;
            this.AdminAddProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddProduct.onHoverState.IconLeftImage = null;
            this.AdminAddProduct.onHoverState.IconRightImage = null;
            this.AdminAddProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnIdleState.BorderRadius = 37;
            this.AdminAddProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnIdleState.BorderThickness = 1;
            this.AdminAddProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.OnIdleState.IconLeftImage = null;
            this.AdminAddProduct.OnIdleState.IconRightImage = null;
            this.AdminAddProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnPressedState.BorderRadius = 37;
            this.AdminAddProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnPressedState.BorderThickness = 1;
            this.AdminAddProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.OnPressedState.IconLeftImage = null;
            this.AdminAddProduct.OnPressedState.IconRightImage = null;
            this.AdminAddProduct.Size = new System.Drawing.Size(160, 36);
            this.AdminAddProduct.TabIndex = 56;
            this.AdminAddProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddProduct.TextMarginLeft = 0;
            this.AdminAddProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillEmployeeGender
            // 
            this.AdminFillEmployeeGender.AcceptsReturn = false;
            this.AdminFillEmployeeGender.AcceptsTab = false;
            this.AdminFillEmployeeGender.AnimationSpeed = 200;
            this.AdminFillEmployeeGender.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillEmployeeGender.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillEmployeeGender.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillEmployeeGender.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillEmployeeGender.BackgroundImage")));
            this.AdminFillEmployeeGender.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillEmployeeGender.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillEmployeeGender.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillEmployeeGender.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillEmployeeGender.BorderRadius = 1;
            this.AdminFillEmployeeGender.BorderThickness = 1;
            this.AdminFillEmployeeGender.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillEmployeeGender.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillEmployeeGender.DefaultText = "";
            this.AdminFillEmployeeGender.FillColor = System.Drawing.Color.White;
            this.AdminFillEmployeeGender.HideSelection = true;
            this.AdminFillEmployeeGender.IconLeft = null;
            this.AdminFillEmployeeGender.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.IconPadding = 10;
            this.AdminFillEmployeeGender.IconRight = null;
            this.AdminFillEmployeeGender.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.Lines = new string[0];
            this.AdminFillEmployeeGender.Location = new System.Drawing.Point(716, 215);
            this.AdminFillEmployeeGender.MaxLength = 32767;
            this.AdminFillEmployeeGender.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillEmployeeGender.Modified = false;
            this.AdminFillEmployeeGender.Multiline = false;
            this.AdminFillEmployeeGender.Name = "AdminFillEmployeeGender";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillEmployeeGender.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnIdleState = stateProperties4;
            this.AdminFillEmployeeGender.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillEmployeeGender.PasswordChar = '\0';
            this.AdminFillEmployeeGender.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillEmployeeGender.PlaceholderText = "Fill your Employee\'s Gender";
            this.AdminFillEmployeeGender.ReadOnly = false;
            this.AdminFillEmployeeGender.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillEmployeeGender.SelectedText = "";
            this.AdminFillEmployeeGender.SelectionLength = 0;
            this.AdminFillEmployeeGender.SelectionStart = 0;
            this.AdminFillEmployeeGender.ShortcutsEnabled = true;
            this.AdminFillEmployeeGender.Size = new System.Drawing.Size(330, 37);
            this.AdminFillEmployeeGender.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillEmployeeGender.TabIndex = 55;
            this.AdminFillEmployeeGender.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillEmployeeGender.TextMarginBottom = 0;
            this.AdminFillEmployeeGender.TextMarginLeft = 3;
            this.AdminFillEmployeeGender.TextMarginTop = 0;
            this.AdminFillEmployeeGender.TextPlaceholder = "Fill your Employee\'s Gender";
            this.AdminFillEmployeeGender.UseSystemPasswordChar = false;
            this.AdminFillEmployeeGender.WordWrap = true;
            // 
            // AdminFillProductPrice
            // 
            this.AdminFillProductPrice.AcceptsReturn = false;
            this.AdminFillProductPrice.AcceptsTab = false;
            this.AdminFillProductPrice.AnimationSpeed = 200;
            this.AdminFillProductPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductPrice.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductPrice.BackgroundImage")));
            this.AdminFillProductPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductPrice.BorderRadius = 1;
            this.AdminFillProductPrice.BorderThickness = 1;
            this.AdminFillProductPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductPrice.DefaultText = "";
            this.AdminFillProductPrice.FillColor = System.Drawing.Color.White;
            this.AdminFillProductPrice.HideSelection = true;
            this.AdminFillProductPrice.IconLeft = null;
            this.AdminFillProductPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.IconPadding = 10;
            this.AdminFillProductPrice.IconRight = null;
            this.AdminFillProductPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.Lines = new string[0];
            this.AdminFillProductPrice.Location = new System.Drawing.Point(716, 271);
            this.AdminFillProductPrice.MaxLength = 32767;
            this.AdminFillProductPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductPrice.Modified = false;
            this.AdminFillProductPrice.Multiline = false;
            this.AdminFillProductPrice.Name = "AdminFillProductPrice";
            stateProperties5.BorderColor = System.Drawing.Color.Transparent;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnIdleState = stateProperties8;
            this.AdminFillProductPrice.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductPrice.PasswordChar = '\0';
            this.AdminFillProductPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductPrice.PlaceholderText = "Fill your Product\'s Price\r\n";
            this.AdminFillProductPrice.ReadOnly = false;
            this.AdminFillProductPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductPrice.SelectedText = "";
            this.AdminFillProductPrice.SelectionLength = 0;
            this.AdminFillProductPrice.SelectionStart = 0;
            this.AdminFillProductPrice.ShortcutsEnabled = true;
            this.AdminFillProductPrice.Size = new System.Drawing.Size(330, 37);
            this.AdminFillProductPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductPrice.TabIndex = 54;
            this.AdminFillProductPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductPrice.TextMarginBottom = 0;
            this.AdminFillProductPrice.TextMarginLeft = 3;
            this.AdminFillProductPrice.TextMarginTop = 0;
            this.AdminFillProductPrice.TextPlaceholder = "Fill your Product\'s Price\r\n";
            this.AdminFillProductPrice.UseSystemPasswordChar = false;
            this.AdminFillProductPrice.WordWrap = true;
            // 
            // AdminFillProductAvailable
            // 
            this.AdminFillProductAvailable.AcceptsReturn = false;
            this.AdminFillProductAvailable.AcceptsTab = false;
            this.AdminFillProductAvailable.AnimationSpeed = 200;
            this.AdminFillProductAvailable.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductAvailable.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductAvailable.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductAvailable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductAvailable.BackgroundImage")));
            this.AdminFillProductAvailable.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductAvailable.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductAvailable.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductAvailable.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductAvailable.BorderRadius = 1;
            this.AdminFillProductAvailable.BorderThickness = 1;
            this.AdminFillProductAvailable.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductAvailable.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductAvailable.DefaultText = "";
            this.AdminFillProductAvailable.FillColor = System.Drawing.Color.White;
            this.AdminFillProductAvailable.HideSelection = true;
            this.AdminFillProductAvailable.IconLeft = null;
            this.AdminFillProductAvailable.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.IconPadding = 10;
            this.AdminFillProductAvailable.IconRight = null;
            this.AdminFillProductAvailable.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.Lines = new string[0];
            this.AdminFillProductAvailable.Location = new System.Drawing.Point(716, 329);
            this.AdminFillProductAvailable.MaxLength = 32767;
            this.AdminFillProductAvailable.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductAvailable.Modified = false;
            this.AdminFillProductAvailable.Multiline = false;
            this.AdminFillProductAvailable.Name = "AdminFillProductAvailable";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductAvailable.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnIdleState = stateProperties12;
            this.AdminFillProductAvailable.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductAvailable.PasswordChar = '\0';
            this.AdminFillProductAvailable.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductAvailable.PlaceholderText = "Fill your Product\'s Available\r\n";
            this.AdminFillProductAvailable.ReadOnly = false;
            this.AdminFillProductAvailable.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductAvailable.SelectedText = "";
            this.AdminFillProductAvailable.SelectionLength = 0;
            this.AdminFillProductAvailable.SelectionStart = 0;
            this.AdminFillProductAvailable.ShortcutsEnabled = true;
            this.AdminFillProductAvailable.Size = new System.Drawing.Size(330, 37);
            this.AdminFillProductAvailable.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductAvailable.TabIndex = 53;
            this.AdminFillProductAvailable.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductAvailable.TextMarginBottom = 0;
            this.AdminFillProductAvailable.TextMarginLeft = 3;
            this.AdminFillProductAvailable.TextMarginTop = 0;
            this.AdminFillProductAvailable.TextPlaceholder = "Fill your Product\'s Available\r\n";
            this.AdminFillProductAvailable.UseSystemPasswordChar = false;
            this.AdminFillProductAvailable.WordWrap = true;
            // 
            // AdminFillProductType
            // 
            this.AdminFillProductType.AcceptsReturn = false;
            this.AdminFillProductType.AcceptsTab = false;
            this.AdminFillProductType.AnimationSpeed = 200;
            this.AdminFillProductType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductType.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductType.BackgroundImage")));
            this.AdminFillProductType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductType.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductType.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductType.BorderRadius = 1;
            this.AdminFillProductType.BorderThickness = 1;
            this.AdminFillProductType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductType.DefaultText = "";
            this.AdminFillProductType.FillColor = System.Drawing.Color.White;
            this.AdminFillProductType.HideSelection = true;
            this.AdminFillProductType.IconLeft = null;
            this.AdminFillProductType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.IconPadding = 10;
            this.AdminFillProductType.IconRight = null;
            this.AdminFillProductType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.Lines = new string[0];
            this.AdminFillProductType.Location = new System.Drawing.Point(716, 159);
            this.AdminFillProductType.MaxLength = 32767;
            this.AdminFillProductType.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductType.Modified = false;
            this.AdminFillProductType.Multiline = false;
            this.AdminFillProductType.Name = "AdminFillProductType";
            stateProperties13.BorderColor = System.Drawing.Color.Transparent;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Transparent;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductType.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnIdleState = stateProperties16;
            this.AdminFillProductType.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductType.PasswordChar = '\0';
            this.AdminFillProductType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductType.PlaceholderText = "Fill your Product\'s  Type\r\n";
            this.AdminFillProductType.ReadOnly = false;
            this.AdminFillProductType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductType.SelectedText = "";
            this.AdminFillProductType.SelectionLength = 0;
            this.AdminFillProductType.SelectionStart = 0;
            this.AdminFillProductType.ShortcutsEnabled = true;
            this.AdminFillProductType.Size = new System.Drawing.Size(330, 37);
            this.AdminFillProductType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductType.TabIndex = 50;
            this.AdminFillProductType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductType.TextMarginBottom = 0;
            this.AdminFillProductType.TextMarginLeft = 3;
            this.AdminFillProductType.TextMarginTop = 0;
            this.AdminFillProductType.TextPlaceholder = "Fill your Product\'s  Type\r\n";
            this.AdminFillProductType.UseSystemPasswordChar = false;
            this.AdminFillProductType.WordWrap = true;
            // 
            // AdminViewAllCustomer
            // 
            this.AdminViewAllCustomer.HideSelection = false;
            this.AdminViewAllCustomer.Location = new System.Drawing.Point(22, 22);
            this.AdminViewAllCustomer.Margin = new System.Windows.Forms.Padding(2);
            this.AdminViewAllCustomer.Name = "AdminViewAllCustomer";
            this.AdminViewAllCustomer.Size = new System.Drawing.Size(672, 616);
            this.AdminViewAllCustomer.TabIndex = 49;
            this.AdminViewAllCustomer.UseCompatibleStateImageBehavior = false;
            // 
            // AdminShowAllProduct
            // 
            this.AdminShowAllProduct.AllowAnimations = true;
            this.AdminShowAllProduct.AllowMouseEffects = true;
            this.AdminShowAllProduct.AllowToggling = false;
            this.AdminShowAllProduct.AnimationSpeed = 200;
            this.AdminShowAllProduct.AutoGenerateColors = false;
            this.AdminShowAllProduct.AutoRoundBorders = false;
            this.AdminShowAllProduct.AutoSizeLeftIcon = true;
            this.AdminShowAllProduct.AutoSizeRightIcon = true;
            this.AdminShowAllProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowAllProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminShowAllProduct.BackgroundImage")));
            this.AdminShowAllProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllProduct.ButtonText = "VIEW ALL YOUR PRODUCTS";
            this.AdminShowAllProduct.ButtonTextMarginLeft = 0;
            this.AdminShowAllProduct.ColorContrastOnClick = 45;
            this.AdminShowAllProduct.ColorContrastOnHover = 45;
            this.AdminShowAllProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AdminShowAllProduct.CustomizableEdges = borderEdges4;
            this.AdminShowAllProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminShowAllProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminShowAllProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowAllProduct.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminShowAllProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminShowAllProduct.IconMarginLeft = 11;
            this.AdminShowAllProduct.IconPadding = 10;
            this.AdminShowAllProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminShowAllProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminShowAllProduct.IconSize = 25;
            this.AdminShowAllProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.IdleBorderRadius = 37;
            this.AdminShowAllProduct.IdleBorderThickness = 1;
            this.AdminShowAllProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.IdleIconLeftImage = null;
            this.AdminShowAllProduct.IdleIconRightImage = null;
            this.AdminShowAllProduct.IndicateFocus = false;
            this.AdminShowAllProduct.Location = new System.Drawing.Point(22, 647);
            this.AdminShowAllProduct.Name = "AdminShowAllProduct";
            this.AdminShowAllProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllProduct.OnDisabledState.BorderRadius = 37;
            this.AdminShowAllProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllProduct.OnDisabledState.BorderThickness = 1;
            this.AdminShowAllProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllProduct.OnDisabledState.IconLeftImage = null;
            this.AdminShowAllProduct.OnDisabledState.IconRightImage = null;
            this.AdminShowAllProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.onHoverState.BorderRadius = 37;
            this.AdminShowAllProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllProduct.onHoverState.BorderThickness = 1;
            this.AdminShowAllProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminShowAllProduct.onHoverState.IconLeftImage = null;
            this.AdminShowAllProduct.onHoverState.IconRightImage = null;
            this.AdminShowAllProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.OnIdleState.BorderRadius = 37;
            this.AdminShowAllProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllProduct.OnIdleState.BorderThickness = 1;
            this.AdminShowAllProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllProduct.OnIdleState.IconLeftImage = null;
            this.AdminShowAllProduct.OnIdleState.IconRightImage = null;
            this.AdminShowAllProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.OnPressedState.BorderRadius = 37;
            this.AdminShowAllProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllProduct.OnPressedState.BorderThickness = 1;
            this.AdminShowAllProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllProduct.OnPressedState.IconLeftImage = null;
            this.AdminShowAllProduct.OnPressedState.IconRightImage = null;
            this.AdminShowAllProduct.Size = new System.Drawing.Size(214, 36);
            this.AdminShowAllProduct.TabIndex = 48;
            this.AdminShowAllProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminShowAllProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminShowAllProduct.TextMarginLeft = 0;
            this.AdminShowAllProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminShowAllProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillProductName
            // 
            this.AdminFillProductName.AcceptsReturn = false;
            this.AdminFillProductName.AcceptsTab = false;
            this.AdminFillProductName.AnimationSpeed = 200;
            this.AdminFillProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductName.BackgroundImage")));
            this.AdminFillProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductName.BorderRadius = 1;
            this.AdminFillProductName.BorderThickness = 1;
            this.AdminFillProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductName.DefaultText = "";
            this.AdminFillProductName.FillColor = System.Drawing.Color.White;
            this.AdminFillProductName.HideSelection = true;
            this.AdminFillProductName.IconLeft = null;
            this.AdminFillProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.IconPadding = 10;
            this.AdminFillProductName.IconRight = null;
            this.AdminFillProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.Lines = new string[0];
            this.AdminFillProductName.Location = new System.Drawing.Point(716, 39);
            this.AdminFillProductName.MaxLength = 32767;
            this.AdminFillProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductName.Modified = false;
            this.AdminFillProductName.Multiline = false;
            this.AdminFillProductName.Name = "AdminFillProductName";
            stateProperties17.BorderColor = System.Drawing.Color.Transparent;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Transparent;
            stateProperties18.FillColor = System.Drawing.Color.Transparent;
            stateProperties18.ForeColor = System.Drawing.Color.Transparent;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Transparent;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnIdleState = stateProperties20;
            this.AdminFillProductName.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductName.PasswordChar = '\0';
            this.AdminFillProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductName.PlaceholderText = "Fill your Product\'s Name\r\n";
            this.AdminFillProductName.ReadOnly = false;
            this.AdminFillProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductName.SelectedText = "";
            this.AdminFillProductName.SelectionLength = 0;
            this.AdminFillProductName.SelectionStart = 0;
            this.AdminFillProductName.ShortcutsEnabled = true;
            this.AdminFillProductName.Size = new System.Drawing.Size(330, 37);
            this.AdminFillProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductName.TabIndex = 47;
            this.AdminFillProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductName.TextMarginBottom = 0;
            this.AdminFillProductName.TextMarginLeft = 3;
            this.AdminFillProductName.TextMarginTop = 0;
            this.AdminFillProductName.TextPlaceholder = "Fill your Product\'s Name\r\n";
            this.AdminFillProductName.UseSystemPasswordChar = false;
            this.AdminFillProductName.WordWrap = true;
            // 
            // AdminCheckProduct
            // 
            this.AdminCheckProduct.AllowAnimations = true;
            this.AdminCheckProduct.AllowMouseEffects = true;
            this.AdminCheckProduct.AllowToggling = false;
            this.AdminCheckProduct.AnimationSpeed = 200;
            this.AdminCheckProduct.AutoGenerateColors = false;
            this.AdminCheckProduct.AutoRoundBorders = false;
            this.AdminCheckProduct.AutoSizeLeftIcon = true;
            this.AdminCheckProduct.AutoSizeRightIcon = true;
            this.AdminCheckProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckProduct.BackgroundImage")));
            this.AdminCheckProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.ButtonText = "CHECK";
            this.AdminCheckProduct.ButtonTextMarginLeft = 0;
            this.AdminCheckProduct.ColorContrastOnClick = 45;
            this.AdminCheckProduct.ColorContrastOnHover = 45;
            this.AdminCheckProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminCheckProduct.CustomizableEdges = borderEdges5;
            this.AdminCheckProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckProduct.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckProduct.IconMarginLeft = 11;
            this.AdminCheckProduct.IconPadding = 10;
            this.AdminCheckProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckProduct.IconSize = 25;
            this.AdminCheckProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.IdleBorderRadius = 37;
            this.AdminCheckProduct.IdleBorderThickness = 1;
            this.AdminCheckProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.IdleIconLeftImage = null;
            this.AdminCheckProduct.IdleIconRightImage = null;
            this.AdminCheckProduct.IndicateFocus = false;
            this.AdminCheckProduct.Location = new System.Drawing.Point(716, 96);
            this.AdminCheckProduct.Name = "AdminCheckProduct";
            this.AdminCheckProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckProduct.OnDisabledState.BorderRadius = 37;
            this.AdminCheckProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnDisabledState.BorderThickness = 1;
            this.AdminCheckProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckProduct.OnDisabledState.IconLeftImage = null;
            this.AdminCheckProduct.OnDisabledState.IconRightImage = null;
            this.AdminCheckProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.onHoverState.BorderRadius = 37;
            this.AdminCheckProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.onHoverState.BorderThickness = 1;
            this.AdminCheckProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckProduct.onHoverState.IconLeftImage = null;
            this.AdminCheckProduct.onHoverState.IconRightImage = null;
            this.AdminCheckProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnIdleState.BorderRadius = 37;
            this.AdminCheckProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnIdleState.BorderThickness = 1;
            this.AdminCheckProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.OnIdleState.IconLeftImage = null;
            this.AdminCheckProduct.OnIdleState.IconRightImage = null;
            this.AdminCheckProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnPressedState.BorderRadius = 37;
            this.AdminCheckProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnPressedState.BorderThickness = 1;
            this.AdminCheckProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.OnPressedState.IconLeftImage = null;
            this.AdminCheckProduct.OnPressedState.IconRightImage = null;
            this.AdminCheckProduct.Size = new System.Drawing.Size(330, 36);
            this.AdminCheckProduct.TabIndex = 46;
            this.AdminCheckProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckProduct.TextMarginLeft = 0;
            this.AdminCheckProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.AdminUpdateProduct);
            this.Controls.Add(this.AdminDeleteProduct);
            this.Controls.Add(this.AdminAddProduct);
            this.Controls.Add(this.AdminFillEmployeeGender);
            this.Controls.Add(this.AdminFillProductPrice);
            this.Controls.Add(this.AdminFillProductAvailable);
            this.Controls.Add(this.AdminFillProductType);
            this.Controls.Add(this.AdminViewAllCustomer);
            this.Controls.Add(this.AdminShowAllProduct);
            this.Controls.Add(this.AdminFillProductName);
            this.Controls.Add(this.AdminCheckProduct);
            this.Name = "AdminProduct";
            this.Size = new System.Drawing.Size(1069, 705);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddProduct;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillEmployeeGender;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductPrice;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductAvailable;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductType;
        private System.Windows.Forms.ListView AdminViewAllCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminShowAllProduct;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckProduct;
    }
}
