namespace UI
{
    partial class AdminCustomer
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminCustomer));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.AdminShowRating = new Bunifu.UI.WinForms.BunifuRating();
            this.AdminShowAllCustomers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillCustomerName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillCustomerDateOfBirth = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCustomerUserName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCustomerEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCustomerPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCustomerAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillCustomerGender = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminAddCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminUpdateCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // AdminShowRating
            // 
            this.AdminShowRating.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowRating.DisabledEmptyFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(212)))), ((int)(((byte)(212)))));
            this.AdminShowRating.DisabledRatedFillColor = System.Drawing.Color.DarkGray;
            this.AdminShowRating.EmptyBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(212)))), ((int)(((byte)(212)))));
            this.AdminShowRating.EmptyFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(212)))), ((int)(((byte)(212)))));
            this.AdminShowRating.Font = new System.Drawing.Font("Century Gothic", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowRating.HoverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(217)))), ((int)(((byte)(20)))));
            this.AdminShowRating.HoverFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(217)))), ((int)(((byte)(20)))));
            this.AdminShowRating.InnerRadius = 2F;
            this.AdminShowRating.Location = new System.Drawing.Point(860, 960);
            this.AdminShowRating.Name = "AdminShowRating";
            this.AdminShowRating.OuterRadius = 10F;
            this.AdminShowRating.RatedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(217)))), ((int)(((byte)(20)))));
            this.AdminShowRating.RatedFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(217)))), ((int)(((byte)(20)))));
            this.AdminShowRating.ReadOnly = false;
            this.AdminShowRating.RightClickToClear = true;
            this.AdminShowRating.Size = new System.Drawing.Size(121, 22);
            this.AdminShowRating.TabIndex = 20;
            this.AdminShowRating.Text = "bunifuRating1";
            this.AdminShowRating.Value = 2;
            // 
            // AdminShowAllCustomers
            // 
            this.AdminShowAllCustomers.AllowAnimations = true;
            this.AdminShowAllCustomers.AllowMouseEffects = true;
            this.AdminShowAllCustomers.AllowToggling = false;
            this.AdminShowAllCustomers.AnimationSpeed = 200;
            this.AdminShowAllCustomers.AutoGenerateColors = false;
            this.AdminShowAllCustomers.AutoRoundBorders = false;
            this.AdminShowAllCustomers.AutoSizeLeftIcon = true;
            this.AdminShowAllCustomers.AutoSizeRightIcon = true;
            this.AdminShowAllCustomers.BackColor = System.Drawing.Color.Transparent;
            this.AdminShowAllCustomers.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminShowAllCustomers.BackgroundImage")));
            this.AdminShowAllCustomers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCustomers.ButtonText = "VIEW ALL YOUR CUSTOMERS";
            this.AdminShowAllCustomers.ButtonTextMarginLeft = 0;
            this.AdminShowAllCustomers.ColorContrastOnClick = 45;
            this.AdminShowAllCustomers.ColorContrastOnHover = 45;
            this.AdminShowAllCustomers.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.AdminShowAllCustomers.CustomizableEdges = borderEdges9;
            this.AdminShowAllCustomers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminShowAllCustomers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllCustomers.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllCustomers.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllCustomers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminShowAllCustomers.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminShowAllCustomers.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCustomers.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminShowAllCustomers.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllCustomers.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminShowAllCustomers.IconMarginLeft = 11;
            this.AdminShowAllCustomers.IconPadding = 10;
            this.AdminShowAllCustomers.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminShowAllCustomers.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminShowAllCustomers.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminShowAllCustomers.IconSize = 25;
            this.AdminShowAllCustomers.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.IdleBorderRadius = 37;
            this.AdminShowAllCustomers.IdleBorderThickness = 1;
            this.AdminShowAllCustomers.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.IdleIconLeftImage = null;
            this.AdminShowAllCustomers.IdleIconRightImage = null;
            this.AdminShowAllCustomers.IndicateFocus = false;
            this.AdminShowAllCustomers.Location = new System.Drawing.Point(33, 960);
            this.AdminShowAllCustomers.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminShowAllCustomers.Name = "AdminShowAllCustomers";
            this.AdminShowAllCustomers.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminShowAllCustomers.OnDisabledState.BorderRadius = 37;
            this.AdminShowAllCustomers.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCustomers.OnDisabledState.BorderThickness = 1;
            this.AdminShowAllCustomers.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminShowAllCustomers.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminShowAllCustomers.OnDisabledState.IconLeftImage = null;
            this.AdminShowAllCustomers.OnDisabledState.IconRightImage = null;
            this.AdminShowAllCustomers.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.onHoverState.BorderRadius = 37;
            this.AdminShowAllCustomers.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCustomers.onHoverState.BorderThickness = 1;
            this.AdminShowAllCustomers.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminShowAllCustomers.onHoverState.IconLeftImage = null;
            this.AdminShowAllCustomers.onHoverState.IconRightImage = null;
            this.AdminShowAllCustomers.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.OnIdleState.BorderRadius = 37;
            this.AdminShowAllCustomers.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCustomers.OnIdleState.BorderThickness = 1;
            this.AdminShowAllCustomers.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCustomers.OnIdleState.IconLeftImage = null;
            this.AdminShowAllCustomers.OnIdleState.IconRightImage = null;
            this.AdminShowAllCustomers.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.OnPressedState.BorderRadius = 37;
            this.AdminShowAllCustomers.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminShowAllCustomers.OnPressedState.BorderThickness = 1;
            this.AdminShowAllCustomers.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminShowAllCustomers.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminShowAllCustomers.OnPressedState.IconLeftImage = null;
            this.AdminShowAllCustomers.OnPressedState.IconRightImage = null;
            this.AdminShowAllCustomers.Size = new System.Drawing.Size(321, 54);
            this.AdminShowAllCustomers.TabIndex = 19;
            this.AdminShowAllCustomers.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminShowAllCustomers.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminShowAllCustomers.TextMarginLeft = 0;
            this.AdminShowAllCustomers.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminShowAllCustomers.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillCustomerName
            // 
            this.AdminFillCustomerName.AcceptsReturn = false;
            this.AdminFillCustomerName.AcceptsTab = false;
            this.AdminFillCustomerName.AnimationSpeed = 200;
            this.AdminFillCustomerName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerName.BackgroundImage")));
            this.AdminFillCustomerName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerName.BorderRadius = 1;
            this.AdminFillCustomerName.BorderThickness = 1;
            this.AdminFillCustomerName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerName.DefaultText = "";
            this.AdminFillCustomerName.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerName.HideSelection = true;
            this.AdminFillCustomerName.IconLeft = null;
            this.AdminFillCustomerName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerName.IconPadding = 10;
            this.AdminFillCustomerName.IconRight = null;
            this.AdminFillCustomerName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerName.Lines = new string[0];
            this.AdminFillCustomerName.Location = new System.Drawing.Point(1074, 48);
            this.AdminFillCustomerName.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerName.MaxLength = 32767;
            this.AdminFillCustomerName.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerName.Modified = false;
            this.AdminFillCustomerName.Multiline = false;
            this.AdminFillCustomerName.Name = "AdminFillCustomerName";
            stateProperties53.BorderColor = System.Drawing.Color.Transparent;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerName.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.Transparent;
            stateProperties54.FillColor = System.Drawing.Color.Transparent;
            stateProperties54.ForeColor = System.Drawing.Color.Transparent;
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerName.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.Transparent;
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerName.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerName.OnIdleState = stateProperties56;
            this.AdminFillCustomerName.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerName.PasswordChar = '\0';
            this.AdminFillCustomerName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerName.PlaceholderText = "Fill your Customer\'s Name";
            this.AdminFillCustomerName.ReadOnly = false;
            this.AdminFillCustomerName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerName.SelectedText = "";
            this.AdminFillCustomerName.SelectionLength = 0;
            this.AdminFillCustomerName.SelectionStart = 0;
            this.AdminFillCustomerName.ShortcutsEnabled = true;
            this.AdminFillCustomerName.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerName.TabIndex = 18;
            this.AdminFillCustomerName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerName.TextMarginBottom = 0;
            this.AdminFillCustomerName.TextMarginLeft = 3;
            this.AdminFillCustomerName.TextMarginTop = 0;
            this.AdminFillCustomerName.TextPlaceholder = "Fill your Customer\'s Name";
            this.AdminFillCustomerName.UseSystemPasswordChar = false;
            this.AdminFillCustomerName.WordWrap = true;
            // 
            // AdminCheckCustomer
            // 
            this.AdminCheckCustomer.AllowAnimations = true;
            this.AdminCheckCustomer.AllowMouseEffects = true;
            this.AdminCheckCustomer.AllowToggling = false;
            this.AdminCheckCustomer.AnimationSpeed = 200;
            this.AdminCheckCustomer.AutoGenerateColors = false;
            this.AdminCheckCustomer.AutoRoundBorders = false;
            this.AdminCheckCustomer.AutoSizeLeftIcon = true;
            this.AdminCheckCustomer.AutoSizeRightIcon = true;
            this.AdminCheckCustomer.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckCustomer.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckCustomer.BackgroundImage")));
            this.AdminCheckCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCustomer.ButtonText = "CHECK";
            this.AdminCheckCustomer.ButtonTextMarginLeft = 0;
            this.AdminCheckCustomer.ColorContrastOnClick = 45;
            this.AdminCheckCustomer.ColorContrastOnHover = 45;
            this.AdminCheckCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.AdminCheckCustomer.CustomizableEdges = borderEdges10;
            this.AdminCheckCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckCustomer.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckCustomer.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckCustomer.IconMarginLeft = 11;
            this.AdminCheckCustomer.IconPadding = 10;
            this.AdminCheckCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckCustomer.IconSize = 25;
            this.AdminCheckCustomer.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.IdleBorderRadius = 37;
            this.AdminCheckCustomer.IdleBorderThickness = 1;
            this.AdminCheckCustomer.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.IdleIconLeftImage = null;
            this.AdminCheckCustomer.IdleIconRightImage = null;
            this.AdminCheckCustomer.IndicateFocus = false;
            this.AdminCheckCustomer.Location = new System.Drawing.Point(1074, 144);
            this.AdminCheckCustomer.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminCheckCustomer.Name = "AdminCheckCustomer";
            this.AdminCheckCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckCustomer.OnDisabledState.BorderRadius = 37;
            this.AdminCheckCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCustomer.OnDisabledState.BorderThickness = 1;
            this.AdminCheckCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckCustomer.OnDisabledState.IconLeftImage = null;
            this.AdminCheckCustomer.OnDisabledState.IconRightImage = null;
            this.AdminCheckCustomer.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.onHoverState.BorderRadius = 37;
            this.AdminCheckCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCustomer.onHoverState.BorderThickness = 1;
            this.AdminCheckCustomer.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckCustomer.onHoverState.IconLeftImage = null;
            this.AdminCheckCustomer.onHoverState.IconRightImage = null;
            this.AdminCheckCustomer.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.OnIdleState.BorderRadius = 37;
            this.AdminCheckCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCustomer.OnIdleState.BorderThickness = 1;
            this.AdminCheckCustomer.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCustomer.OnIdleState.IconLeftImage = null;
            this.AdminCheckCustomer.OnIdleState.IconRightImage = null;
            this.AdminCheckCustomer.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.OnPressedState.BorderRadius = 37;
            this.AdminCheckCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckCustomer.OnPressedState.BorderThickness = 1;
            this.AdminCheckCustomer.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckCustomer.OnPressedState.IconLeftImage = null;
            this.AdminCheckCustomer.OnPressedState.IconRightImage = null;
            this.AdminCheckCustomer.Size = new System.Drawing.Size(495, 54);
            this.AdminCheckCustomer.TabIndex = 17;
            this.AdminCheckCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckCustomer.TextMarginLeft = 0;
            this.AdminCheckCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckCustomer.UseDefaultRadiusAndThickness = true;
            this.AdminCheckCustomer.Click += new System.EventHandler(this.AdminCheckCustomer_Click);
            // 
            // AdminFillCustomerDateOfBirth
            // 
            this.AdminFillCustomerDateOfBirth.AcceptsReturn = false;
            this.AdminFillCustomerDateOfBirth.AcceptsTab = false;
            this.AdminFillCustomerDateOfBirth.AnimationSpeed = 200;
            this.AdminFillCustomerDateOfBirth.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerDateOfBirth.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerDateOfBirth.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerDateOfBirth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerDateOfBirth.BackgroundImage")));
            this.AdminFillCustomerDateOfBirth.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerDateOfBirth.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerDateOfBirth.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerDateOfBirth.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerDateOfBirth.BorderRadius = 1;
            this.AdminFillCustomerDateOfBirth.BorderThickness = 1;
            this.AdminFillCustomerDateOfBirth.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerDateOfBirth.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerDateOfBirth.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerDateOfBirth.DefaultText = "";
            this.AdminFillCustomerDateOfBirth.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerDateOfBirth.HideSelection = true;
            this.AdminFillCustomerDateOfBirth.IconLeft = null;
            this.AdminFillCustomerDateOfBirth.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerDateOfBirth.IconPadding = 10;
            this.AdminFillCustomerDateOfBirth.IconRight = null;
            this.AdminFillCustomerDateOfBirth.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerDateOfBirth.Lines = new string[0];
            this.AdminFillCustomerDateOfBirth.Location = new System.Drawing.Point(1074, 244);
            this.AdminFillCustomerDateOfBirth.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerDateOfBirth.MaxLength = 32767;
            this.AdminFillCustomerDateOfBirth.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerDateOfBirth.Modified = false;
            this.AdminFillCustomerDateOfBirth.Multiline = false;
            this.AdminFillCustomerDateOfBirth.Name = "AdminFillCustomerDateOfBirth";
            stateProperties49.BorderColor = System.Drawing.Color.Transparent;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerDateOfBirth.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.Transparent;
            stateProperties50.FillColor = System.Drawing.Color.Transparent;
            stateProperties50.ForeColor = System.Drawing.Color.Transparent;
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerDateOfBirth.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.Transparent;
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerDateOfBirth.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerDateOfBirth.OnIdleState = stateProperties52;
            this.AdminFillCustomerDateOfBirth.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerDateOfBirth.PasswordChar = '\0';
            this.AdminFillCustomerDateOfBirth.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerDateOfBirth.PlaceholderText = "Fill your Customer\'s  Date Of Birth";
            this.AdminFillCustomerDateOfBirth.ReadOnly = false;
            this.AdminFillCustomerDateOfBirth.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerDateOfBirth.SelectedText = "";
            this.AdminFillCustomerDateOfBirth.SelectionLength = 0;
            this.AdminFillCustomerDateOfBirth.SelectionStart = 0;
            this.AdminFillCustomerDateOfBirth.ShortcutsEnabled = true;
            this.AdminFillCustomerDateOfBirth.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerDateOfBirth.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerDateOfBirth.TabIndex = 22;
            this.AdminFillCustomerDateOfBirth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerDateOfBirth.TextMarginBottom = 0;
            this.AdminFillCustomerDateOfBirth.TextMarginLeft = 3;
            this.AdminFillCustomerDateOfBirth.TextMarginTop = 0;
            this.AdminFillCustomerDateOfBirth.TextPlaceholder = "Fill your Customer\'s  Date Of Birth";
            this.AdminFillCustomerDateOfBirth.UseSystemPasswordChar = false;
            this.AdminFillCustomerDateOfBirth.WordWrap = true;
            // 
            // AdminFillCustomerUserName
            // 
            this.AdminFillCustomerUserName.AcceptsReturn = false;
            this.AdminFillCustomerUserName.AcceptsTab = false;
            this.AdminFillCustomerUserName.AnimationSpeed = 200;
            this.AdminFillCustomerUserName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerUserName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerUserName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerUserName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerUserName.BackgroundImage")));
            this.AdminFillCustomerUserName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerUserName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerUserName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerUserName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerUserName.BorderRadius = 1;
            this.AdminFillCustomerUserName.BorderThickness = 1;
            this.AdminFillCustomerUserName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerUserName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerUserName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerUserName.DefaultText = "";
            this.AdminFillCustomerUserName.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerUserName.HideSelection = true;
            this.AdminFillCustomerUserName.IconLeft = null;
            this.AdminFillCustomerUserName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerUserName.IconPadding = 10;
            this.AdminFillCustomerUserName.IconRight = null;
            this.AdminFillCustomerUserName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerUserName.Lines = new string[0];
            this.AdminFillCustomerUserName.Location = new System.Drawing.Point(1074, 728);
            this.AdminFillCustomerUserName.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerUserName.MaxLength = 32767;
            this.AdminFillCustomerUserName.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerUserName.Modified = false;
            this.AdminFillCustomerUserName.Multiline = false;
            this.AdminFillCustomerUserName.Name = "AdminFillCustomerUserName";
            stateProperties45.BorderColor = System.Drawing.Color.Transparent;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerUserName.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Transparent;
            stateProperties46.FillColor = System.Drawing.Color.Transparent;
            stateProperties46.ForeColor = System.Drawing.Color.Transparent;
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerUserName.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.Transparent;
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerUserName.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerUserName.OnIdleState = stateProperties48;
            this.AdminFillCustomerUserName.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerUserName.PasswordChar = '\0';
            this.AdminFillCustomerUserName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerUserName.PlaceholderText = "Fill your Customer\'s User Name";
            this.AdminFillCustomerUserName.ReadOnly = false;
            this.AdminFillCustomerUserName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerUserName.SelectedText = "";
            this.AdminFillCustomerUserName.SelectionLength = 0;
            this.AdminFillCustomerUserName.SelectionStart = 0;
            this.AdminFillCustomerUserName.ShortcutsEnabled = true;
            this.AdminFillCustomerUserName.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerUserName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerUserName.TabIndex = 23;
            this.AdminFillCustomerUserName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerUserName.TextMarginBottom = 0;
            this.AdminFillCustomerUserName.TextMarginLeft = 3;
            this.AdminFillCustomerUserName.TextMarginTop = 0;
            this.AdminFillCustomerUserName.TextPlaceholder = "Fill your Customer\'s User Name";
            this.AdminFillCustomerUserName.UseSystemPasswordChar = false;
            this.AdminFillCustomerUserName.WordWrap = true;
            // 
            // AdminFillCustomerEmail
            // 
            this.AdminFillCustomerEmail.AcceptsReturn = false;
            this.AdminFillCustomerEmail.AcceptsTab = false;
            this.AdminFillCustomerEmail.AnimationSpeed = 200;
            this.AdminFillCustomerEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerEmail.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerEmail.BackgroundImage")));
            this.AdminFillCustomerEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerEmail.BorderRadius = 1;
            this.AdminFillCustomerEmail.BorderThickness = 1;
            this.AdminFillCustomerEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerEmail.DefaultText = "";
            this.AdminFillCustomerEmail.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerEmail.HideSelection = true;
            this.AdminFillCustomerEmail.IconLeft = null;
            this.AdminFillCustomerEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerEmail.IconPadding = 10;
            this.AdminFillCustomerEmail.IconRight = null;
            this.AdminFillCustomerEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerEmail.Lines = new string[0];
            this.AdminFillCustomerEmail.Location = new System.Drawing.Point(1074, 640);
            this.AdminFillCustomerEmail.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerEmail.MaxLength = 32767;
            this.AdminFillCustomerEmail.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerEmail.Modified = false;
            this.AdminFillCustomerEmail.Multiline = false;
            this.AdminFillCustomerEmail.Name = "AdminFillCustomerEmail";
            stateProperties41.BorderColor = System.Drawing.Color.Transparent;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerEmail.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Transparent;
            stateProperties42.FillColor = System.Drawing.Color.Transparent;
            stateProperties42.ForeColor = System.Drawing.Color.Transparent;
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerEmail.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.Transparent;
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerEmail.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerEmail.OnIdleState = stateProperties44;
            this.AdminFillCustomerEmail.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerEmail.PasswordChar = '\0';
            this.AdminFillCustomerEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerEmail.PlaceholderText = "Fill your Customer\'s Emai";
            this.AdminFillCustomerEmail.ReadOnly = false;
            this.AdminFillCustomerEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerEmail.SelectedText = "";
            this.AdminFillCustomerEmail.SelectionLength = 0;
            this.AdminFillCustomerEmail.SelectionStart = 0;
            this.AdminFillCustomerEmail.ShortcutsEnabled = true;
            this.AdminFillCustomerEmail.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerEmail.TabIndex = 24;
            this.AdminFillCustomerEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerEmail.TextMarginBottom = 0;
            this.AdminFillCustomerEmail.TextMarginLeft = 3;
            this.AdminFillCustomerEmail.TextMarginTop = 0;
            this.AdminFillCustomerEmail.TextPlaceholder = "Fill your Customer\'s Emai";
            this.AdminFillCustomerEmail.UseSystemPasswordChar = false;
            this.AdminFillCustomerEmail.WordWrap = true;
            // 
            // AdminFillCustomerPhoneNumber
            // 
            this.AdminFillCustomerPhoneNumber.AcceptsReturn = false;
            this.AdminFillCustomerPhoneNumber.AcceptsTab = false;
            this.AdminFillCustomerPhoneNumber.AnimationSpeed = 200;
            this.AdminFillCustomerPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerPhoneNumber.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerPhoneNumber.BackgroundImage")));
            this.AdminFillCustomerPhoneNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerPhoneNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerPhoneNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerPhoneNumber.BorderRadius = 1;
            this.AdminFillCustomerPhoneNumber.BorderThickness = 1;
            this.AdminFillCustomerPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerPhoneNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerPhoneNumber.DefaultText = "";
            this.AdminFillCustomerPhoneNumber.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerPhoneNumber.HideSelection = true;
            this.AdminFillCustomerPhoneNumber.IconLeft = null;
            this.AdminFillCustomerPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerPhoneNumber.IconPadding = 10;
            this.AdminFillCustomerPhoneNumber.IconRight = null;
            this.AdminFillCustomerPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerPhoneNumber.Lines = new string[0];
            this.AdminFillCustomerPhoneNumber.Location = new System.Drawing.Point(1074, 544);
            this.AdminFillCustomerPhoneNumber.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerPhoneNumber.MaxLength = 32767;
            this.AdminFillCustomerPhoneNumber.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerPhoneNumber.Modified = false;
            this.AdminFillCustomerPhoneNumber.Multiline = false;
            this.AdminFillCustomerPhoneNumber.Name = "AdminFillCustomerPhoneNumber";
            stateProperties37.BorderColor = System.Drawing.Color.Transparent;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerPhoneNumber.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Transparent;
            stateProperties38.FillColor = System.Drawing.Color.Transparent;
            stateProperties38.ForeColor = System.Drawing.Color.Transparent;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerPhoneNumber.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.Transparent;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerPhoneNumber.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerPhoneNumber.OnIdleState = stateProperties40;
            this.AdminFillCustomerPhoneNumber.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerPhoneNumber.PasswordChar = '\0';
            this.AdminFillCustomerPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerPhoneNumber.PlaceholderText = "Fill your Customer\'s Phone Number";
            this.AdminFillCustomerPhoneNumber.ReadOnly = false;
            this.AdminFillCustomerPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerPhoneNumber.SelectedText = "";
            this.AdminFillCustomerPhoneNumber.SelectionLength = 0;
            this.AdminFillCustomerPhoneNumber.SelectionStart = 0;
            this.AdminFillCustomerPhoneNumber.ShortcutsEnabled = true;
            this.AdminFillCustomerPhoneNumber.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerPhoneNumber.TabIndex = 25;
            this.AdminFillCustomerPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerPhoneNumber.TextMarginBottom = 0;
            this.AdminFillCustomerPhoneNumber.TextMarginLeft = 3;
            this.AdminFillCustomerPhoneNumber.TextMarginTop = 0;
            this.AdminFillCustomerPhoneNumber.TextPlaceholder = "Fill your Customer\'s Phone Number";
            this.AdminFillCustomerPhoneNumber.UseSystemPasswordChar = false;
            this.AdminFillCustomerPhoneNumber.WordWrap = true;
            // 
            // AdminFillCustomerAddress
            // 
            this.AdminFillCustomerAddress.AcceptsReturn = false;
            this.AdminFillCustomerAddress.AcceptsTab = false;
            this.AdminFillCustomerAddress.AnimationSpeed = 200;
            this.AdminFillCustomerAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerAddress.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerAddress.BackgroundImage")));
            this.AdminFillCustomerAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerAddress.BorderRadius = 1;
            this.AdminFillCustomerAddress.BorderThickness = 1;
            this.AdminFillCustomerAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerAddress.DefaultText = "";
            this.AdminFillCustomerAddress.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerAddress.HideSelection = true;
            this.AdminFillCustomerAddress.IconLeft = null;
            this.AdminFillCustomerAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerAddress.IconPadding = 10;
            this.AdminFillCustomerAddress.IconRight = null;
            this.AdminFillCustomerAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerAddress.Lines = new string[0];
            this.AdminFillCustomerAddress.Location = new System.Drawing.Point(1074, 446);
            this.AdminFillCustomerAddress.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerAddress.MaxLength = 32767;
            this.AdminFillCustomerAddress.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerAddress.Modified = false;
            this.AdminFillCustomerAddress.Multiline = false;
            this.AdminFillCustomerAddress.Name = "AdminFillCustomerAddress";
            stateProperties33.BorderColor = System.Drawing.Color.Transparent;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerAddress.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Transparent;
            stateProperties34.FillColor = System.Drawing.Color.Transparent;
            stateProperties34.ForeColor = System.Drawing.Color.Transparent;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerAddress.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Transparent;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerAddress.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerAddress.OnIdleState = stateProperties36;
            this.AdminFillCustomerAddress.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerAddress.PasswordChar = '\0';
            this.AdminFillCustomerAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerAddress.PlaceholderText = "Fill your Customer\'s Address";
            this.AdminFillCustomerAddress.ReadOnly = false;
            this.AdminFillCustomerAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerAddress.SelectedText = "";
            this.AdminFillCustomerAddress.SelectionLength = 0;
            this.AdminFillCustomerAddress.SelectionStart = 0;
            this.AdminFillCustomerAddress.ShortcutsEnabled = true;
            this.AdminFillCustomerAddress.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerAddress.TabIndex = 26;
            this.AdminFillCustomerAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerAddress.TextMarginBottom = 0;
            this.AdminFillCustomerAddress.TextMarginLeft = 3;
            this.AdminFillCustomerAddress.TextMarginTop = 0;
            this.AdminFillCustomerAddress.TextPlaceholder = "Fill your Customer\'s Address";
            this.AdminFillCustomerAddress.UseSystemPasswordChar = false;
            this.AdminFillCustomerAddress.WordWrap = true;
            // 
            // AdminFillCustomerGender
            // 
            this.AdminFillCustomerGender.AcceptsReturn = false;
            this.AdminFillCustomerGender.AcceptsTab = false;
            this.AdminFillCustomerGender.AnimationSpeed = 200;
            this.AdminFillCustomerGender.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillCustomerGender.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillCustomerGender.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillCustomerGender.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillCustomerGender.BackgroundImage")));
            this.AdminFillCustomerGender.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillCustomerGender.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillCustomerGender.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillCustomerGender.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillCustomerGender.BorderRadius = 1;
            this.AdminFillCustomerGender.BorderThickness = 1;
            this.AdminFillCustomerGender.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillCustomerGender.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerGender.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillCustomerGender.DefaultText = "";
            this.AdminFillCustomerGender.FillColor = System.Drawing.Color.White;
            this.AdminFillCustomerGender.HideSelection = true;
            this.AdminFillCustomerGender.IconLeft = null;
            this.AdminFillCustomerGender.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerGender.IconPadding = 10;
            this.AdminFillCustomerGender.IconRight = null;
            this.AdminFillCustomerGender.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillCustomerGender.Lines = new string[0];
            this.AdminFillCustomerGender.Location = new System.Drawing.Point(1074, 350);
            this.AdminFillCustomerGender.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerGender.MaxLength = 32767;
            this.AdminFillCustomerGender.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillCustomerGender.Modified = false;
            this.AdminFillCustomerGender.Multiline = false;
            this.AdminFillCustomerGender.Name = "AdminFillCustomerGender";
            stateProperties29.BorderColor = System.Drawing.Color.Transparent;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerGender.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Transparent;
            stateProperties30.FillColor = System.Drawing.Color.Transparent;
            stateProperties30.ForeColor = System.Drawing.Color.Transparent;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillCustomerGender.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Transparent;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerGender.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillCustomerGender.OnIdleState = stateProperties32;
            this.AdminFillCustomerGender.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminFillCustomerGender.PasswordChar = '\0';
            this.AdminFillCustomerGender.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillCustomerGender.PlaceholderText = "Fill your Customer\'s Gender";
            this.AdminFillCustomerGender.ReadOnly = false;
            this.AdminFillCustomerGender.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillCustomerGender.SelectedText = "";
            this.AdminFillCustomerGender.SelectionLength = 0;
            this.AdminFillCustomerGender.SelectionStart = 0;
            this.AdminFillCustomerGender.ShortcutsEnabled = true;
            this.AdminFillCustomerGender.Size = new System.Drawing.Size(495, 56);
            this.AdminFillCustomerGender.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillCustomerGender.TabIndex = 27;
            this.AdminFillCustomerGender.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillCustomerGender.TextMarginBottom = 0;
            this.AdminFillCustomerGender.TextMarginLeft = 3;
            this.AdminFillCustomerGender.TextMarginTop = 0;
            this.AdminFillCustomerGender.TextPlaceholder = "Fill your Customer\'s Gender";
            this.AdminFillCustomerGender.UseSystemPasswordChar = false;
            this.AdminFillCustomerGender.WordWrap = true;
            // 
            // AdminAddCustomer
            // 
            this.AdminAddCustomer.AllowAnimations = true;
            this.AdminAddCustomer.AllowMouseEffects = true;
            this.AdminAddCustomer.AllowToggling = false;
            this.AdminAddCustomer.AnimationSpeed = 200;
            this.AdminAddCustomer.AutoGenerateColors = false;
            this.AdminAddCustomer.AutoRoundBorders = false;
            this.AdminAddCustomer.AutoSizeLeftIcon = true;
            this.AdminAddCustomer.AutoSizeRightIcon = true;
            this.AdminAddCustomer.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddCustomer.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddCustomer.BackgroundImage")));
            this.AdminAddCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCustomer.ButtonText = "ADD";
            this.AdminAddCustomer.ButtonTextMarginLeft = 0;
            this.AdminAddCustomer.ColorContrastOnClick = 45;
            this.AdminAddCustomer.ColorContrastOnHover = 45;
            this.AdminAddCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.AdminAddCustomer.CustomizableEdges = borderEdges8;
            this.AdminAddCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddCustomer.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddCustomer.ForeColor = System.Drawing.Color.White;
            this.AdminAddCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddCustomer.IconMarginLeft = 11;
            this.AdminAddCustomer.IconPadding = 10;
            this.AdminAddCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddCustomer.IconSize = 25;
            this.AdminAddCustomer.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.IdleBorderRadius = 37;
            this.AdminAddCustomer.IdleBorderThickness = 1;
            this.AdminAddCustomer.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.IdleIconLeftImage = null;
            this.AdminAddCustomer.IdleIconRightImage = null;
            this.AdminAddCustomer.IndicateFocus = false;
            this.AdminAddCustomer.Location = new System.Drawing.Point(1074, 816);
            this.AdminAddCustomer.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminAddCustomer.Name = "AdminAddCustomer";
            this.AdminAddCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddCustomer.OnDisabledState.BorderRadius = 37;
            this.AdminAddCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCustomer.OnDisabledState.BorderThickness = 1;
            this.AdminAddCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddCustomer.OnDisabledState.IconLeftImage = null;
            this.AdminAddCustomer.OnDisabledState.IconRightImage = null;
            this.AdminAddCustomer.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.onHoverState.BorderRadius = 37;
            this.AdminAddCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCustomer.onHoverState.BorderThickness = 1;
            this.AdminAddCustomer.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddCustomer.onHoverState.IconLeftImage = null;
            this.AdminAddCustomer.onHoverState.IconRightImage = null;
            this.AdminAddCustomer.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.OnIdleState.BorderRadius = 37;
            this.AdminAddCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCustomer.OnIdleState.BorderThickness = 1;
            this.AdminAddCustomer.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddCustomer.OnIdleState.IconLeftImage = null;
            this.AdminAddCustomer.OnIdleState.IconRightImage = null;
            this.AdminAddCustomer.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.OnPressedState.BorderRadius = 37;
            this.AdminAddCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddCustomer.OnPressedState.BorderThickness = 1;
            this.AdminAddCustomer.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddCustomer.OnPressedState.IconLeftImage = null;
            this.AdminAddCustomer.OnPressedState.IconRightImage = null;
            this.AdminAddCustomer.Size = new System.Drawing.Size(240, 54);
            this.AdminAddCustomer.TabIndex = 28;
            this.AdminAddCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddCustomer.TextMarginLeft = 0;
            this.AdminAddCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddCustomer.UseDefaultRadiusAndThickness = true;
            this.AdminAddCustomer.Click += new System.EventHandler(this.AdminAddCustomer_Click);
            // 
            // AdminDeleteCustomer
            // 
            this.AdminDeleteCustomer.AllowAnimations = true;
            this.AdminDeleteCustomer.AllowMouseEffects = true;
            this.AdminDeleteCustomer.AllowToggling = false;
            this.AdminDeleteCustomer.AnimationSpeed = 200;
            this.AdminDeleteCustomer.AutoGenerateColors = false;
            this.AdminDeleteCustomer.AutoRoundBorders = false;
            this.AdminDeleteCustomer.AutoSizeLeftIcon = true;
            this.AdminDeleteCustomer.AutoSizeRightIcon = true;
            this.AdminDeleteCustomer.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteCustomer.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteCustomer.BackgroundImage")));
            this.AdminDeleteCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCustomer.ButtonText = "DELETE";
            this.AdminDeleteCustomer.ButtonTextMarginLeft = 0;
            this.AdminDeleteCustomer.ColorContrastOnClick = 45;
            this.AdminDeleteCustomer.ColorContrastOnHover = 45;
            this.AdminDeleteCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.AdminDeleteCustomer.CustomizableEdges = borderEdges7;
            this.AdminDeleteCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteCustomer.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteCustomer.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteCustomer.IconMarginLeft = 11;
            this.AdminDeleteCustomer.IconPadding = 10;
            this.AdminDeleteCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteCustomer.IconSize = 25;
            this.AdminDeleteCustomer.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.IdleBorderRadius = 37;
            this.AdminDeleteCustomer.IdleBorderThickness = 1;
            this.AdminDeleteCustomer.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.IdleIconLeftImage = null;
            this.AdminDeleteCustomer.IdleIconRightImage = null;
            this.AdminDeleteCustomer.IndicateFocus = false;
            this.AdminDeleteCustomer.Location = new System.Drawing.Point(1329, 816);
            this.AdminDeleteCustomer.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminDeleteCustomer.Name = "AdminDeleteCustomer";
            this.AdminDeleteCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteCustomer.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCustomer.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteCustomer.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteCustomer.OnDisabledState.IconRightImage = null;
            this.AdminDeleteCustomer.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.onHoverState.BorderRadius = 37;
            this.AdminDeleteCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCustomer.onHoverState.BorderThickness = 1;
            this.AdminDeleteCustomer.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteCustomer.onHoverState.IconLeftImage = null;
            this.AdminDeleteCustomer.onHoverState.IconRightImage = null;
            this.AdminDeleteCustomer.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.OnIdleState.BorderRadius = 37;
            this.AdminDeleteCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCustomer.OnIdleState.BorderThickness = 1;
            this.AdminDeleteCustomer.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCustomer.OnIdleState.IconLeftImage = null;
            this.AdminDeleteCustomer.OnIdleState.IconRightImage = null;
            this.AdminDeleteCustomer.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.OnPressedState.BorderRadius = 37;
            this.AdminDeleteCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteCustomer.OnPressedState.BorderThickness = 1;
            this.AdminDeleteCustomer.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteCustomer.OnPressedState.IconLeftImage = null;
            this.AdminDeleteCustomer.OnPressedState.IconRightImage = null;
            this.AdminDeleteCustomer.Size = new System.Drawing.Size(240, 54);
            this.AdminDeleteCustomer.TabIndex = 29;
            this.AdminDeleteCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteCustomer.TextMarginLeft = 0;
            this.AdminDeleteCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // AdminUpdateCustomer
            // 
            this.AdminUpdateCustomer.AllowAnimations = true;
            this.AdminUpdateCustomer.AllowMouseEffects = true;
            this.AdminUpdateCustomer.AllowToggling = false;
            this.AdminUpdateCustomer.AnimationSpeed = 200;
            this.AdminUpdateCustomer.AutoGenerateColors = false;
            this.AdminUpdateCustomer.AutoRoundBorders = false;
            this.AdminUpdateCustomer.AutoSizeLeftIcon = true;
            this.AdminUpdateCustomer.AutoSizeRightIcon = true;
            this.AdminUpdateCustomer.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateCustomer.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateCustomer.BackgroundImage")));
            this.AdminUpdateCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCustomer.ButtonText = "Update";
            this.AdminUpdateCustomer.ButtonTextMarginLeft = 0;
            this.AdminUpdateCustomer.ColorContrastOnClick = 45;
            this.AdminUpdateCustomer.ColorContrastOnHover = 45;
            this.AdminUpdateCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.AdminUpdateCustomer.CustomizableEdges = borderEdges6;
            this.AdminUpdateCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateCustomer.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateCustomer.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateCustomer.IconMarginLeft = 11;
            this.AdminUpdateCustomer.IconPadding = 10;
            this.AdminUpdateCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateCustomer.IconSize = 25;
            this.AdminUpdateCustomer.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.IdleBorderRadius = 37;
            this.AdminUpdateCustomer.IdleBorderThickness = 1;
            this.AdminUpdateCustomer.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.IdleIconLeftImage = null;
            this.AdminUpdateCustomer.IdleIconRightImage = null;
            this.AdminUpdateCustomer.IndicateFocus = false;
            this.AdminUpdateCustomer.Location = new System.Drawing.Point(1074, 892);
            this.AdminUpdateCustomer.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.AdminUpdateCustomer.Name = "AdminUpdateCustomer";
            this.AdminUpdateCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateCustomer.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCustomer.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateCustomer.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateCustomer.OnDisabledState.IconRightImage = null;
            this.AdminUpdateCustomer.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.onHoverState.BorderRadius = 37;
            this.AdminUpdateCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCustomer.onHoverState.BorderThickness = 1;
            this.AdminUpdateCustomer.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateCustomer.onHoverState.IconLeftImage = null;
            this.AdminUpdateCustomer.onHoverState.IconRightImage = null;
            this.AdminUpdateCustomer.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.OnIdleState.BorderRadius = 37;
            this.AdminUpdateCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCustomer.OnIdleState.BorderThickness = 1;
            this.AdminUpdateCustomer.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCustomer.OnIdleState.IconLeftImage = null;
            this.AdminUpdateCustomer.OnIdleState.IconRightImage = null;
            this.AdminUpdateCustomer.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.OnPressedState.BorderRadius = 37;
            this.AdminUpdateCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateCustomer.OnPressedState.BorderThickness = 1;
            this.AdminUpdateCustomer.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateCustomer.OnPressedState.IconLeftImage = null;
            this.AdminUpdateCustomer.OnPressedState.IconRightImage = null;
            this.AdminUpdateCustomer.Size = new System.Drawing.Size(495, 54);
            this.AdminUpdateCustomer.TabIndex = 30;
            this.AdminUpdateCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateCustomer.TextMarginLeft = 0;
            this.AdminUpdateCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // dataGridView1
            // 
            this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(46, 24);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersWidth = 62;
            this.dataGridView1.RowTemplate.Height = 28;
            this.dataGridView1.Size = new System.Drawing.Size(1006, 922);
            this.dataGridView1.TabIndex = 31;
            // 
            // AdminCustomer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(144F, 144F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.AdminUpdateCustomer);
            this.Controls.Add(this.AdminDeleteCustomer);
            this.Controls.Add(this.AdminAddCustomer);
            this.Controls.Add(this.AdminFillCustomerGender);
            this.Controls.Add(this.AdminFillCustomerAddress);
            this.Controls.Add(this.AdminFillCustomerPhoneNumber);
            this.Controls.Add(this.AdminFillCustomerEmail);
            this.Controls.Add(this.AdminFillCustomerUserName);
            this.Controls.Add(this.AdminFillCustomerDateOfBirth);
            this.Controls.Add(this.AdminShowRating);
            this.Controls.Add(this.AdminShowAllCustomers);
            this.Controls.Add(this.AdminFillCustomerName);
            this.Controls.Add(this.AdminCheckCustomer);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "AdminCustomer";
            this.Size = new System.Drawing.Size(1604, 1058);
            this.Load += new System.EventHandler(this.AdminCustomer_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuRating AdminShowRating;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminShowAllCustomers;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddCustomer;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerGender;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerAddress;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerPhoneNumber;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerEmail;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerUserName;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillCustomerDateOfBirth;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateCustomer;
        private System.Windows.Forms.DataGridView dataGridView1;
    }
}
