namespace UI
{
    partial class CatMng
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CatMng));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbIDCat = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbAvailable = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.tbCat_Name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UserView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbNameCat = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCheck = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.UserView)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel5.Location = new System.Drawing.Point(1191, 363);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(29, 21);
            this.bunifuLabel5.TabIndex = 166;
            this.bunifuLabel5.Text = "Giá:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel4.Location = new System.Drawing.Point(1188, 282);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(82, 21);
            this.bunifuLabel4.TabIndex = 165;
            this.bunifuLabel4.Text = "Trạng thái:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel2.Location = new System.Drawing.Point(1188, 199);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(70, 21);
            this.bunifuLabel2.TabIndex = 164;
            this.bunifuLabel2.Text = "Tên mèo:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel1.Location = new System.Drawing.Point(1188, 121);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(21, 21);
            this.bunifuLabel1.TabIndex = 163;
            this.bunifuLabel1.Text = "ID:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnRefresh
            // 
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowMouseEffects = true;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AnimationSpeed = 200;
            this.btnRefresh.AutoGenerateColors = false;
            this.btnRefresh.AutoRoundBorders = false;
            this.btnRefresh.AutoSizeLeftIcon = true;
            this.btnRefresh.AutoSizeRightIcon = true;
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnRefresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.BackgroundImage")));
            this.btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.ButtonText = "REFRESH";
            this.btnRefresh.ButtonTextMarginLeft = 0;
            this.btnRefresh.ColorContrastOnClick = 45;
            this.btnRefresh.ColorContrastOnHover = 45;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnRefresh.CustomizableEdges = borderEdges1;
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRefresh.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRefresh.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRefresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRefresh.IconMarginLeft = 11;
            this.btnRefresh.IconPadding = 10;
            this.btnRefresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRefresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRefresh.IconSize = 25;
            this.btnRefresh.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleBorderRadius = 40;
            this.btnRefresh.IdleBorderThickness = 1;
            this.btnRefresh.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleIconLeftImage = null;
            this.btnRefresh.IdleIconRightImage = null;
            this.btnRefresh.IndicateFocus = false;
            this.btnRefresh.Location = new System.Drawing.Point(462, 653);
            this.btnRefresh.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.OnDisabledState.BorderRadius = 40;
            this.btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnDisabledState.BorderThickness = 1;
            this.btnRefresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.OnDisabledState.IconLeftImage = null;
            this.btnRefresh.OnDisabledState.IconRightImage = null;
            this.btnRefresh.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.BorderRadius = 40;
            this.btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.onHoverState.BorderThickness = 1;
            this.btnRefresh.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRefresh.onHoverState.IconLeftImage = null;
            this.btnRefresh.onHoverState.IconRightImage = null;
            this.btnRefresh.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.BorderRadius = 40;
            this.btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnIdleState.BorderThickness = 1;
            this.btnRefresh.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnIdleState.IconLeftImage = null;
            this.btnRefresh.OnIdleState.IconRightImage = null;
            this.btnRefresh.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.BorderRadius = 40;
            this.btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnPressedState.BorderThickness = 1;
            this.btnRefresh.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnPressedState.IconLeftImage = null;
            this.btnRefresh.OnPressedState.IconRightImage = null;
            this.btnRefresh.Size = new System.Drawing.Size(108, 57);
            this.btnRefresh.TabIndex = 162;
            this.btnRefresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRefresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRefresh.TextMarginLeft = 0;
            this.btnRefresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.UseDefaultRadiusAndThickness = true;
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // txbIDCat
            // 
            this.txbIDCat.AcceptsReturn = false;
            this.txbIDCat.AcceptsTab = false;
            this.txbIDCat.AnimationSpeed = 200;
            this.txbIDCat.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbIDCat.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbIDCat.BackColor = System.Drawing.Color.White;
            this.txbIDCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbIDCat.BackgroundImage")));
            this.txbIDCat.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbIDCat.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbIDCat.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbIDCat.BorderColorIdle = System.Drawing.Color.Black;
            this.txbIDCat.BorderRadius = 30;
            this.txbIDCat.BorderThickness = 1;
            this.txbIDCat.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbIDCat.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbIDCat.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbIDCat.DefaultText = "";
            this.txbIDCat.FillColor = System.Drawing.Color.White;
            this.txbIDCat.HideSelection = true;
            this.txbIDCat.IconLeft = null;
            this.txbIDCat.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbIDCat.IconPadding = 10;
            this.txbIDCat.IconRight = null;
            this.txbIDCat.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbIDCat.Lines = new string[0];
            this.txbIDCat.Location = new System.Drawing.Point(1161, 133);
            this.txbIDCat.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbIDCat.MaxLength = 32767;
            this.txbIDCat.MinimumSize = new System.Drawing.Size(3, 2);
            this.txbIDCat.Modified = false;
            this.txbIDCat.Multiline = false;
            this.txbIDCat.Name = "txbIDCat";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbIDCat.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Black;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbIDCat.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbIDCat.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbIDCat.OnIdleState = stateProperties4;
            this.txbIDCat.Padding = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbIDCat.PasswordChar = '\0';
            this.txbIDCat.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbIDCat.PlaceholderText = "";
            this.txbIDCat.ReadOnly = false;
            this.txbIDCat.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbIDCat.SelectedText = "";
            this.txbIDCat.SelectionLength = 0;
            this.txbIDCat.SelectionStart = 0;
            this.txbIDCat.ShortcutsEnabled = true;
            this.txbIDCat.Size = new System.Drawing.Size(332, 47);
            this.txbIDCat.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbIDCat.TabIndex = 161;
            this.txbIDCat.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbIDCat.TextMarginBottom = 0;
            this.txbIDCat.TextMarginLeft = 3;
            this.txbIDCat.TextMarginTop = 0;
            this.txbIDCat.TextPlaceholder = "";
            this.txbIDCat.UseSystemPasswordChar = false;
            this.txbIDCat.WordWrap = true;
            // 
            // txbPrice
            // 
            this.txbPrice.AcceptsReturn = false;
            this.txbPrice.AcceptsTab = false;
            this.txbPrice.AnimationSpeed = 200;
            this.txbPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbPrice.BackColor = System.Drawing.Color.Transparent;
            this.txbPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbPrice.BackgroundImage")));
            this.txbPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbPrice.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbPrice.BorderColorIdle = System.Drawing.Color.Black;
            this.txbPrice.BorderRadius = 30;
            this.txbPrice.BorderThickness = 1;
            this.txbPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbPrice.DefaultText = "";
            this.txbPrice.FillColor = System.Drawing.Color.White;
            this.txbPrice.HideSelection = true;
            this.txbPrice.IconLeft = null;
            this.txbPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.IconPadding = 10;
            this.txbPrice.IconRight = null;
            this.txbPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.Lines = new string[0];
            this.txbPrice.Location = new System.Drawing.Point(1160, 374);
            this.txbPrice.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbPrice.MaxLength = 32767;
            this.txbPrice.MinimumSize = new System.Drawing.Size(3, 2);
            this.txbPrice.Modified = false;
            this.txbPrice.Multiline = false;
            this.txbPrice.Name = "txbPrice";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Black;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Black;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnIdleState = stateProperties8;
            this.txbPrice.Padding = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbPrice.PasswordChar = '\0';
            this.txbPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbPrice.PlaceholderText = "";
            this.txbPrice.ReadOnly = false;
            this.txbPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbPrice.SelectedText = "";
            this.txbPrice.SelectionLength = 0;
            this.txbPrice.SelectionStart = 0;
            this.txbPrice.ShortcutsEnabled = true;
            this.txbPrice.Size = new System.Drawing.Size(337, 47);
            this.txbPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbPrice.TabIndex = 160;
            this.txbPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbPrice.TextMarginBottom = 0;
            this.txbPrice.TextMarginLeft = 3;
            this.txbPrice.TextMarginTop = 0;
            this.txbPrice.TextPlaceholder = "";
            this.txbPrice.UseSystemPasswordChar = false;
            this.txbPrice.WordWrap = true;
            // 
            // txbAvailable
            // 
            this.txbAvailable.AcceptsReturn = false;
            this.txbAvailable.AcceptsTab = false;
            this.txbAvailable.AnimationSpeed = 200;
            this.txbAvailable.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbAvailable.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbAvailable.BackColor = System.Drawing.Color.Transparent;
            this.txbAvailable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbAvailable.BackgroundImage")));
            this.txbAvailable.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbAvailable.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbAvailable.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbAvailable.BorderColorIdle = System.Drawing.Color.Black;
            this.txbAvailable.BorderRadius = 30;
            this.txbAvailable.BorderThickness = 1;
            this.txbAvailable.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbAvailable.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbAvailable.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbAvailable.DefaultText = "";
            this.txbAvailable.FillColor = System.Drawing.Color.White;
            this.txbAvailable.HideSelection = true;
            this.txbAvailable.IconLeft = null;
            this.txbAvailable.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbAvailable.IconPadding = 10;
            this.txbAvailable.IconRight = null;
            this.txbAvailable.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbAvailable.Lines = new string[0];
            this.txbAvailable.Location = new System.Drawing.Point(1156, 293);
            this.txbAvailable.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbAvailable.MaxLength = 32767;
            this.txbAvailable.MinimumSize = new System.Drawing.Size(3, 2);
            this.txbAvailable.Modified = false;
            this.txbAvailable.Multiline = false;
            this.txbAvailable.Name = "txbAvailable";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbAvailable.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Black;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbAvailable.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbAvailable.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbAvailable.OnIdleState = stateProperties12;
            this.txbAvailable.Padding = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbAvailable.PasswordChar = '\0';
            this.txbAvailable.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbAvailable.PlaceholderText = "";
            this.txbAvailable.ReadOnly = false;
            this.txbAvailable.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbAvailable.SelectedText = "";
            this.txbAvailable.SelectionLength = 0;
            this.txbAvailable.SelectionStart = 0;
            this.txbAvailable.ShortcutsEnabled = true;
            this.txbAvailable.Size = new System.Drawing.Size(337, 47);
            this.txbAvailable.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbAvailable.TabIndex = 159;
            this.txbAvailable.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbAvailable.TextMarginBottom = 0;
            this.txbAvailable.TextMarginLeft = 3;
            this.txbAvailable.TextMarginTop = 0;
            this.txbAvailable.TextPlaceholder = "";
            this.txbAvailable.UseSystemPasswordChar = false;
            this.txbAvailable.WordWrap = true;
            // 
            // label1
            // 
            this.label1.ForeColor = System.Drawing.Color.Gray;
            this.label1.Location = new System.Drawing.Point(1157, 92);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(347, 25);
            this.label1.TabIndex = 158;
            this.label1.Text = resources.GetString("label1.Text");
            // 
            // tbCat_Name
            // 
            this.tbCat_Name.AcceptsReturn = false;
            this.tbCat_Name.AcceptsTab = false;
            this.tbCat_Name.AnimationSpeed = 200;
            this.tbCat_Name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbCat_Name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbCat_Name.BackColor = System.Drawing.Color.White;
            this.tbCat_Name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbCat_Name.BackgroundImage")));
            this.tbCat_Name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbCat_Name.BorderColorDisabled = System.Drawing.Color.Black;
            this.tbCat_Name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbCat_Name.BorderColorIdle = System.Drawing.Color.Black;
            this.tbCat_Name.BorderRadius = 35;
            this.tbCat_Name.BorderThickness = 1;
            this.tbCat_Name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbCat_Name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCat_Name.DefaultFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbCat_Name.DefaultText = "";
            this.tbCat_Name.FillColor = System.Drawing.Color.White;
            this.tbCat_Name.HideSelection = true;
            this.tbCat_Name.IconLeft = null;
            this.tbCat_Name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCat_Name.IconPadding = 10;
            this.tbCat_Name.IconRight = null;
            this.tbCat_Name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbCat_Name.Lines = new string[0];
            this.tbCat_Name.Location = new System.Drawing.Point(1156, 31);
            this.tbCat_Name.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.tbCat_Name.MaxLength = 32767;
            this.tbCat_Name.MinimumSize = new System.Drawing.Size(3, 2);
            this.tbCat_Name.Modified = false;
            this.tbCat_Name.Multiline = false;
            this.tbCat_Name.Name = "tbCat_Name";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCat_Name.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Black;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbCat_Name.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCat_Name.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbCat_Name.OnIdleState = stateProperties16;
            this.tbCat_Name.Padding = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.tbCat_Name.PasswordChar = '\0';
            this.tbCat_Name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbCat_Name.PlaceholderText = "Nhập tên mèo để tìm kiếm";
            this.tbCat_Name.ReadOnly = false;
            this.tbCat_Name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbCat_Name.SelectedText = "";
            this.tbCat_Name.SelectionLength = 0;
            this.tbCat_Name.SelectionStart = 0;
            this.tbCat_Name.ShortcutsEnabled = true;
            this.tbCat_Name.Size = new System.Drawing.Size(223, 57);
            this.tbCat_Name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbCat_Name.TabIndex = 157;
            this.tbCat_Name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbCat_Name.TextMarginBottom = 0;
            this.tbCat_Name.TextMarginLeft = 3;
            this.tbCat_Name.TextMarginTop = 0;
            this.tbCat_Name.TextPlaceholder = "Nhập tên mèo để tìm kiếm";
            this.tbCat_Name.UseSystemPasswordChar = false;
            this.tbCat_Name.WordWrap = true;
            // 
            // UserView
            // 
            this.UserView.AllowCustomTheming = false;
            this.UserView.AllowUserToAddRows = false;
            this.UserView.AllowUserToDeleteRows = false;
            this.UserView.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.UserView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.UserView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.UserView.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.UserView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.UserView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.UserView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.UserView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.UserView.ColumnHeadersHeight = 40;
            this.UserView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.UserView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.UserView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.UserView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.UserView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.UserView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.UserView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.UserView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.UserView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.UserView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.UserView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.UserView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.UserView.CurrentTheme.Name = null;
            this.UserView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.UserView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.UserView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.UserView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.UserView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.UserView.DefaultCellStyle = dataGridViewCellStyle3;
            this.UserView.EnableHeadersVisualStyles = false;
            this.UserView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.UserView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.UserView.HeaderBgColor = System.Drawing.Color.Empty;
            this.UserView.HeaderForeColor = System.Drawing.Color.White;
            this.UserView.Location = new System.Drawing.Point(41, 43);
            this.UserView.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.UserView.Name = "UserView";
            this.UserView.ReadOnly = true;
            this.UserView.RowHeadersVisible = false;
            this.UserView.RowHeadersWidth = 62;
            this.UserView.RowTemplate.Height = 40;
            this.UserView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.UserView.Size = new System.Drawing.Size(1067, 587);
            this.UserView.TabIndex = 156;
            this.UserView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnAdd
            // 
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowMouseEffects = true;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.AutoRoundBorders = false;
            this.btnAdd.AutoSizeLeftIcon = true;
            this.btnAdd.AutoSizeRightIcon = true;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "THÊM";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges2;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 10;
            this.btnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdd.IconSize = 25;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleBorderRadius = 40;
            this.btnAdd.IdleBorderThickness = 1;
            this.btnAdd.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleIconLeftImage = null;
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(580, 653);
            this.btnAdd.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.OnDisabledState.BorderRadius = 40;
            this.btnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnDisabledState.BorderThickness = 1;
            this.btnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.OnDisabledState.IconLeftImage = null;
            this.btnAdd.OnDisabledState.IconRightImage = null;
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.BorderRadius = 40;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAdd.onHoverState.IconLeftImage = null;
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.BorderRadius = 40;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnIdleState.IconLeftImage = null;
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.BorderRadius = 40;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(108, 57);
            this.btnAdd.TabIndex = 153;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // txbNameCat
            // 
            this.txbNameCat.AcceptsReturn = false;
            this.txbNameCat.AcceptsTab = false;
            this.txbNameCat.AnimationSpeed = 200;
            this.txbNameCat.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbNameCat.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbNameCat.BackColor = System.Drawing.Color.Transparent;
            this.txbNameCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbNameCat.BackgroundImage")));
            this.txbNameCat.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbNameCat.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbNameCat.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbNameCat.BorderColorIdle = System.Drawing.Color.Black;
            this.txbNameCat.BorderRadius = 30;
            this.txbNameCat.BorderThickness = 1;
            this.txbNameCat.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbNameCat.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameCat.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbNameCat.DefaultText = "";
            this.txbNameCat.FillColor = System.Drawing.Color.White;
            this.txbNameCat.HideSelection = true;
            this.txbNameCat.IconLeft = null;
            this.txbNameCat.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameCat.IconPadding = 10;
            this.txbNameCat.IconRight = null;
            this.txbNameCat.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameCat.Lines = new string[0];
            this.txbNameCat.Location = new System.Drawing.Point(1156, 212);
            this.txbNameCat.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbNameCat.MaxLength = 32767;
            this.txbNameCat.MinimumSize = new System.Drawing.Size(3, 2);
            this.txbNameCat.Modified = false;
            this.txbNameCat.Multiline = false;
            this.txbNameCat.Name = "txbNameCat";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameCat.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Black;
            stateProperties18.FillColor = System.Drawing.Color.Transparent;
            stateProperties18.ForeColor = System.Drawing.Color.Transparent;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbNameCat.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameCat.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameCat.OnIdleState = stateProperties20;
            this.txbNameCat.Padding = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.txbNameCat.PasswordChar = '\0';
            this.txbNameCat.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbNameCat.PlaceholderText = "";
            this.txbNameCat.ReadOnly = false;
            this.txbNameCat.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbNameCat.SelectedText = "";
            this.txbNameCat.SelectionLength = 0;
            this.txbNameCat.SelectionStart = 0;
            this.txbNameCat.ShortcutsEnabled = true;
            this.txbNameCat.Size = new System.Drawing.Size(337, 47);
            this.txbNameCat.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbNameCat.TabIndex = 152;
            this.txbNameCat.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbNameCat.TextMarginBottom = 0;
            this.txbNameCat.TextMarginLeft = 3;
            this.txbNameCat.TextMarginTop = 0;
            this.txbNameCat.TextPlaceholder = "";
            this.txbNameCat.UseSystemPasswordChar = false;
            this.txbNameCat.WordWrap = true;
            // 
            // btnCheck
            // 
            this.btnCheck.AllowAnimations = true;
            this.btnCheck.AllowMouseEffects = true;
            this.btnCheck.AllowToggling = false;
            this.btnCheck.AnimationSpeed = 200;
            this.btnCheck.AutoGenerateColors = false;
            this.btnCheck.AutoRoundBorders = false;
            this.btnCheck.AutoSizeLeftIcon = true;
            this.btnCheck.AutoSizeRightIcon = true;
            this.btnCheck.BackColor = System.Drawing.Color.Transparent;
            this.btnCheck.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnCheck.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCheck.BackgroundImage")));
            this.btnCheck.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.ButtonText = "CHECK";
            this.btnCheck.ButtonTextMarginLeft = 0;
            this.btnCheck.ColorContrastOnClick = 45;
            this.btnCheck.ColorContrastOnHover = 45;
            this.btnCheck.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCheck.CustomizableEdges = borderEdges3;
            this.btnCheck.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCheck.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCheck.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCheck.ForeColor = System.Drawing.Color.White;
            this.btnCheck.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCheck.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCheck.IconMarginLeft = 11;
            this.btnCheck.IconPadding = 10;
            this.btnCheck.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCheck.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCheck.IconSize = 25;
            this.btnCheck.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleBorderRadius = 40;
            this.btnCheck.IdleBorderThickness = 1;
            this.btnCheck.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleIconLeftImage = null;
            this.btnCheck.IdleIconRightImage = null;
            this.btnCheck.IndicateFocus = false;
            this.btnCheck.Location = new System.Drawing.Point(1389, 31);
            this.btnCheck.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.btnCheck.Name = "btnCheck";
            this.btnCheck.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.OnDisabledState.BorderRadius = 40;
            this.btnCheck.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnDisabledState.BorderThickness = 1;
            this.btnCheck.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.OnDisabledState.IconLeftImage = null;
            this.btnCheck.OnDisabledState.IconRightImage = null;
            this.btnCheck.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.BorderRadius = 40;
            this.btnCheck.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.onHoverState.BorderThickness = 1;
            this.btnCheck.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCheck.onHoverState.IconLeftImage = null;
            this.btnCheck.onHoverState.IconRightImage = null;
            this.btnCheck.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.BorderRadius = 40;
            this.btnCheck.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnIdleState.BorderThickness = 1;
            this.btnCheck.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnIdleState.IconLeftImage = null;
            this.btnCheck.OnIdleState.IconRightImage = null;
            this.btnCheck.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.BorderRadius = 40;
            this.btnCheck.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnPressedState.BorderThickness = 1;
            this.btnCheck.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnPressedState.IconLeftImage = null;
            this.btnCheck.OnPressedState.IconRightImage = null;
            this.btnCheck.Size = new System.Drawing.Size(113, 57);
            this.btnCheck.TabIndex = 151;
            this.btnCheck.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCheck.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCheck.TextMarginLeft = 0;
            this.btnCheck.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCheck.UseDefaultRadiusAndThickness = true;
            // 
            // CatMng
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1540, 737);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnRefresh);
            this.Controls.Add(this.txbIDCat);
            this.Controls.Add(this.txbPrice);
            this.Controls.Add(this.txbAvailable);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.tbCat_Name);
            this.Controls.Add(this.UserView);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.txbNameCat);
            this.Controls.Add(this.btnCheck);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "CatMng";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "CatMng";
            this.Load += new System.EventHandler(this.Cat_Load);
            ((System.ComponentModel.ISupportInitialize)(this.UserView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuTextBox txbIDCat;
        private Bunifu.UI.WinForms.BunifuTextBox txbPrice;
        private Bunifu.UI.WinForms.BunifuTextBox txbAvailable;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox tbCat_Name;
        private Bunifu.UI.WinForms.BunifuDataGridView UserView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuTextBox txbNameCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCheck;
    }
}