namespace UI
{
    partial class ProductMng
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ProductMng));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txbPoint = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dbType = new Bunifu.UI.WinForms.BunifuDropdown();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txbPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dbStatus = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txbNameItem = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txbSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllYourDrinks = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCheck = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel7.Location = new System.Drawing.Point(886, 312);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(37, 17);
            this.bunifuLabel7.TabIndex = 247;
            this.bunifuLabel7.Text = "Điểm:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txbPoint
            // 
            this.txbPoint.AcceptsReturn = false;
            this.txbPoint.AcceptsTab = false;
            this.txbPoint.AnimationSpeed = 200;
            this.txbPoint.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbPoint.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbPoint.BackColor = System.Drawing.Color.Transparent;
            this.txbPoint.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbPoint.BackgroundImage")));
            this.txbPoint.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbPoint.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbPoint.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbPoint.BorderColorIdle = System.Drawing.Color.Black;
            this.txbPoint.BorderRadius = 35;
            this.txbPoint.BorderThickness = 1;
            this.txbPoint.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbPoint.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPoint.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbPoint.DefaultText = "";
            this.txbPoint.FillColor = System.Drawing.Color.White;
            this.txbPoint.HideSelection = true;
            this.txbPoint.IconLeft = null;
            this.txbPoint.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPoint.IconPadding = 10;
            this.txbPoint.IconRight = null;
            this.txbPoint.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPoint.Lines = new string[0];
            this.txbPoint.Location = new System.Drawing.Point(871, 321);
            this.txbPoint.Margin = new System.Windows.Forms.Padding(4);
            this.txbPoint.MaxLength = 32767;
            this.txbPoint.MinimumSize = new System.Drawing.Size(2, 2);
            this.txbPoint.Modified = false;
            this.txbPoint.Multiline = false;
            this.txbPoint.Name = "txbPoint";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPoint.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Black;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.Transparent;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbPoint.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPoint.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPoint.OnIdleState = stateProperties4;
            this.txbPoint.Padding = new System.Windows.Forms.Padding(4);
            this.txbPoint.PasswordChar = '\0';
            this.txbPoint.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbPoint.PlaceholderText = "";
            this.txbPoint.ReadOnly = false;
            this.txbPoint.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbPoint.SelectedText = "";
            this.txbPoint.SelectionLength = 0;
            this.txbPoint.SelectionStart = 0;
            this.txbPoint.ShortcutsEnabled = true;
            this.txbPoint.Size = new System.Drawing.Size(256, 38);
            this.txbPoint.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbPoint.TabIndex = 248;
            this.txbPoint.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbPoint.TextMarginBottom = 0;
            this.txbPoint.TextMarginLeft = 3;
            this.txbPoint.TextMarginTop = 0;
            this.txbPoint.TextPlaceholder = "";
            this.txbPoint.UseSystemPasswordChar = false;
            this.txbPoint.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel3.Location = new System.Drawing.Point(885, 374);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(30, 17);
            this.bunifuLabel3.TabIndex = 240;
            this.bunifuLabel3.Text = "Loại:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dbType
            // 
            this.dbType.BackColor = System.Drawing.Color.Transparent;
            this.dbType.BackgroundColor = System.Drawing.Color.White;
            this.dbType.BorderColor = System.Drawing.Color.Black;
            this.dbType.BorderRadius = 16;
            this.dbType.Color = System.Drawing.Color.Black;
            this.dbType.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.dbType.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dbType.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dbType.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dbType.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.dbType.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.dbType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.dbType.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.dbType.DropDownHeight = 400;
            this.dbType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dbType.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dbType.FillDropDown = true;
            this.dbType.FillIndicator = false;
            this.dbType.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dbType.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dbType.ForeColor = System.Drawing.Color.Black;
            this.dbType.FormattingEnabled = true;
            this.dbType.Icon = null;
            this.dbType.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dbType.IndicatorColor = System.Drawing.Color.Black;
            this.dbType.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dbType.IntegralHeight = false;
            this.dbType.ItemBackColor = System.Drawing.Color.White;
            this.dbType.ItemBorderColor = System.Drawing.Color.White;
            this.dbType.ItemForeColor = System.Drawing.Color.Black;
            this.dbType.ItemHeight = 30;
            this.dbType.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.dbType.ItemHighLightForeColor = System.Drawing.Color.White;
            this.dbType.Items.AddRange(new object[] {
            "Thức Ăn Cho Mèo",
            "Cỏ Mèo"});
            this.dbType.ItemTopMargin = 3;
            this.dbType.Location = new System.Drawing.Point(872, 385);
            this.dbType.Margin = new System.Windows.Forms.Padding(4);
            this.dbType.Name = "dbType";
            this.dbType.Size = new System.Drawing.Size(257, 36);
            this.dbType.TabIndex = 246;
            this.dbType.Text = null;
            this.dbType.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dbType.TextLeftMargin = 5;
            // 
            // pictureBox
            // 
            this.pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pictureBox.Location = new System.Drawing.Point(870, 120);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(127, 127);
            this.pictureBox.TabIndex = 245;
            this.pictureBox.TabStop = false;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel2.Location = new System.Drawing.Point(887, 253);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(24, 17);
            this.bunifuLabel2.TabIndex = 238;
            this.bunifuLabel2.Text = "Giá:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txbPrice
            // 
            this.txbPrice.AcceptsReturn = false;
            this.txbPrice.AcceptsTab = false;
            this.txbPrice.AnimationSpeed = 200;
            this.txbPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbPrice.BackColor = System.Drawing.Color.Transparent;
            this.txbPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbPrice.BackgroundImage")));
            this.txbPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbPrice.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbPrice.BorderColorIdle = System.Drawing.Color.Black;
            this.txbPrice.BorderRadius = 35;
            this.txbPrice.BorderThickness = 1;
            this.txbPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbPrice.DefaultText = "";
            this.txbPrice.FillColor = System.Drawing.Color.White;
            this.txbPrice.HideSelection = true;
            this.txbPrice.IconLeft = null;
            this.txbPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.IconPadding = 10;
            this.txbPrice.IconRight = null;
            this.txbPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbPrice.Lines = new string[0];
            this.txbPrice.Location = new System.Drawing.Point(872, 262);
            this.txbPrice.Margin = new System.Windows.Forms.Padding(4);
            this.txbPrice.MaxLength = 32767;
            this.txbPrice.MinimumSize = new System.Drawing.Size(2, 2);
            this.txbPrice.Modified = false;
            this.txbPrice.Multiline = false;
            this.txbPrice.Name = "txbPrice";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Black;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.Transparent;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Black;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbPrice.OnIdleState = stateProperties8;
            this.txbPrice.Padding = new System.Windows.Forms.Padding(4);
            this.txbPrice.PasswordChar = '\0';
            this.txbPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbPrice.PlaceholderText = "";
            this.txbPrice.ReadOnly = false;
            this.txbPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbPrice.SelectedText = "";
            this.txbPrice.SelectionLength = 0;
            this.txbPrice.SelectionStart = 0;
            this.txbPrice.ShortcutsEnabled = true;
            this.txbPrice.Size = new System.Drawing.Size(256, 38);
            this.txbPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbPrice.TabIndex = 239;
            this.txbPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbPrice.TextMarginBottom = 0;
            this.txbPrice.TextMarginLeft = 3;
            this.txbPrice.TextMarginTop = 0;
            this.txbPrice.TextPlaceholder = "";
            this.txbPrice.UseSystemPasswordChar = false;
            this.txbPrice.WordWrap = true;
            // 
            // btnImage
            // 
            this.btnImage.AllowAnimations = true;
            this.btnImage.AllowMouseEffects = true;
            this.btnImage.AllowToggling = false;
            this.btnImage.AnimationSpeed = 200;
            this.btnImage.AutoGenerateColors = false;
            this.btnImage.AutoRoundBorders = false;
            this.btnImage.AutoSizeLeftIcon = true;
            this.btnImage.AutoSizeRightIcon = true;
            this.btnImage.BackColor = System.Drawing.Color.Transparent;
            this.btnImage.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImage.BackgroundImage")));
            this.btnImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.ButtonText = "Chọn Ảnh";
            this.btnImage.ButtonTextMarginLeft = 0;
            this.btnImage.ColorContrastOnClick = 45;
            this.btnImage.ColorContrastOnHover = 45;
            this.btnImage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnImage.CustomizableEdges = borderEdges1;
            this.btnImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnImage.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnImage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnImage.IconMarginLeft = 11;
            this.btnImage.IconPadding = 10;
            this.btnImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnImage.IconSize = 25;
            this.btnImage.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IdleBorderRadius = 35;
            this.btnImage.IdleBorderThickness = 1;
            this.btnImage.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.IdleIconLeftImage = null;
            this.btnImage.IdleIconRightImage = null;
            this.btnImage.IndicateFocus = false;
            this.btnImage.Location = new System.Drawing.Point(951, 509);
            this.btnImage.Margin = new System.Windows.Forms.Padding(4);
            this.btnImage.Name = "btnImage";
            this.btnImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.OnDisabledState.BorderRadius = 35;
            this.btnImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnDisabledState.BorderThickness = 1;
            this.btnImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.OnDisabledState.IconLeftImage = null;
            this.btnImage.OnDisabledState.IconRightImage = null;
            this.btnImage.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.onHoverState.BorderRadius = 35;
            this.btnImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.onHoverState.BorderThickness = 1;
            this.btnImage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnImage.onHoverState.IconLeftImage = null;
            this.btnImage.onHoverState.IconRightImage = null;
            this.btnImage.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.BorderRadius = 35;
            this.btnImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnIdleState.BorderThickness = 1;
            this.btnImage.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.IconLeftImage = null;
            this.btnImage.OnIdleState.IconRightImage = null;
            this.btnImage.OnPressedState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.OnPressedState.BorderRadius = 35;
            this.btnImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnPressedState.BorderThickness = 1;
            this.btnImage.OnPressedState.FillColor = System.Drawing.Color.Sienna;
            this.btnImage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImage.OnPressedState.IconLeftImage = null;
            this.btnImage.OnPressedState.IconRightImage = null;
            this.btnImage.Size = new System.Drawing.Size(94, 41);
            this.btnImage.TabIndex = 244;
            this.btnImage.TabStop = false;
            this.btnImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImage.TextMarginLeft = 0;
            this.btnImage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnImage.UseDefaultRadiusAndThickness = true;
            this.btnImage.Click += new System.EventHandler(this.btnImage_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel6.Location = new System.Drawing.Point(871, 98);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(61, 17);
            this.bunifuLabel6.TabIndex = 243;
            this.bunifuLabel6.Text = "Hình ảnh:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel5.Location = new System.Drawing.Point(885, 441);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(69, 17);
            this.bunifuLabel5.TabIndex = 242;
            this.bunifuLabel5.Text = "Trạng thái:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dbStatus
            // 
            this.dbStatus.BackColor = System.Drawing.Color.Transparent;
            this.dbStatus.BackgroundColor = System.Drawing.Color.White;
            this.dbStatus.BorderColor = System.Drawing.Color.Black;
            this.dbStatus.BorderRadius = 16;
            this.dbStatus.Color = System.Drawing.Color.Black;
            this.dbStatus.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.dbStatus.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dbStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dbStatus.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dbStatus.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.dbStatus.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.dbStatus.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.dbStatus.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.dbStatus.DropDownHeight = 400;
            this.dbStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dbStatus.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dbStatus.FillDropDown = true;
            this.dbStatus.FillIndicator = false;
            this.dbStatus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dbStatus.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dbStatus.ForeColor = System.Drawing.Color.Black;
            this.dbStatus.FormattingEnabled = true;
            this.dbStatus.Icon = null;
            this.dbStatus.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dbStatus.IndicatorColor = System.Drawing.Color.Black;
            this.dbStatus.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dbStatus.IntegralHeight = false;
            this.dbStatus.ItemBackColor = System.Drawing.Color.White;
            this.dbStatus.ItemBorderColor = System.Drawing.Color.White;
            this.dbStatus.ItemForeColor = System.Drawing.Color.Black;
            this.dbStatus.ItemHeight = 30;
            this.dbStatus.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.dbStatus.ItemHighLightForeColor = System.Drawing.Color.White;
            this.dbStatus.Items.AddRange(new object[] {
            "Available",
            "Booked"});
            this.dbStatus.ItemTopMargin = 3;
            this.dbStatus.Location = new System.Drawing.Point(872, 452);
            this.dbStatus.Margin = new System.Windows.Forms.Padding(4);
            this.dbStatus.Name = "dbStatus";
            this.dbStatus.Size = new System.Drawing.Size(257, 36);
            this.dbStatus.TabIndex = 241;
            this.dbStatus.Text = null;
            this.dbStatus.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dbStatus.TextLeftMargin = 5;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel4.Location = new System.Drawing.Point(1016, 183);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(91, 17);
            this.bunifuLabel4.TabIndex = 237;
            this.bunifuLabel4.Text = "Tên sản phẩm:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel1.Location = new System.Drawing.Point(1016, 128);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(19, 17);
            this.bunifuLabel1.TabIndex = 236;
            this.bunifuLabel1.Text = "ID:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnRefresh
            // 
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowMouseEffects = true;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AnimationSpeed = 200;
            this.btnRefresh.AutoGenerateColors = false;
            this.btnRefresh.AutoRoundBorders = false;
            this.btnRefresh.AutoSizeLeftIcon = true;
            this.btnRefresh.AutoSizeRightIcon = true;
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnRefresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.BackgroundImage")));
            this.btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.ButtonText = "REFRESH";
            this.btnRefresh.ButtonTextMarginLeft = 0;
            this.btnRefresh.ColorContrastOnClick = 45;
            this.btnRefresh.ColorContrastOnHover = 45;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnRefresh.CustomizableEdges = borderEdges2;
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRefresh.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRefresh.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRefresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRefresh.IconMarginLeft = 11;
            this.btnRefresh.IconPadding = 10;
            this.btnRefresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRefresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRefresh.IconSize = 25;
            this.btnRefresh.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleBorderRadius = 40;
            this.btnRefresh.IdleBorderThickness = 1;
            this.btnRefresh.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleIconLeftImage = null;
            this.btnRefresh.IdleIconRightImage = null;
            this.btnRefresh.IndicateFocus = false;
            this.btnRefresh.Location = new System.Drawing.Point(245, 527);
            this.btnRefresh.Margin = new System.Windows.Forms.Padding(4);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.OnDisabledState.BorderRadius = 40;
            this.btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnDisabledState.BorderThickness = 1;
            this.btnRefresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.OnDisabledState.IconLeftImage = null;
            this.btnRefresh.OnDisabledState.IconRightImage = null;
            this.btnRefresh.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.BorderRadius = 40;
            this.btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.onHoverState.BorderThickness = 1;
            this.btnRefresh.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRefresh.onHoverState.IconLeftImage = null;
            this.btnRefresh.onHoverState.IconRightImage = null;
            this.btnRefresh.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.BorderRadius = 40;
            this.btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnIdleState.BorderThickness = 1;
            this.btnRefresh.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnIdleState.IconLeftImage = null;
            this.btnRefresh.OnIdleState.IconRightImage = null;
            this.btnRefresh.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.BorderRadius = 40;
            this.btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnPressedState.BorderThickness = 1;
            this.btnRefresh.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnPressedState.IconLeftImage = null;
            this.btnRefresh.OnPressedState.IconRightImage = null;
            this.btnRefresh.Size = new System.Drawing.Size(81, 46);
            this.btnRefresh.TabIndex = 235;
            this.btnRefresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRefresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRefresh.TextMarginLeft = 0;
            this.btnRefresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.UseDefaultRadiusAndThickness = true;
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // txbID
            // 
            this.txbID.AcceptsReturn = false;
            this.txbID.AcceptsTab = false;
            this.txbID.AnimationSpeed = 200;
            this.txbID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbID.BackColor = System.Drawing.Color.White;
            this.txbID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbID.BackgroundImage")));
            this.txbID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbID.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbID.BorderColorIdle = System.Drawing.Color.Black;
            this.txbID.BorderRadius = 35;
            this.txbID.BorderThickness = 1;
            this.txbID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbID.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbID.DefaultText = "";
            this.txbID.FillColor = System.Drawing.Color.White;
            this.txbID.HideSelection = true;
            this.txbID.IconLeft = null;
            this.txbID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbID.IconPadding = 10;
            this.txbID.IconRight = null;
            this.txbID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbID.Lines = new string[0];
            this.txbID.Location = new System.Drawing.Point(1004, 138);
            this.txbID.Margin = new System.Windows.Forms.Padding(4);
            this.txbID.MaxLength = 32767;
            this.txbID.MinimumSize = new System.Drawing.Size(2, 2);
            this.txbID.Modified = false;
            this.txbID.Multiline = false;
            this.txbID.Name = "txbID";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Black;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.Transparent;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbID.OnIdleState = stateProperties12;
            this.txbID.Padding = new System.Windows.Forms.Padding(4);
            this.txbID.PasswordChar = '\0';
            this.txbID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbID.PlaceholderText = "";
            this.txbID.ReadOnly = false;
            this.txbID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbID.SelectedText = "";
            this.txbID.SelectionLength = 0;
            this.txbID.SelectionStart = 0;
            this.txbID.ShortcutsEnabled = true;
            this.txbID.Size = new System.Drawing.Size(123, 38);
            this.txbID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbID.TabIndex = 234;
            this.txbID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbID.TextMarginBottom = 0;
            this.txbID.TextMarginLeft = 3;
            this.txbID.TextMarginTop = 0;
            this.txbID.TextPlaceholder = "";
            this.txbID.UseSystemPasswordChar = false;
            this.txbID.WordWrap = true;
            // 
            // txbNameItem
            // 
            this.txbNameItem.AcceptsReturn = false;
            this.txbNameItem.AcceptsTab = false;
            this.txbNameItem.AnimationSpeed = 200;
            this.txbNameItem.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbNameItem.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbNameItem.BackColor = System.Drawing.Color.Transparent;
            this.txbNameItem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbNameItem.BackgroundImage")));
            this.txbNameItem.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbNameItem.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbNameItem.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbNameItem.BorderColorIdle = System.Drawing.Color.Black;
            this.txbNameItem.BorderRadius = 35;
            this.txbNameItem.BorderThickness = 1;
            this.txbNameItem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbNameItem.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameItem.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbNameItem.DefaultText = "";
            this.txbNameItem.FillColor = System.Drawing.Color.White;
            this.txbNameItem.HideSelection = true;
            this.txbNameItem.IconLeft = null;
            this.txbNameItem.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameItem.IconPadding = 10;
            this.txbNameItem.IconRight = null;
            this.txbNameItem.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbNameItem.Lines = new string[0];
            this.txbNameItem.Location = new System.Drawing.Point(1004, 192);
            this.txbNameItem.Margin = new System.Windows.Forms.Padding(4);
            this.txbNameItem.MaxLength = 32767;
            this.txbNameItem.MinimumSize = new System.Drawing.Size(2, 2);
            this.txbNameItem.Modified = false;
            this.txbNameItem.Multiline = false;
            this.txbNameItem.Name = "txbNameItem";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameItem.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Black;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.Transparent;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbNameItem.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameItem.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbNameItem.OnIdleState = stateProperties16;
            this.txbNameItem.Padding = new System.Windows.Forms.Padding(4);
            this.txbNameItem.PasswordChar = '\0';
            this.txbNameItem.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbNameItem.PlaceholderText = "";
            this.txbNameItem.ReadOnly = false;
            this.txbNameItem.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbNameItem.SelectedText = "";
            this.txbNameItem.SelectionLength = 0;
            this.txbNameItem.SelectionStart = 0;
            this.txbNameItem.ShortcutsEnabled = true;
            this.txbNameItem.Size = new System.Drawing.Size(123, 38);
            this.txbNameItem.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbNameItem.TabIndex = 233;
            this.txbNameItem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbNameItem.TextMarginBottom = 0;
            this.txbNameItem.TextMarginLeft = 3;
            this.txbNameItem.TextMarginTop = 0;
            this.txbNameItem.TextPlaceholder = "";
            this.txbNameItem.UseSystemPasswordChar = false;
            this.txbNameItem.WordWrap = true;
            // 
            // label1
            // 
            this.label1.ForeColor = System.Drawing.Color.Gray;
            this.label1.Location = new System.Drawing.Point(868, 75);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(260, 20);
            this.label1.TabIndex = 232;
            this.label1.Text = resources.GetString("label1.Text");
            // 
            // txbSearch
            // 
            this.txbSearch.AcceptsReturn = false;
            this.txbSearch.AcceptsTab = false;
            this.txbSearch.AnimationSpeed = 200;
            this.txbSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSearch.BackColor = System.Drawing.Color.White;
            this.txbSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSearch.BackgroundImage")));
            this.txbSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txbSearch.BorderColorDisabled = System.Drawing.Color.Black;
            this.txbSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txbSearch.BorderColorIdle = System.Drawing.Color.Black;
            this.txbSearch.BorderRadius = 35;
            this.txbSearch.BorderThickness = 1;
            this.txbSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSearch.DefaultFont = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 8F);
            this.txbSearch.DefaultText = "";
            this.txbSearch.FillColor = System.Drawing.Color.White;
            this.txbSearch.HideSelection = true;
            this.txbSearch.IconLeft = null;
            this.txbSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSearch.IconPadding = 10;
            this.txbSearch.IconRight = null;
            this.txbSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSearch.Lines = new string[0];
            this.txbSearch.Location = new System.Drawing.Point(867, 25);
            this.txbSearch.Margin = new System.Windows.Forms.Padding(4);
            this.txbSearch.MaxLength = 32767;
            this.txbSearch.MinimumSize = new System.Drawing.Size(2, 2);
            this.txbSearch.Modified = false;
            this.txbSearch.Multiline = false;
            this.txbSearch.Name = "txbSearch";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSearch.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Black;
            stateProperties18.FillColor = System.Drawing.Color.Transparent;
            stateProperties18.ForeColor = System.Drawing.Color.Transparent;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txbSearch.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSearch.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSearch.OnIdleState = stateProperties20;
            this.txbSearch.Padding = new System.Windows.Forms.Padding(4);
            this.txbSearch.PasswordChar = '\0';
            this.txbSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSearch.PlaceholderText = "Nhập ID sản phẩm để tìm";
            this.txbSearch.ReadOnly = false;
            this.txbSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSearch.SelectedText = "";
            this.txbSearch.SelectionLength = 0;
            this.txbSearch.SelectionStart = 0;
            this.txbSearch.ShortcutsEnabled = true;
            this.txbSearch.Size = new System.Drawing.Size(167, 46);
            this.txbSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txbSearch.TabIndex = 231;
            this.txbSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSearch.TextMarginBottom = 0;
            this.txbSearch.TextMarginLeft = 3;
            this.txbSearch.TextMarginTop = 0;
            this.txbSearch.TextPlaceholder = "Nhập ID sản phẩm để tìm";
            this.txbSearch.UseSystemPasswordChar = false;
            this.txbSearch.WordWrap = true;
            // 
            // AdminViewAllYourDrinks
            // 
            this.AdminViewAllYourDrinks.AllowCustomTheming = false;
            this.AdminViewAllYourDrinks.AllowUserToAddRows = false;
            this.AdminViewAllYourDrinks.AllowUserToDeleteRows = false;
            this.AdminViewAllYourDrinks.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.AdminViewAllYourDrinks.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.AdminViewAllYourDrinks.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.AdminViewAllYourDrinks.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.AdminViewAllYourDrinks.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.AdminViewAllYourDrinks.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.AdminViewAllYourDrinks.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.AdminViewAllYourDrinks.ColumnHeadersHeight = 40;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.Name = null;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.AdminViewAllYourDrinks.DefaultCellStyle = dataGridViewCellStyle3;
            this.AdminViewAllYourDrinks.EnableHeadersVisualStyles = false;
            this.AdminViewAllYourDrinks.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.HeaderBgColor = System.Drawing.Color.Empty;
            this.AdminViewAllYourDrinks.HeaderForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.Location = new System.Drawing.Point(31, 35);
            this.AdminViewAllYourDrinks.Name = "AdminViewAllYourDrinks";
            this.AdminViewAllYourDrinks.ReadOnly = true;
            this.AdminViewAllYourDrinks.RowHeadersVisible = false;
            this.AdminViewAllYourDrinks.RowHeadersWidth = 62;
            this.AdminViewAllYourDrinks.RowTemplate.Height = 40;
            this.AdminViewAllYourDrinks.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.AdminViewAllYourDrinks.Size = new System.Drawing.Size(800, 477);
            this.AdminViewAllYourDrinks.TabIndex = 230;
            this.AdminViewAllYourDrinks.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnUpdate
            // 
            this.btnUpdate.AllowAnimations = true;
            this.btnUpdate.AllowMouseEffects = true;
            this.btnUpdate.AllowToggling = false;
            this.btnUpdate.AnimationSpeed = 200;
            this.btnUpdate.AutoGenerateColors = false;
            this.btnUpdate.AutoRoundBorders = false;
            this.btnUpdate.AutoSizeLeftIcon = true;
            this.btnUpdate.AutoSizeRightIcon = true;
            this.btnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdate.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.ButtonText = "SỬA";
            this.btnUpdate.ButtonTextMarginLeft = 0;
            this.btnUpdate.ColorContrastOnClick = 45;
            this.btnUpdate.ColorContrastOnHover = 45;
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnUpdate.CustomizableEdges = borderEdges3;
            this.btnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdate.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpdate.IconMarginLeft = 11;
            this.btnUpdate.IconPadding = 10;
            this.btnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdate.IconSize = 25;
            this.btnUpdate.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.IdleBorderRadius = 40;
            this.btnUpdate.IdleBorderThickness = 1;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.IdleIconLeftImage = null;
            this.btnUpdate.IdleIconRightImage = null;
            this.btnUpdate.IndicateFocus = false;
            this.btnUpdate.Location = new System.Drawing.Point(512, 527);
            this.btnUpdate.Margin = new System.Windows.Forms.Padding(4);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.OnDisabledState.BorderRadius = 40;
            this.btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnDisabledState.BorderThickness = 1;
            this.btnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.OnDisabledState.IconLeftImage = null;
            this.btnUpdate.OnDisabledState.IconRightImage = null;
            this.btnUpdate.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.onHoverState.BorderRadius = 40;
            this.btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.onHoverState.BorderThickness = 1;
            this.btnUpdate.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnUpdate.onHoverState.IconLeftImage = null;
            this.btnUpdate.onHoverState.IconRightImage = null;
            this.btnUpdate.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnIdleState.BorderRadius = 40;
            this.btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnIdleState.BorderThickness = 1;
            this.btnUpdate.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnIdleState.IconLeftImage = null;
            this.btnUpdate.OnIdleState.IconRightImage = null;
            this.btnUpdate.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnPressedState.BorderRadius = 40;
            this.btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnPressedState.BorderThickness = 1;
            this.btnUpdate.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnPressedState.IconLeftImage = null;
            this.btnUpdate.OnPressedState.IconRightImage = null;
            this.btnUpdate.Size = new System.Drawing.Size(81, 46);
            this.btnUpdate.TabIndex = 229;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdate.TextMarginLeft = 0;
            this.btnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdate.UseDefaultRadiusAndThickness = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "XOÁ";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges4;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 10;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.IdleBorderRadius = 40;
            this.btnDelete.IdleBorderThickness = 1;
            this.btnDelete.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.IdleIconLeftImage = null;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(423, 527);
            this.btnDelete.Margin = new System.Windows.Forms.Padding(4);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 40;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.onHoverState.BorderRadius = 40;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnIdleState.BorderRadius = 40;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnIdleState.IconLeftImage = null;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnPressedState.BorderRadius = 40;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(81, 46);
            this.btnDelete.TabIndex = 228;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnAdd
            // 
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowMouseEffects = true;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.AutoRoundBorders = false;
            this.btnAdd.AutoSizeLeftIcon = true;
            this.btnAdd.AutoSizeRightIcon = true;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "THÊM";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges5;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 10;
            this.btnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdd.IconSize = 25;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleBorderRadius = 40;
            this.btnAdd.IdleBorderThickness = 1;
            this.btnAdd.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleIconLeftImage = null;
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(334, 527);
            this.btnAdd.Margin = new System.Windows.Forms.Padding(4);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.OnDisabledState.BorderRadius = 40;
            this.btnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnDisabledState.BorderThickness = 1;
            this.btnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.OnDisabledState.IconLeftImage = null;
            this.btnAdd.OnDisabledState.IconRightImage = null;
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.BorderRadius = 40;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAdd.onHoverState.IconLeftImage = null;
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.BorderRadius = 40;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnIdleState.IconLeftImage = null;
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.BorderRadius = 40;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(81, 46);
            this.btnAdd.TabIndex = 227;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // btnCheck
            // 
            this.btnCheck.AllowAnimations = true;
            this.btnCheck.AllowMouseEffects = true;
            this.btnCheck.AllowToggling = false;
            this.btnCheck.AnimationSpeed = 200;
            this.btnCheck.AutoGenerateColors = false;
            this.btnCheck.AutoRoundBorders = false;
            this.btnCheck.AutoSizeLeftIcon = true;
            this.btnCheck.AutoSizeRightIcon = true;
            this.btnCheck.BackColor = System.Drawing.Color.Transparent;
            this.btnCheck.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnCheck.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCheck.BackgroundImage")));
            this.btnCheck.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.ButtonText = "TÌM KIẾM";
            this.btnCheck.ButtonTextMarginLeft = 0;
            this.btnCheck.ColorContrastOnClick = 45;
            this.btnCheck.ColorContrastOnHover = 45;
            this.btnCheck.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCheck.CustomizableEdges = borderEdges6;
            this.btnCheck.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCheck.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCheck.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCheck.ForeColor = System.Drawing.Color.White;
            this.btnCheck.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCheck.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCheck.IconMarginLeft = 11;
            this.btnCheck.IconPadding = 10;
            this.btnCheck.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCheck.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCheck.IconSize = 25;
            this.btnCheck.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleBorderRadius = 40;
            this.btnCheck.IdleBorderThickness = 1;
            this.btnCheck.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleIconLeftImage = null;
            this.btnCheck.IdleIconRightImage = null;
            this.btnCheck.IndicateFocus = false;
            this.btnCheck.Location = new System.Drawing.Point(1042, 25);
            this.btnCheck.Margin = new System.Windows.Forms.Padding(4);
            this.btnCheck.Name = "btnCheck";
            this.btnCheck.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.OnDisabledState.BorderRadius = 40;
            this.btnCheck.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnDisabledState.BorderThickness = 1;
            this.btnCheck.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.OnDisabledState.IconLeftImage = null;
            this.btnCheck.OnDisabledState.IconRightImage = null;
            this.btnCheck.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.BorderRadius = 40;
            this.btnCheck.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.onHoverState.BorderThickness = 1;
            this.btnCheck.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCheck.onHoverState.IconLeftImage = null;
            this.btnCheck.onHoverState.IconRightImage = null;
            this.btnCheck.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.BorderRadius = 40;
            this.btnCheck.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnIdleState.BorderThickness = 1;
            this.btnCheck.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnIdleState.IconLeftImage = null;
            this.btnCheck.OnIdleState.IconRightImage = null;
            this.btnCheck.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.BorderRadius = 40;
            this.btnCheck.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnPressedState.BorderThickness = 1;
            this.btnCheck.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnPressedState.IconLeftImage = null;
            this.btnCheck.OnPressedState.IconRightImage = null;
            this.btnCheck.Size = new System.Drawing.Size(85, 46);
            this.btnCheck.TabIndex = 226;
            this.btnCheck.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCheck.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCheck.TextMarginLeft = 0;
            this.btnCheck.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCheck.UseDefaultRadiusAndThickness = true;
            this.btnCheck.Click += new System.EventHandler(this.btnCheck_Click);
            // 
            // ProductMng
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1155, 599);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.txbPoint);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.dbType);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txbPrice);
            this.Controls.Add(this.btnImage);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.dbStatus);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnRefresh);
            this.Controls.Add(this.txbID);
            this.Controls.Add(this.txbNameItem);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txbSearch);
            this.Controls.Add(this.AdminViewAllYourDrinks);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.btnCheck);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "ProductMng";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản Lý Sản Phẩm";
            this.Load += new System.EventHandler(this.Items_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox txbPoint;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuDropdown dbType;
        private System.Windows.Forms.PictureBox pictureBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txbPrice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnImage;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuDropdown dbStatus;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuTextBox txbID;
        private Bunifu.UI.WinForms.BunifuTextBox txbNameItem;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txbSearch;
        private Bunifu.UI.WinForms.BunifuDataGridView AdminViewAllYourDrinks;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCheck;
    }
}