namespace Master_NekoCoffeeApp
{
    partial class Drinks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Drinks));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillDrinkID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.AdminFillDrinkSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminViewAllYourDrinks = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCheck = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillDrinkPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillDrinkType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.AdminFillDrinkAvailable = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel2.Location = new System.Drawing.Point(886, 266);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(24, 17);
            this.bunifuLabel2.TabIndex = 192;
            this.bunifuLabel2.Text = "Giá:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel4.Location = new System.Drawing.Point(1015, 196);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(62, 17);
            this.bunifuLabel4.TabIndex = 191;
            this.bunifuLabel4.Text = "Tên nước:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel1.Location = new System.Drawing.Point(1015, 141);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(19, 17);
            this.bunifuLabel1.TabIndex = 190;
            this.bunifuLabel1.Text = "ID:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnRefresh
            // 
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowMouseEffects = true;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AnimationSpeed = 200;
            this.btnRefresh.AutoGenerateColors = false;
            this.btnRefresh.AutoRoundBorders = false;
            this.btnRefresh.AutoSizeLeftIcon = true;
            this.btnRefresh.AutoSizeRightIcon = true;
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnRefresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.BackgroundImage")));
            this.btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.ButtonText = "REFRESH";
            this.btnRefresh.ButtonTextMarginLeft = 0;
            this.btnRefresh.ColorContrastOnClick = 45;
            this.btnRefresh.ColorContrastOnHover = 45;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnRefresh.CustomizableEdges = borderEdges7;
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRefresh.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRefresh.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRefresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRefresh.IconMarginLeft = 11;
            this.btnRefresh.IconPadding = 10;
            this.btnRefresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRefresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRefresh.IconSize = 25;
            this.btnRefresh.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleBorderRadius = 40;
            this.btnRefresh.IdleBorderThickness = 1;
            this.btnRefresh.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.IdleIconLeftImage = null;
            this.btnRefresh.IdleIconRightImage = null;
            this.btnRefresh.IndicateFocus = false;
            this.btnRefresh.Location = new System.Drawing.Point(245, 527);
            this.btnRefresh.Margin = new System.Windows.Forms.Padding(4);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.OnDisabledState.BorderRadius = 40;
            this.btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnDisabledState.BorderThickness = 1;
            this.btnRefresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.OnDisabledState.IconLeftImage = null;
            this.btnRefresh.OnDisabledState.IconRightImage = null;
            this.btnRefresh.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.BorderRadius = 40;
            this.btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.onHoverState.BorderThickness = 1;
            this.btnRefresh.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRefresh.onHoverState.IconLeftImage = null;
            this.btnRefresh.onHoverState.IconRightImage = null;
            this.btnRefresh.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.BorderRadius = 40;
            this.btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnIdleState.BorderThickness = 1;
            this.btnRefresh.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnIdleState.IconLeftImage = null;
            this.btnRefresh.OnIdleState.IconRightImage = null;
            this.btnRefresh.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.BorderRadius = 40;
            this.btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnPressedState.BorderThickness = 1;
            this.btnRefresh.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnRefresh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnPressedState.IconLeftImage = null;
            this.btnRefresh.OnPressedState.IconRightImage = null;
            this.btnRefresh.Size = new System.Drawing.Size(81, 46);
            this.btnRefresh.TabIndex = 189;
            this.btnRefresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRefresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRefresh.TextMarginLeft = 0;
            this.btnRefresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.UseDefaultRadiusAndThickness = true;
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // AdminFillDrinkID
            // 
            this.AdminFillDrinkID.AcceptsReturn = false;
            this.AdminFillDrinkID.AcceptsTab = false;
            this.AdminFillDrinkID.AnimationSpeed = 200;
            this.AdminFillDrinkID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkID.BackColor = System.Drawing.Color.White;
            this.AdminFillDrinkID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkID.BackgroundImage")));
            this.AdminFillDrinkID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkID.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdminFillDrinkID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkID.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFillDrinkID.BorderRadius = 35;
            this.AdminFillDrinkID.BorderThickness = 1;
            this.AdminFillDrinkID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkID.DefaultText = "";
            this.AdminFillDrinkID.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkID.HideSelection = true;
            this.AdminFillDrinkID.IconLeft = null;
            this.AdminFillDrinkID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.IconPadding = 10;
            this.AdminFillDrinkID.IconRight = null;
            this.AdminFillDrinkID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkID.Lines = new string[0];
            this.AdminFillDrinkID.Location = new System.Drawing.Point(1003, 151);
            this.AdminFillDrinkID.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkID.MaxLength = 32767;
            this.AdminFillDrinkID.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkID.Modified = false;
            this.AdminFillDrinkID.Multiline = false;
            this.AdminFillDrinkID.Name = "AdminFillDrinkID";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Black;
            stateProperties22.FillColor = System.Drawing.Color.Transparent;
            stateProperties22.ForeColor = System.Drawing.Color.Transparent;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkID.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkID.OnIdleState = stateProperties24;
            this.AdminFillDrinkID.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkID.PasswordChar = '\0';
            this.AdminFillDrinkID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkID.PlaceholderText = "";
            this.AdminFillDrinkID.ReadOnly = false;
            this.AdminFillDrinkID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkID.SelectedText = "";
            this.AdminFillDrinkID.SelectionLength = 0;
            this.AdminFillDrinkID.SelectionStart = 0;
            this.AdminFillDrinkID.ShortcutsEnabled = true;
            this.AdminFillDrinkID.Size = new System.Drawing.Size(123, 38);
            this.AdminFillDrinkID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkID.TabIndex = 187;
            this.AdminFillDrinkID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkID.TextMarginBottom = 0;
            this.AdminFillDrinkID.TextMarginLeft = 3;
            this.AdminFillDrinkID.TextMarginTop = 0;
            this.AdminFillDrinkID.TextPlaceholder = "";
            this.AdminFillDrinkID.UseSystemPasswordChar = false;
            this.AdminFillDrinkID.WordWrap = true;
            // 
            // AdminFillDrinkName
            // 
            this.AdminFillDrinkName.AcceptsReturn = false;
            this.AdminFillDrinkName.AcceptsTab = false;
            this.AdminFillDrinkName.AnimationSpeed = 200;
            this.AdminFillDrinkName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkName.BackgroundImage")));
            this.AdminFillDrinkName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkName.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdminFillDrinkName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkName.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFillDrinkName.BorderRadius = 35;
            this.AdminFillDrinkName.BorderThickness = 1;
            this.AdminFillDrinkName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkName.DefaultText = "";
            this.AdminFillDrinkName.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkName.HideSelection = true;
            this.AdminFillDrinkName.IconLeft = null;
            this.AdminFillDrinkName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.IconPadding = 10;
            this.AdminFillDrinkName.IconRight = null;
            this.AdminFillDrinkName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkName.Lines = new string[0];
            this.AdminFillDrinkName.Location = new System.Drawing.Point(1003, 205);
            this.AdminFillDrinkName.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkName.MaxLength = 32767;
            this.AdminFillDrinkName.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkName.Modified = false;
            this.AdminFillDrinkName.Multiline = false;
            this.AdminFillDrinkName.Name = "AdminFillDrinkName";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Black;
            stateProperties26.FillColor = System.Drawing.Color.Transparent;
            stateProperties26.ForeColor = System.Drawing.Color.Transparent;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Black;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkName.OnIdleState = stateProperties28;
            this.AdminFillDrinkName.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkName.PasswordChar = '\0';
            this.AdminFillDrinkName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkName.PlaceholderText = "";
            this.AdminFillDrinkName.ReadOnly = false;
            this.AdminFillDrinkName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkName.SelectedText = "";
            this.AdminFillDrinkName.SelectionLength = 0;
            this.AdminFillDrinkName.SelectionStart = 0;
            this.AdminFillDrinkName.ShortcutsEnabled = true;
            this.AdminFillDrinkName.Size = new System.Drawing.Size(123, 38);
            this.AdminFillDrinkName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkName.TabIndex = 186;
            this.AdminFillDrinkName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkName.TextMarginBottom = 0;
            this.AdminFillDrinkName.TextMarginLeft = 3;
            this.AdminFillDrinkName.TextMarginTop = 0;
            this.AdminFillDrinkName.TextPlaceholder = "";
            this.AdminFillDrinkName.UseSystemPasswordChar = false;
            this.AdminFillDrinkName.WordWrap = true;
            // 
            // label1
            // 
            this.label1.ForeColor = System.Drawing.Color.Gray;
            this.label1.Location = new System.Drawing.Point(867, 88);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(260, 20);
            this.label1.TabIndex = 185;
            this.label1.Text = resources.GetString("label1.Text");
            // 
            // AdminFillDrinkSearch
            // 
            this.AdminFillDrinkSearch.AcceptsReturn = false;
            this.AdminFillDrinkSearch.AcceptsTab = false;
            this.AdminFillDrinkSearch.AnimationSpeed = 200;
            this.AdminFillDrinkSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkSearch.BackColor = System.Drawing.Color.White;
            this.AdminFillDrinkSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkSearch.BackgroundImage")));
            this.AdminFillDrinkSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkSearch.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdminFillDrinkSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkSearch.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFillDrinkSearch.BorderRadius = 35;
            this.AdminFillDrinkSearch.BorderThickness = 1;
            this.AdminFillDrinkSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkSearch.DefaultText = "";
            this.AdminFillDrinkSearch.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkSearch.HideSelection = true;
            this.AdminFillDrinkSearch.IconLeft = null;
            this.AdminFillDrinkSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.IconPadding = 10;
            this.AdminFillDrinkSearch.IconRight = null;
            this.AdminFillDrinkSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkSearch.Lines = new string[0];
            this.AdminFillDrinkSearch.Location = new System.Drawing.Point(867, 25);
            this.AdminFillDrinkSearch.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkSearch.MaxLength = 32767;
            this.AdminFillDrinkSearch.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkSearch.Modified = false;
            this.AdminFillDrinkSearch.Multiline = false;
            this.AdminFillDrinkSearch.Name = "AdminFillDrinkSearch";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Black;
            stateProperties30.FillColor = System.Drawing.Color.Transparent;
            stateProperties30.ForeColor = System.Drawing.Color.Transparent;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkSearch.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Black;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkSearch.OnIdleState = stateProperties32;
            this.AdminFillDrinkSearch.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkSearch.PasswordChar = '\0';
            this.AdminFillDrinkSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkSearch.PlaceholderText = "Nhập ID nước để tìm";
            this.AdminFillDrinkSearch.ReadOnly = false;
            this.AdminFillDrinkSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkSearch.SelectedText = "";
            this.AdminFillDrinkSearch.SelectionLength = 0;
            this.AdminFillDrinkSearch.SelectionStart = 0;
            this.AdminFillDrinkSearch.ShortcutsEnabled = true;
            this.AdminFillDrinkSearch.Size = new System.Drawing.Size(167, 46);
            this.AdminFillDrinkSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkSearch.TabIndex = 184;
            this.AdminFillDrinkSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkSearch.TextMarginBottom = 0;
            this.AdminFillDrinkSearch.TextMarginLeft = 3;
            this.AdminFillDrinkSearch.TextMarginTop = 0;
            this.AdminFillDrinkSearch.TextPlaceholder = "Nhập ID nước để tìm";
            this.AdminFillDrinkSearch.UseSystemPasswordChar = false;
            this.AdminFillDrinkSearch.WordWrap = true;
            // 
            // AdminViewAllYourDrinks
            // 
            this.AdminViewAllYourDrinks.AllowCustomTheming = false;
            this.AdminViewAllYourDrinks.AllowUserToAddRows = false;
            this.AdminViewAllYourDrinks.AllowUserToDeleteRows = false;
            this.AdminViewAllYourDrinks.AllowUserToOrderColumns = true;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.AdminViewAllYourDrinks.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.AdminViewAllYourDrinks.BackgroundColor = System.Drawing.SystemColors.ButtonHighlight;
            this.AdminViewAllYourDrinks.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.AdminViewAllYourDrinks.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.AdminViewAllYourDrinks.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.AdminViewAllYourDrinks.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.AdminViewAllYourDrinks.ColumnHeadersHeight = 40;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.AdminViewAllYourDrinks.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.Name = null;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.AdminViewAllYourDrinks.DefaultCellStyle = dataGridViewCellStyle6;
            this.AdminViewAllYourDrinks.EnableHeadersVisualStyles = false;
            this.AdminViewAllYourDrinks.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.AdminViewAllYourDrinks.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.AdminViewAllYourDrinks.HeaderBgColor = System.Drawing.Color.Empty;
            this.AdminViewAllYourDrinks.HeaderForeColor = System.Drawing.Color.White;
            this.AdminViewAllYourDrinks.Location = new System.Drawing.Point(31, 35);
            this.AdminViewAllYourDrinks.Name = "AdminViewAllYourDrinks";
            this.AdminViewAllYourDrinks.ReadOnly = true;
            this.AdminViewAllYourDrinks.RowHeadersVisible = false;
            this.AdminViewAllYourDrinks.RowHeadersWidth = 62;
            this.AdminViewAllYourDrinks.RowTemplate.Height = 40;
            this.AdminViewAllYourDrinks.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.AdminViewAllYourDrinks.Size = new System.Drawing.Size(800, 477);
            this.AdminViewAllYourDrinks.TabIndex = 183;
            this.AdminViewAllYourDrinks.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnUpdate
            // 
            this.btnUpdate.AllowAnimations = true;
            this.btnUpdate.AllowMouseEffects = true;
            this.btnUpdate.AllowToggling = false;
            this.btnUpdate.AnimationSpeed = 200;
            this.btnUpdate.AutoGenerateColors = false;
            this.btnUpdate.AutoRoundBorders = false;
            this.btnUpdate.AutoSizeLeftIcon = true;
            this.btnUpdate.AutoSizeRightIcon = true;
            this.btnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdate.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.ButtonText = "SỬA";
            this.btnUpdate.ButtonTextMarginLeft = 0;
            this.btnUpdate.ColorContrastOnClick = 45;
            this.btnUpdate.ColorContrastOnHover = 45;
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnUpdate.CustomizableEdges = borderEdges8;
            this.btnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdate.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpdate.IconMarginLeft = 11;
            this.btnUpdate.IconPadding = 10;
            this.btnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdate.IconSize = 25;
            this.btnUpdate.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.IdleBorderRadius = 40;
            this.btnUpdate.IdleBorderThickness = 1;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.IdleIconLeftImage = null;
            this.btnUpdate.IdleIconRightImage = null;
            this.btnUpdate.IndicateFocus = false;
            this.btnUpdate.Location = new System.Drawing.Point(512, 527);
            this.btnUpdate.Margin = new System.Windows.Forms.Padding(4);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.OnDisabledState.BorderRadius = 40;
            this.btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnDisabledState.BorderThickness = 1;
            this.btnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.OnDisabledState.IconLeftImage = null;
            this.btnUpdate.OnDisabledState.IconRightImage = null;
            this.btnUpdate.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.onHoverState.BorderRadius = 40;
            this.btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.onHoverState.BorderThickness = 1;
            this.btnUpdate.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnUpdate.onHoverState.IconLeftImage = null;
            this.btnUpdate.onHoverState.IconRightImage = null;
            this.btnUpdate.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnIdleState.BorderRadius = 40;
            this.btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnIdleState.BorderThickness = 1;
            this.btnUpdate.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnIdleState.IconLeftImage = null;
            this.btnUpdate.OnIdleState.IconRightImage = null;
            this.btnUpdate.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnPressedState.BorderRadius = 40;
            this.btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnPressedState.BorderThickness = 1;
            this.btnUpdate.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnPressedState.IconLeftImage = null;
            this.btnUpdate.OnPressedState.IconRightImage = null;
            this.btnUpdate.Size = new System.Drawing.Size(81, 46);
            this.btnUpdate.TabIndex = 182;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdate.TextMarginLeft = 0;
            this.btnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdate.UseDefaultRadiusAndThickness = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "XOÁ";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges9;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 10;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.IdleBorderRadius = 40;
            this.btnDelete.IdleBorderThickness = 1;
            this.btnDelete.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.IdleIconLeftImage = null;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(423, 527);
            this.btnDelete.Margin = new System.Windows.Forms.Padding(4);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 40;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.onHoverState.BorderRadius = 40;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnIdleState.BorderRadius = 40;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnIdleState.IconLeftImage = null;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnPressedState.BorderRadius = 40;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(81, 46);
            this.btnDelete.TabIndex = 181;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnAdd
            // 
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowMouseEffects = true;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.AutoRoundBorders = false;
            this.btnAdd.AutoSizeLeftIcon = true;
            this.btnAdd.AutoSizeRightIcon = true;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "THÊM";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges10;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 10;
            this.btnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdd.IconSize = 25;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleBorderRadius = 40;
            this.btnAdd.IdleBorderThickness = 1;
            this.btnAdd.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.IdleIconLeftImage = null;
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(334, 527);
            this.btnAdd.Margin = new System.Windows.Forms.Padding(4);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.OnDisabledState.BorderRadius = 40;
            this.btnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnDisabledState.BorderThickness = 1;
            this.btnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.OnDisabledState.IconLeftImage = null;
            this.btnAdd.OnDisabledState.IconRightImage = null;
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.BorderRadius = 40;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAdd.onHoverState.IconLeftImage = null;
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.BorderRadius = 40;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnIdleState.IconLeftImage = null;
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.BorderRadius = 40;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(81, 46);
            this.btnAdd.TabIndex = 180;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // btnCheck
            // 
            this.btnCheck.AllowAnimations = true;
            this.btnCheck.AllowMouseEffects = true;
            this.btnCheck.AllowToggling = false;
            this.btnCheck.AnimationSpeed = 200;
            this.btnCheck.AutoGenerateColors = false;
            this.btnCheck.AutoRoundBorders = false;
            this.btnCheck.AutoSizeLeftIcon = true;
            this.btnCheck.AutoSizeRightIcon = true;
            this.btnCheck.BackColor = System.Drawing.Color.Transparent;
            this.btnCheck.BackColor1 = System.Drawing.Color.LightSalmon;
            this.btnCheck.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCheck.BackgroundImage")));
            this.btnCheck.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.ButtonText = "TÌM KIẾM";
            this.btnCheck.ButtonTextMarginLeft = 0;
            this.btnCheck.ColorContrastOnClick = 45;
            this.btnCheck.ColorContrastOnHover = 45;
            this.btnCheck.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnCheck.CustomizableEdges = borderEdges11;
            this.btnCheck.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCheck.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCheck.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCheck.ForeColor = System.Drawing.Color.White;
            this.btnCheck.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCheck.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCheck.IconMarginLeft = 11;
            this.btnCheck.IconPadding = 10;
            this.btnCheck.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCheck.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheck.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCheck.IconSize = 25;
            this.btnCheck.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleBorderRadius = 40;
            this.btnCheck.IdleBorderThickness = 1;
            this.btnCheck.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.IdleIconLeftImage = null;
            this.btnCheck.IdleIconRightImage = null;
            this.btnCheck.IndicateFocus = false;
            this.btnCheck.Location = new System.Drawing.Point(1042, 25);
            this.btnCheck.Margin = new System.Windows.Forms.Padding(4);
            this.btnCheck.Name = "btnCheck";
            this.btnCheck.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheck.OnDisabledState.BorderRadius = 40;
            this.btnCheck.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnDisabledState.BorderThickness = 1;
            this.btnCheck.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheck.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheck.OnDisabledState.IconLeftImage = null;
            this.btnCheck.OnDisabledState.IconRightImage = null;
            this.btnCheck.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.BorderRadius = 40;
            this.btnCheck.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.onHoverState.BorderThickness = 1;
            this.btnCheck.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCheck.onHoverState.IconLeftImage = null;
            this.btnCheck.onHoverState.IconRightImage = null;
            this.btnCheck.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.BorderRadius = 40;
            this.btnCheck.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnIdleState.BorderThickness = 1;
            this.btnCheck.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnIdleState.IconLeftImage = null;
            this.btnCheck.OnIdleState.IconRightImage = null;
            this.btnCheck.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.BorderRadius = 40;
            this.btnCheck.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheck.OnPressedState.BorderThickness = 1;
            this.btnCheck.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.btnCheck.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCheck.OnPressedState.IconLeftImage = null;
            this.btnCheck.OnPressedState.IconRightImage = null;
            this.btnCheck.Size = new System.Drawing.Size(85, 46);
            this.btnCheck.TabIndex = 179;
            this.btnCheck.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCheck.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCheck.TextMarginLeft = 0;
            this.btnCheck.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCheck.UseDefaultRadiusAndThickness = true;
            this.btnCheck.Click += new System.EventHandler(this.btnCheck_Click);
            // 
            // AdminFillDrinkPrice
            // 
            this.AdminFillDrinkPrice.AcceptsReturn = false;
            this.AdminFillDrinkPrice.AcceptsTab = false;
            this.AdminFillDrinkPrice.AnimationSpeed = 200;
            this.AdminFillDrinkPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkPrice.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkPrice.BackgroundImage")));
            this.AdminFillDrinkPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkPrice.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdminFillDrinkPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkPrice.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFillDrinkPrice.BorderRadius = 35;
            this.AdminFillDrinkPrice.BorderThickness = 1;
            this.AdminFillDrinkPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkPrice.DefaultText = "";
            this.AdminFillDrinkPrice.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkPrice.HideSelection = true;
            this.AdminFillDrinkPrice.IconLeft = null;
            this.AdminFillDrinkPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.IconPadding = 10;
            this.AdminFillDrinkPrice.IconRight = null;
            this.AdminFillDrinkPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkPrice.Lines = new string[0];
            this.AdminFillDrinkPrice.Location = new System.Drawing.Point(871, 275);
            this.AdminFillDrinkPrice.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkPrice.MaxLength = 32767;
            this.AdminFillDrinkPrice.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkPrice.Modified = false;
            this.AdminFillDrinkPrice.Multiline = false;
            this.AdminFillDrinkPrice.Name = "AdminFillDrinkPrice";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Black;
            stateProperties34.FillColor = System.Drawing.Color.Transparent;
            stateProperties34.ForeColor = System.Drawing.Color.Transparent;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkPrice.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Black;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkPrice.OnIdleState = stateProperties36;
            this.AdminFillDrinkPrice.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkPrice.PasswordChar = '\0';
            this.AdminFillDrinkPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkPrice.PlaceholderText = "";
            this.AdminFillDrinkPrice.ReadOnly = false;
            this.AdminFillDrinkPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkPrice.SelectedText = "";
            this.AdminFillDrinkPrice.SelectionLength = 0;
            this.AdminFillDrinkPrice.SelectionStart = 0;
            this.AdminFillDrinkPrice.ShortcutsEnabled = true;
            this.AdminFillDrinkPrice.Size = new System.Drawing.Size(256, 38);
            this.AdminFillDrinkPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkPrice.TabIndex = 193;
            this.AdminFillDrinkPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkPrice.TextMarginBottom = 0;
            this.AdminFillDrinkPrice.TextMarginLeft = 3;
            this.AdminFillDrinkPrice.TextMarginTop = 0;
            this.AdminFillDrinkPrice.TextPlaceholder = "";
            this.AdminFillDrinkPrice.UseSystemPasswordChar = false;
            this.AdminFillDrinkPrice.WordWrap = true;
            // 
            // AdminFillDrinkType
            // 
            this.AdminFillDrinkType.AcceptsReturn = false;
            this.AdminFillDrinkType.AcceptsTab = false;
            this.AdminFillDrinkType.AnimationSpeed = 200;
            this.AdminFillDrinkType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillDrinkType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillDrinkType.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillDrinkType.BackgroundImage")));
            this.AdminFillDrinkType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkType.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdminFillDrinkType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillDrinkType.BorderColorIdle = System.Drawing.Color.Black;
            this.AdminFillDrinkType.BorderRadius = 35;
            this.AdminFillDrinkType.BorderThickness = 1;
            this.AdminFillDrinkType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillDrinkType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.DefaultFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkType.DefaultText = "";
            this.AdminFillDrinkType.FillColor = System.Drawing.Color.White;
            this.AdminFillDrinkType.HideSelection = true;
            this.AdminFillDrinkType.IconLeft = null;
            this.AdminFillDrinkType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.IconPadding = 10;
            this.AdminFillDrinkType.IconRight = null;
            this.AdminFillDrinkType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillDrinkType.Lines = new string[0];
            this.AdminFillDrinkType.Location = new System.Drawing.Point(869, 330);
            this.AdminFillDrinkType.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkType.MaxLength = 32767;
            this.AdminFillDrinkType.MinimumSize = new System.Drawing.Size(2, 2);
            this.AdminFillDrinkType.Modified = false;
            this.AdminFillDrinkType.Multiline = false;
            this.AdminFillDrinkType.Name = "AdminFillDrinkType";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Black;
            stateProperties38.FillColor = System.Drawing.Color.Transparent;
            stateProperties38.ForeColor = System.Drawing.Color.Transparent;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkType.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Black;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillDrinkType.OnIdleState = stateProperties40;
            this.AdminFillDrinkType.Padding = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkType.PasswordChar = '\0';
            this.AdminFillDrinkType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillDrinkType.PlaceholderText = "";
            this.AdminFillDrinkType.ReadOnly = false;
            this.AdminFillDrinkType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillDrinkType.SelectedText = "";
            this.AdminFillDrinkType.SelectionLength = 0;
            this.AdminFillDrinkType.SelectionStart = 0;
            this.AdminFillDrinkType.ShortcutsEnabled = true;
            this.AdminFillDrinkType.Size = new System.Drawing.Size(257, 38);
            this.AdminFillDrinkType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillDrinkType.TabIndex = 195;
            this.AdminFillDrinkType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillDrinkType.TextMarginBottom = 0;
            this.AdminFillDrinkType.TextMarginLeft = 3;
            this.AdminFillDrinkType.TextMarginTop = 0;
            this.AdminFillDrinkType.TextPlaceholder = "";
            this.AdminFillDrinkType.UseSystemPasswordChar = false;
            this.AdminFillDrinkType.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel3.Location = new System.Drawing.Point(886, 320);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(30, 17);
            this.bunifuLabel3.TabIndex = 194;
            this.bunifuLabel3.Text = "Loại:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel5.Location = new System.Drawing.Point(884, 374);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(69, 17);
            this.bunifuLabel5.TabIndex = 197;
            this.bunifuLabel5.Text = "Trạng thái:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminFillDrinkAvailable
            // 
            this.AdminFillDrinkAvailable.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillDrinkAvailable.BackgroundColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.BorderColor = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.BorderRadius = 19;
            this.AdminFillDrinkAvailable.Color = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.AdminFillDrinkAvailable.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.AdminFillDrinkAvailable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillDrinkAvailable.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.AdminFillDrinkAvailable.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.AdminFillDrinkAvailable.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.AdminFillDrinkAvailable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.AdminFillDrinkAvailable.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.AdminFillDrinkAvailable.DropDownHeight = 400;
            this.AdminFillDrinkAvailable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.AdminFillDrinkAvailable.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.AdminFillDrinkAvailable.FillDropDown = true;
            this.AdminFillDrinkAvailable.FillIndicator = false;
            this.AdminFillDrinkAvailable.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.AdminFillDrinkAvailable.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminFillDrinkAvailable.ForeColor = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.FormattingEnabled = true;
            this.AdminFillDrinkAvailable.Icon = null;
            this.AdminFillDrinkAvailable.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.AdminFillDrinkAvailable.IndicatorColor = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.AdminFillDrinkAvailable.IntegralHeight = false;
            this.AdminFillDrinkAvailable.ItemBackColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.ItemBorderColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.ItemForeColor = System.Drawing.Color.Black;
            this.AdminFillDrinkAvailable.ItemHeight = 30;
            this.AdminFillDrinkAvailable.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.AdminFillDrinkAvailable.ItemHighLightForeColor = System.Drawing.Color.White;
            this.AdminFillDrinkAvailable.Items.AddRange(new object[] {
            "Available",
            "Unavailable"});
            this.AdminFillDrinkAvailable.ItemTopMargin = 3;
            this.AdminFillDrinkAvailable.Location = new System.Drawing.Point(869, 385);
            this.AdminFillDrinkAvailable.Margin = new System.Windows.Forms.Padding(4);
            this.AdminFillDrinkAvailable.Name = "AdminFillDrinkAvailable";
            this.AdminFillDrinkAvailable.Size = new System.Drawing.Size(257, 36);
            this.AdminFillDrinkAvailable.TabIndex = 196;
            this.AdminFillDrinkAvailable.Text = null;
            this.AdminFillDrinkAvailable.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.AdminFillDrinkAvailable.TextLeftMargin = 5;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.SaddleBrown;
            this.bunifuLabel6.Location = new System.Drawing.Point(870, 111);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(61, 17);
            this.bunifuLabel6.TabIndex = 199;
            this.bunifuLabel6.Text = "Hình ảnh:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnImage
            // 
            this.btnImage.AllowAnimations = true;
            this.btnImage.AllowMouseEffects = true;
            this.btnImage.AllowToggling = false;
            this.btnImage.AnimationSpeed = 200;
            this.btnImage.AutoGenerateColors = false;
            this.btnImage.AutoRoundBorders = false;
            this.btnImage.AutoSizeLeftIcon = true;
            this.btnImage.AutoSizeRightIcon = true;
            this.btnImage.BackColor = System.Drawing.Color.Transparent;
            this.btnImage.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImage.BackgroundImage")));
            this.btnImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.ButtonText = "Chọn Ảnh";
            this.btnImage.ButtonTextMarginLeft = 0;
            this.btnImage.ColorContrastOnClick = 45;
            this.btnImage.ColorContrastOnHover = 45;
            this.btnImage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnImage.CustomizableEdges = borderEdges12;
            this.btnImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnImage.Font = new System.Drawing.Font("Segoe UI Black", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnImage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnImage.IconMarginLeft = 11;
            this.btnImage.IconPadding = 10;
            this.btnImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnImage.IconSize = 25;
            this.btnImage.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.IdleBorderRadius = 35;
            this.btnImage.IdleBorderThickness = 1;
            this.btnImage.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.IdleIconLeftImage = null;
            this.btnImage.IdleIconRightImage = null;
            this.btnImage.IndicateFocus = false;
            this.btnImage.Location = new System.Drawing.Point(954, 445);
            this.btnImage.Margin = new System.Windows.Forms.Padding(4);
            this.btnImage.Name = "btnImage";
            this.btnImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImage.OnDisabledState.BorderRadius = 35;
            this.btnImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnDisabledState.BorderThickness = 1;
            this.btnImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImage.OnDisabledState.IconLeftImage = null;
            this.btnImage.OnDisabledState.IconRightImage = null;
            this.btnImage.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.onHoverState.BorderRadius = 35;
            this.btnImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.onHoverState.BorderThickness = 1;
            this.btnImage.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnImage.onHoverState.IconLeftImage = null;
            this.btnImage.onHoverState.IconRightImage = null;
            this.btnImage.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.BorderRadius = 35;
            this.btnImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnIdleState.BorderThickness = 1;
            this.btnImage.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnImage.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnImage.OnIdleState.IconLeftImage = null;
            this.btnImage.OnIdleState.IconRightImage = null;
            this.btnImage.OnPressedState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnImage.OnPressedState.BorderRadius = 35;
            this.btnImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImage.OnPressedState.BorderThickness = 1;
            this.btnImage.OnPressedState.FillColor = System.Drawing.Color.Sienna;
            this.btnImage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImage.OnPressedState.IconLeftImage = null;
            this.btnImage.OnPressedState.IconRightImage = null;
            this.btnImage.Size = new System.Drawing.Size(94, 41);
            this.btnImage.TabIndex = 200;
            this.btnImage.TabStop = false;
            this.btnImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImage.TextMarginLeft = 0;
            this.btnImage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnImage.UseDefaultRadiusAndThickness = true;
            this.btnImage.Click += new System.EventHandler(this.btnImage_Click);
            // 
            // pictureBox
            // 
            this.pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pictureBox.Location = new System.Drawing.Point(869, 133);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(127, 127);
            this.pictureBox.TabIndex = 201;
            this.pictureBox.TabStop = false;
            // 
            // Drinks
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1159, 599);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.AdminFillDrinkPrice);
            this.Controls.Add(this.btnImage);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.AdminFillDrinkAvailable);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnRefresh);
            this.Controls.Add(this.AdminFillDrinkID);
            this.Controls.Add(this.AdminFillDrinkName);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.AdminFillDrinkSearch);
            this.Controls.Add(this.AdminViewAllYourDrinks);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.btnCheck);
            this.Controls.Add(this.AdminFillDrinkType);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Drinks";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản Lý Nước";
            this.Load += new System.EventHandler(this.Drinks_Load);
            ((System.ComponentModel.ISupportInitialize)(this.AdminViewAllYourDrinks)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkID;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkName;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkSearch;
        private Bunifu.UI.WinForms.BunifuDataGridView AdminViewAllYourDrinks;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCheck;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkPrice;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillDrinkType;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuDropdown AdminFillDrinkAvailable;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnImage;
        private System.Windows.Forms.PictureBox pictureBox;
    }
}