namespace Master_NekoCoffeeApp
{
    partial class Home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Home));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.linkLabel1 = new System.Windows.Forms.LinkLabel();
            this.logo = new System.Windows.Forms.PictureBox();
            this.lbHome = new System.Windows.Forms.Label();
            this.btnUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox11 = new System.Windows.Forms.PictureBox();
            this.pictureBox10 = new System.Windows.Forms.PictureBox();
            this.pictureBox8 = new System.Windows.Forms.PictureBox();
            this.pictureBox7 = new System.Windows.Forms.PictureBox();
            this.pictureBox6 = new System.Windows.Forms.PictureBox();
            this.pictureBox5 = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox12 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox9 = new System.Windows.Forms.PictureBox();
            this.pictureBox13 = new System.Windows.Forms.PictureBox();
            this.pictureBox14 = new System.Windows.Forms.PictureBox();
            this.btnEmployee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFoods = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInvoice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.linkLBHello = new System.Windows.Forms.LinkLabel();
            this.btnItems = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTable = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox14)).BeginInit();
            this.SuspendLayout();
            // 
            // linkLabel1
            // 
            this.linkLabel1.AutoSize = true;
            this.linkLabel1.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 10F);
            this.linkLabel1.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
            this.linkLabel1.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(121)))), ((int)(((byte)(84)))), ((int)(((byte)(88)))));
            this.linkLabel1.Location = new System.Drawing.Point(325, 54);
            this.linkLabel1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new System.Drawing.Size(113, 18);
            this.linkLabel1.TabIndex = 113;
            this.linkLabel1.TabStop = true;
            this.linkLabel1.Text = "For MasterUser";
            // 
            // logo
            // 
            this.logo.Image = ((System.Drawing.Image)(resources.GetObject("logo.Image")));
            this.logo.Location = new System.Drawing.Point(237, -2);
            this.logo.Margin = new System.Windows.Forms.Padding(2);
            this.logo.Name = "logo";
            this.logo.Size = new System.Drawing.Size(84, 84);
            this.logo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.logo.TabIndex = 114;
            this.logo.TabStop = false;
            // 
            // lbHome
            // 
            this.lbHome.AutoSize = true;
            this.lbHome.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 17F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbHome.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.lbHome.Location = new System.Drawing.Point(302, 25);
            this.lbHome.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lbHome.Name = "lbHome";
            this.lbHome.Size = new System.Drawing.Size(79, 29);
            this.lbHome.TabIndex = 117;
            this.lbHome.Text = "HOME";
            // 
            // btnUser
            // 
            this.btnUser.AllowAnimations = true;
            this.btnUser.AllowMouseEffects = true;
            this.btnUser.AllowToggling = false;
            this.btnUser.AnimationSpeed = 200;
            this.btnUser.AutoGenerateColors = false;
            this.btnUser.AutoRoundBorders = false;
            this.btnUser.AutoSizeLeftIcon = true;
            this.btnUser.AutoSizeRightIcon = true;
            this.btnUser.BackColor = System.Drawing.Color.Transparent;
            this.btnUser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUser.BackgroundImage")));
            this.btnUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.ButtonText = "User";
            this.btnUser.ButtonTextMarginLeft = 0;
            this.btnUser.ColorContrastOnClick = 45;
            this.btnUser.ColorContrastOnHover = 45;
            this.btnUser.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnUser.CustomizableEdges = borderEdges1;
            this.btnUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUser.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUser.IconMarginLeft = 11;
            this.btnUser.IconPadding = 10;
            this.btnUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUser.IconSize = 25;
            this.btnUser.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnUser.IdleBorderRadius = 30;
            this.btnUser.IdleBorderThickness = 1;
            this.btnUser.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnUser.IdleIconLeftImage = null;
            this.btnUser.IdleIconRightImage = null;
            this.btnUser.IndicateFocus = false;
            this.btnUser.Location = new System.Drawing.Point(148, 148);
            this.btnUser.Margin = new System.Windows.Forms.Padding(2);
            this.btnUser.Name = "btnUser";
            this.btnUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUser.OnDisabledState.BorderRadius = 30;
            this.btnUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnDisabledState.BorderThickness = 1;
            this.btnUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUser.OnDisabledState.IconLeftImage = null;
            this.btnUser.OnDisabledState.IconRightImage = null;
            this.btnUser.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnUser.onHoverState.BorderRadius = 30;
            this.btnUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.onHoverState.BorderThickness = 1;
            this.btnUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnUser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUser.onHoverState.IconLeftImage = null;
            this.btnUser.onHoverState.IconRightImage = null;
            this.btnUser.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnUser.OnIdleState.BorderRadius = 30;
            this.btnUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnIdleState.BorderThickness = 1;
            this.btnUser.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnUser.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnUser.OnIdleState.IconLeftImage = null;
            this.btnUser.OnIdleState.IconRightImage = null;
            this.btnUser.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnUser.OnPressedState.BorderRadius = 30;
            this.btnUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnPressedState.BorderThickness = 1;
            this.btnUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUser.OnPressedState.IconLeftImage = null;
            this.btnUser.OnPressedState.IconRightImage = null;
            this.btnUser.Size = new System.Drawing.Size(109, 73);
            this.btnUser.TabIndex = 118;
            this.btnUser.TabStop = false;
            this.btnUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUser.TextMarginLeft = 0;
            this.btnUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUser.UseDefaultRadiusAndThickness = true;
            this.btnUser.Click += new System.EventHandler(this.btnUser_Click);
            // 
            // pictureBox11
            // 
            this.pictureBox11.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox11.Image")));
            this.pictureBox11.Location = new System.Drawing.Point(-10, 383);
            this.pictureBox11.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox11.Name = "pictureBox11";
            this.pictureBox11.Size = new System.Drawing.Size(33, 32);
            this.pictureBox11.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox11.TabIndex = 130;
            this.pictureBox11.TabStop = false;
            // 
            // pictureBox10
            // 
            this.pictureBox10.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox10.Image")));
            this.pictureBox10.Location = new System.Drawing.Point(804, 175);
            this.pictureBox10.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox10.Name = "pictureBox10";
            this.pictureBox10.Size = new System.Drawing.Size(32, 32);
            this.pictureBox10.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox10.TabIndex = 129;
            this.pictureBox10.TabStop = false;
            // 
            // pictureBox8
            // 
            this.pictureBox8.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox8.Image")));
            this.pictureBox8.Location = new System.Drawing.Point(66, -2);
            this.pictureBox8.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox8.Name = "pictureBox8";
            this.pictureBox8.Size = new System.Drawing.Size(33, 29);
            this.pictureBox8.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox8.TabIndex = 128;
            this.pictureBox8.TabStop = false;
            // 
            // pictureBox7
            // 
            this.pictureBox7.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox7.Image")));
            this.pictureBox7.Location = new System.Drawing.Point(-9, -5);
            this.pictureBox7.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox7.Name = "pictureBox7";
            this.pictureBox7.Size = new System.Drawing.Size(32, 32);
            this.pictureBox7.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox7.TabIndex = 127;
            this.pictureBox7.TabStop = false;
            // 
            // pictureBox6
            // 
            this.pictureBox6.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox6.Image")));
            this.pictureBox6.Location = new System.Drawing.Point(-89, 60);
            this.pictureBox6.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox6.Name = "pictureBox6";
            this.pictureBox6.Size = new System.Drawing.Size(57, 54);
            this.pictureBox6.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox6.TabIndex = 126;
            this.pictureBox6.TabStop = false;
            // 
            // pictureBox5
            // 
            this.pictureBox5.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox5.Image")));
            this.pictureBox5.Location = new System.Drawing.Point(55, 408);
            this.pictureBox5.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox5.Name = "pictureBox5";
            this.pictureBox5.Size = new System.Drawing.Size(98, 99);
            this.pictureBox5.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox5.TabIndex = 125;
            this.pictureBox5.TabStop = false;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(768, 350);
            this.pictureBox3.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(78, 73);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox3.TabIndex = 123;
            this.pictureBox3.TabStop = false;
            // 
            // pictureBox4
            // 
            this.pictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox4.Image")));
            this.pictureBox4.Location = new System.Drawing.Point(741, -2);
            this.pictureBox4.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(95, 90);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox4.TabIndex = 124;
            this.pictureBox4.TabStop = false;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(-89, 281);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(78, 73);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 122;
            this.pictureBox1.TabStop = false;
            // 
            // pictureBox12
            // 
            this.pictureBox12.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox12.Image")));
            this.pictureBox12.Location = new System.Drawing.Point(644, 429);
            this.pictureBox12.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox12.Name = "pictureBox12";
            this.pictureBox12.Size = new System.Drawing.Size(85, 68);
            this.pictureBox12.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox12.TabIndex = 131;
            this.pictureBox12.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(803, 266);
            this.pictureBox2.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(33, 32);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 134;
            this.pictureBox2.TabStop = false;
            // 
            // pictureBox9
            // 
            this.pictureBox9.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox9.Image")));
            this.pictureBox9.Location = new System.Drawing.Point(-10, 96);
            this.pictureBox9.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox9.Name = "pictureBox9";
            this.pictureBox9.Size = new System.Drawing.Size(57, 54);
            this.pictureBox9.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox9.TabIndex = 133;
            this.pictureBox9.TabStop = false;
            // 
            // pictureBox13
            // 
            this.pictureBox13.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox13.Image")));
            this.pictureBox13.Location = new System.Drawing.Point(-10, 202);
            this.pictureBox13.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox13.Name = "pictureBox13";
            this.pictureBox13.Size = new System.Drawing.Size(78, 73);
            this.pictureBox13.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox13.TabIndex = 132;
            this.pictureBox13.TabStop = false;
            // 
            // pictureBox14
            // 
            this.pictureBox14.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox14.Image")));
            this.pictureBox14.Location = new System.Drawing.Point(436, 438);
            this.pictureBox14.Margin = new System.Windows.Forms.Padding(2);
            this.pictureBox14.Name = "pictureBox14";
            this.pictureBox14.Size = new System.Drawing.Size(70, 69);
            this.pictureBox14.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox14.TabIndex = 135;
            this.pictureBox14.TabStop = false;
            // 
            // btnEmployee
            // 
            this.btnEmployee.AllowAnimations = true;
            this.btnEmployee.AllowMouseEffects = true;
            this.btnEmployee.AllowToggling = false;
            this.btnEmployee.AnimationSpeed = 200;
            this.btnEmployee.AutoGenerateColors = false;
            this.btnEmployee.AutoRoundBorders = false;
            this.btnEmployee.AutoSizeLeftIcon = true;
            this.btnEmployee.AutoSizeRightIcon = true;
            this.btnEmployee.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployee.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnEmployee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployee.BackgroundImage")));
            this.btnEmployee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.ButtonText = "Employee";
            this.btnEmployee.ButtonTextMarginLeft = 0;
            this.btnEmployee.ColorContrastOnClick = 45;
            this.btnEmployee.ColorContrastOnHover = 45;
            this.btnEmployee.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEmployee.CustomizableEdges = borderEdges2;
            this.btnEmployee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployee.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmployee.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnEmployee.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmployee.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployee.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmployee.IconMarginLeft = 11;
            this.btnEmployee.IconPadding = 10;
            this.btnEmployee.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmployee.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmployee.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmployee.IconSize = 25;
            this.btnEmployee.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnEmployee.IdleBorderRadius = 30;
            this.btnEmployee.IdleBorderThickness = 1;
            this.btnEmployee.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnEmployee.IdleIconLeftImage = null;
            this.btnEmployee.IdleIconRightImage = null;
            this.btnEmployee.IndicateFocus = false;
            this.btnEmployee.Location = new System.Drawing.Point(272, 148);
            this.btnEmployee.Margin = new System.Windows.Forms.Padding(2);
            this.btnEmployee.Name = "btnEmployee";
            this.btnEmployee.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployee.OnDisabledState.BorderRadius = 30;
            this.btnEmployee.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.OnDisabledState.BorderThickness = 1;
            this.btnEmployee.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployee.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployee.OnDisabledState.IconLeftImage = null;
            this.btnEmployee.OnDisabledState.IconRightImage = null;
            this.btnEmployee.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnEmployee.onHoverState.BorderRadius = 30;
            this.btnEmployee.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.onHoverState.BorderThickness = 1;
            this.btnEmployee.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnEmployee.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmployee.onHoverState.IconLeftImage = null;
            this.btnEmployee.onHoverState.IconRightImage = null;
            this.btnEmployee.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnEmployee.OnIdleState.BorderRadius = 30;
            this.btnEmployee.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.OnIdleState.BorderThickness = 1;
            this.btnEmployee.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnEmployee.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnEmployee.OnIdleState.IconLeftImage = null;
            this.btnEmployee.OnIdleState.IconRightImage = null;
            this.btnEmployee.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnEmployee.OnPressedState.BorderRadius = 30;
            this.btnEmployee.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.OnPressedState.BorderThickness = 1;
            this.btnEmployee.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnEmployee.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmployee.OnPressedState.IconLeftImage = null;
            this.btnEmployee.OnPressedState.IconRightImage = null;
            this.btnEmployee.Size = new System.Drawing.Size(109, 73);
            this.btnEmployee.TabIndex = 136;
            this.btnEmployee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployee.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmployee.TextMarginLeft = 0;
            this.btnEmployee.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmployee.UseDefaultRadiusAndThickness = true;
            // 
            // btnFoods
            // 
            this.btnFoods.AllowAnimations = true;
            this.btnFoods.AllowMouseEffects = true;
            this.btnFoods.AllowToggling = false;
            this.btnFoods.AnimationSpeed = 200;
            this.btnFoods.AutoGenerateColors = false;
            this.btnFoods.AutoRoundBorders = false;
            this.btnFoods.AutoSizeLeftIcon = true;
            this.btnFoods.AutoSizeRightIcon = true;
            this.btnFoods.BackColor = System.Drawing.Color.Transparent;
            this.btnFoods.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnFoods.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFoods.BackgroundImage")));
            this.btnFoods.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoods.ButtonText = "Food";
            this.btnFoods.ButtonTextMarginLeft = 0;
            this.btnFoods.ColorContrastOnClick = 45;
            this.btnFoods.ColorContrastOnHover = 45;
            this.btnFoods.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnFoods.CustomizableEdges = borderEdges3;
            this.btnFoods.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFoods.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFoods.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFoods.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFoods.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFoods.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFoods.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnFoods.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFoods.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFoods.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFoods.IconMarginLeft = 11;
            this.btnFoods.IconPadding = 10;
            this.btnFoods.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFoods.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFoods.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFoods.IconSize = 25;
            this.btnFoods.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnFoods.IdleBorderRadius = 30;
            this.btnFoods.IdleBorderThickness = 1;
            this.btnFoods.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnFoods.IdleIconLeftImage = null;
            this.btnFoods.IdleIconRightImage = null;
            this.btnFoods.IndicateFocus = false;
            this.btnFoods.Location = new System.Drawing.Point(272, 244);
            this.btnFoods.Margin = new System.Windows.Forms.Padding(2);
            this.btnFoods.Name = "btnFoods";
            this.btnFoods.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFoods.OnDisabledState.BorderRadius = 30;
            this.btnFoods.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoods.OnDisabledState.BorderThickness = 1;
            this.btnFoods.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFoods.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFoods.OnDisabledState.IconLeftImage = null;
            this.btnFoods.OnDisabledState.IconRightImage = null;
            this.btnFoods.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnFoods.onHoverState.BorderRadius = 30;
            this.btnFoods.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoods.onHoverState.BorderThickness = 1;
            this.btnFoods.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnFoods.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFoods.onHoverState.IconLeftImage = null;
            this.btnFoods.onHoverState.IconRightImage = null;
            this.btnFoods.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnFoods.OnIdleState.BorderRadius = 30;
            this.btnFoods.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoods.OnIdleState.BorderThickness = 1;
            this.btnFoods.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnFoods.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnFoods.OnIdleState.IconLeftImage = null;
            this.btnFoods.OnIdleState.IconRightImage = null;
            this.btnFoods.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnFoods.OnPressedState.BorderRadius = 30;
            this.btnFoods.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoods.OnPressedState.BorderThickness = 1;
            this.btnFoods.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnFoods.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFoods.OnPressedState.IconLeftImage = null;
            this.btnFoods.OnPressedState.IconRightImage = null;
            this.btnFoods.Size = new System.Drawing.Size(109, 73);
            this.btnFoods.TabIndex = 137;
            this.btnFoods.TabStop = false;
            this.btnFoods.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFoods.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFoods.TextMarginLeft = 0;
            this.btnFoods.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFoods.UseDefaultRadiusAndThickness = true;
            // 
            // btnDrink
            // 
            this.btnDrink.AllowAnimations = true;
            this.btnDrink.AllowMouseEffects = true;
            this.btnDrink.AllowToggling = false;
            this.btnDrink.AnimationSpeed = 200;
            this.btnDrink.AutoGenerateColors = false;
            this.btnDrink.AutoRoundBorders = false;
            this.btnDrink.AutoSizeLeftIcon = true;
            this.btnDrink.AutoSizeRightIcon = true;
            this.btnDrink.BackColor = System.Drawing.Color.Transparent;
            this.btnDrink.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDrink.BackgroundImage")));
            this.btnDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDrink.ButtonText = "Drink";
            this.btnDrink.ButtonTextMarginLeft = 0;
            this.btnDrink.ColorContrastOnClick = 45;
            this.btnDrink.ColorContrastOnHover = 45;
            this.btnDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnDrink.CustomizableEdges = borderEdges4;
            this.btnDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDrink.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDrink.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDrink.IconMarginLeft = 11;
            this.btnDrink.IconPadding = 10;
            this.btnDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDrink.IconSize = 25;
            this.btnDrink.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnDrink.IdleBorderRadius = 30;
            this.btnDrink.IdleBorderThickness = 1;
            this.btnDrink.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnDrink.IdleIconLeftImage = null;
            this.btnDrink.IdleIconRightImage = null;
            this.btnDrink.IndicateFocus = false;
            this.btnDrink.Location = new System.Drawing.Point(148, 244);
            this.btnDrink.Margin = new System.Windows.Forms.Padding(2);
            this.btnDrink.Name = "btnDrink";
            this.btnDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDrink.OnDisabledState.BorderRadius = 30;
            this.btnDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDrink.OnDisabledState.BorderThickness = 1;
            this.btnDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDrink.OnDisabledState.IconLeftImage = null;
            this.btnDrink.OnDisabledState.IconRightImage = null;
            this.btnDrink.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnDrink.onHoverState.BorderRadius = 30;
            this.btnDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDrink.onHoverState.BorderThickness = 1;
            this.btnDrink.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnDrink.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDrink.onHoverState.IconLeftImage = null;
            this.btnDrink.onHoverState.IconRightImage = null;
            this.btnDrink.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnDrink.OnIdleState.BorderRadius = 30;
            this.btnDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDrink.OnIdleState.BorderThickness = 1;
            this.btnDrink.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnDrink.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnDrink.OnIdleState.IconLeftImage = null;
            this.btnDrink.OnIdleState.IconRightImage = null;
            this.btnDrink.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnDrink.OnPressedState.BorderRadius = 30;
            this.btnDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDrink.OnPressedState.BorderThickness = 1;
            this.btnDrink.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDrink.OnPressedState.IconLeftImage = null;
            this.btnDrink.OnPressedState.IconRightImage = null;
            this.btnDrink.Size = new System.Drawing.Size(109, 73);
            this.btnDrink.TabIndex = 138;
            this.btnDrink.TabStop = false;
            this.btnDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDrink.TextMarginLeft = 0;
            this.btnDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDrink.UseDefaultRadiusAndThickness = true;
            // 
            // btnCustomer
            // 
            this.btnCustomer.AllowAnimations = true;
            this.btnCustomer.AllowMouseEffects = true;
            this.btnCustomer.AllowToggling = false;
            this.btnCustomer.AnimationSpeed = 200;
            this.btnCustomer.AutoGenerateColors = false;
            this.btnCustomer.AutoRoundBorders = false;
            this.btnCustomer.AutoSizeLeftIcon = true;
            this.btnCustomer.AutoSizeRightIcon = true;
            this.btnCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomer.BackgroundImage")));
            this.btnCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.ButtonText = "Customer";
            this.btnCustomer.ButtonTextMarginLeft = 0;
            this.btnCustomer.ColorContrastOnClick = 45;
            this.btnCustomer.ColorContrastOnHover = 45;
            this.btnCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnCustomer.CustomizableEdges = borderEdges5;
            this.btnCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustomer.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCustomer.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustomer.IconMarginLeft = 11;
            this.btnCustomer.IconPadding = 10;
            this.btnCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustomer.IconSize = 25;
            this.btnCustomer.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCustomer.IdleBorderRadius = 30;
            this.btnCustomer.IdleBorderThickness = 1;
            this.btnCustomer.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCustomer.IdleIconLeftImage = null;
            this.btnCustomer.IdleIconRightImage = null;
            this.btnCustomer.IndicateFocus = false;
            this.btnCustomer.Location = new System.Drawing.Point(397, 148);
            this.btnCustomer.Margin = new System.Windows.Forms.Padding(2);
            this.btnCustomer.Name = "btnCustomer";
            this.btnCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.OnDisabledState.BorderRadius = 30;
            this.btnCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnDisabledState.BorderThickness = 1;
            this.btnCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.OnDisabledState.IconLeftImage = null;
            this.btnCustomer.OnDisabledState.IconRightImage = null;
            this.btnCustomer.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnCustomer.onHoverState.BorderRadius = 30;
            this.btnCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.onHoverState.BorderThickness = 1;
            this.btnCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.onHoverState.IconLeftImage = null;
            this.btnCustomer.onHoverState.IconRightImage = null;
            this.btnCustomer.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCustomer.OnIdleState.BorderRadius = 30;
            this.btnCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnIdleState.BorderThickness = 1;
            this.btnCustomer.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCustomer.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCustomer.OnIdleState.IconLeftImage = null;
            this.btnCustomer.OnIdleState.IconRightImage = null;
            this.btnCustomer.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnCustomer.OnPressedState.BorderRadius = 30;
            this.btnCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnPressedState.BorderThickness = 1;
            this.btnCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.OnPressedState.IconLeftImage = null;
            this.btnCustomer.OnPressedState.IconRightImage = null;
            this.btnCustomer.Size = new System.Drawing.Size(109, 73);
            this.btnCustomer.TabIndex = 139;
            this.btnCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustomer.TextMarginLeft = 0;
            this.btnCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // btnInvoice
            // 
            this.btnInvoice.AllowAnimations = true;
            this.btnInvoice.AllowMouseEffects = true;
            this.btnInvoice.AllowToggling = false;
            this.btnInvoice.AnimationSpeed = 200;
            this.btnInvoice.AutoGenerateColors = false;
            this.btnInvoice.AutoRoundBorders = false;
            this.btnInvoice.AutoSizeLeftIcon = true;
            this.btnInvoice.AutoSizeRightIcon = true;
            this.btnInvoice.BackColor = System.Drawing.Color.Transparent;
            this.btnInvoice.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnInvoice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInvoice.BackgroundImage")));
            this.btnInvoice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInvoice.ButtonText = "Invoice";
            this.btnInvoice.ButtonTextMarginLeft = 0;
            this.btnInvoice.ColorContrastOnClick = 45;
            this.btnInvoice.ColorContrastOnHover = 45;
            this.btnInvoice.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnInvoice.CustomizableEdges = borderEdges6;
            this.btnInvoice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInvoice.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInvoice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInvoice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInvoice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInvoice.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInvoice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnInvoice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInvoice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInvoice.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInvoice.IconMarginLeft = 11;
            this.btnInvoice.IconPadding = 10;
            this.btnInvoice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInvoice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInvoice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInvoice.IconSize = 25;
            this.btnInvoice.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnInvoice.IdleBorderRadius = 30;
            this.btnInvoice.IdleBorderThickness = 1;
            this.btnInvoice.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnInvoice.IdleIconLeftImage = null;
            this.btnInvoice.IdleIconRightImage = null;
            this.btnInvoice.IndicateFocus = false;
            this.btnInvoice.Location = new System.Drawing.Point(397, 244);
            this.btnInvoice.Margin = new System.Windows.Forms.Padding(2);
            this.btnInvoice.Name = "btnInvoice";
            this.btnInvoice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInvoice.OnDisabledState.BorderRadius = 30;
            this.btnInvoice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInvoice.OnDisabledState.BorderThickness = 1;
            this.btnInvoice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInvoice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInvoice.OnDisabledState.IconLeftImage = null;
            this.btnInvoice.OnDisabledState.IconRightImage = null;
            this.btnInvoice.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnInvoice.onHoverState.BorderRadius = 30;
            this.btnInvoice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInvoice.onHoverState.BorderThickness = 1;
            this.btnInvoice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnInvoice.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInvoice.onHoverState.IconLeftImage = null;
            this.btnInvoice.onHoverState.IconRightImage = null;
            this.btnInvoice.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnInvoice.OnIdleState.BorderRadius = 30;
            this.btnInvoice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInvoice.OnIdleState.BorderThickness = 1;
            this.btnInvoice.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnInvoice.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnInvoice.OnIdleState.IconLeftImage = null;
            this.btnInvoice.OnIdleState.IconRightImage = null;
            this.btnInvoice.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnInvoice.OnPressedState.BorderRadius = 30;
            this.btnInvoice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInvoice.OnPressedState.BorderThickness = 1;
            this.btnInvoice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnInvoice.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInvoice.OnPressedState.IconLeftImage = null;
            this.btnInvoice.OnPressedState.IconRightImage = null;
            this.btnInvoice.Size = new System.Drawing.Size(109, 73);
            this.btnInvoice.TabIndex = 140;
            this.btnInvoice.TabStop = false;
            this.btnInvoice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInvoice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInvoice.TextMarginLeft = 0;
            this.btnInvoice.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInvoice.UseDefaultRadiusAndThickness = true;
            // 
            // linkLBHello
            // 
            this.linkLBHello.AutoSize = true;
            this.linkLBHello.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLBHello.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
            this.linkLBHello.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(121)))), ((int)(((byte)(84)))), ((int)(((byte)(88)))));
            this.linkLBHello.Location = new System.Drawing.Point(201, 96);
            this.linkLBHello.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.linkLBHello.Name = "linkLBHello";
            this.linkLBHello.Size = new System.Drawing.Size(56, 24);
            this.linkLBHello.TabIndex = 141;
            this.linkLBHello.TabStop = true;
            this.linkLBHello.Text = "Hello";
            // 
            // btnItems
            // 
            this.btnItems.AllowAnimations = true;
            this.btnItems.AllowMouseEffects = true;
            this.btnItems.AllowToggling = false;
            this.btnItems.AnimationSpeed = 200;
            this.btnItems.AutoGenerateColors = false;
            this.btnItems.AutoRoundBorders = false;
            this.btnItems.AutoSizeLeftIcon = true;
            this.btnItems.AutoSizeRightIcon = true;
            this.btnItems.BackColor = System.Drawing.Color.Transparent;
            this.btnItems.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnItems.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnItems.BackgroundImage")));
            this.btnItems.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.ButtonText = "Items";
            this.btnItems.ButtonTextMarginLeft = 0;
            this.btnItems.ColorContrastOnClick = 45;
            this.btnItems.ColorContrastOnHover = 45;
            this.btnItems.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnItems.CustomizableEdges = borderEdges7;
            this.btnItems.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnItems.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnItems.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnItems.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnItems.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnItems.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnItems.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnItems.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnItems.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnItems.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnItems.IconMarginLeft = 11;
            this.btnItems.IconPadding = 10;
            this.btnItems.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnItems.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnItems.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnItems.IconSize = 25;
            this.btnItems.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnItems.IdleBorderRadius = 30;
            this.btnItems.IdleBorderThickness = 1;
            this.btnItems.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnItems.IdleIconLeftImage = null;
            this.btnItems.IdleIconRightImage = null;
            this.btnItems.IndicateFocus = false;
            this.btnItems.Location = new System.Drawing.Point(522, 148);
            this.btnItems.Margin = new System.Windows.Forms.Padding(2);
            this.btnItems.Name = "btnItems";
            this.btnItems.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnItems.OnDisabledState.BorderRadius = 30;
            this.btnItems.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnDisabledState.BorderThickness = 1;
            this.btnItems.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnItems.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnItems.OnDisabledState.IconLeftImage = null;
            this.btnItems.OnDisabledState.IconRightImage = null;
            this.btnItems.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnItems.onHoverState.BorderRadius = 30;
            this.btnItems.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.onHoverState.BorderThickness = 1;
            this.btnItems.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnItems.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnItems.onHoverState.IconLeftImage = null;
            this.btnItems.onHoverState.IconRightImage = null;
            this.btnItems.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnItems.OnIdleState.BorderRadius = 30;
            this.btnItems.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnIdleState.BorderThickness = 1;
            this.btnItems.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnItems.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnItems.OnIdleState.IconLeftImage = null;
            this.btnItems.OnIdleState.IconRightImage = null;
            this.btnItems.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnItems.OnPressedState.BorderRadius = 30;
            this.btnItems.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnItems.OnPressedState.BorderThickness = 1;
            this.btnItems.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnItems.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnItems.OnPressedState.IconLeftImage = null;
            this.btnItems.OnPressedState.IconRightImage = null;
            this.btnItems.Size = new System.Drawing.Size(109, 73);
            this.btnItems.TabIndex = 142;
            this.btnItems.TabStop = false;
            this.btnItems.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnItems.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnItems.TextMarginLeft = 0;
            this.btnItems.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnItems.UseDefaultRadiusAndThickness = true;
            // 
            // btnCat
            // 
            this.btnCat.AllowAnimations = true;
            this.btnCat.AllowMouseEffects = true;
            this.btnCat.AllowToggling = false;
            this.btnCat.AnimationSpeed = 200;
            this.btnCat.AutoGenerateColors = false;
            this.btnCat.AutoRoundBorders = false;
            this.btnCat.AutoSizeLeftIcon = true;
            this.btnCat.AutoSizeRightIcon = true;
            this.btnCat.BackColor = System.Drawing.Color.Transparent;
            this.btnCat.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCat.BackgroundImage")));
            this.btnCat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCat.ButtonText = "Cat";
            this.btnCat.ButtonTextMarginLeft = 0;
            this.btnCat.ColorContrastOnClick = 45;
            this.btnCat.ColorContrastOnHover = 45;
            this.btnCat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnCat.CustomizableEdges = borderEdges8;
            this.btnCat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCat.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCat.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCat.IconMarginLeft = 11;
            this.btnCat.IconPadding = 10;
            this.btnCat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCat.IconSize = 25;
            this.btnCat.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCat.IdleBorderRadius = 30;
            this.btnCat.IdleBorderThickness = 1;
            this.btnCat.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCat.IdleIconLeftImage = null;
            this.btnCat.IdleIconRightImage = null;
            this.btnCat.IndicateFocus = false;
            this.btnCat.Location = new System.Drawing.Point(522, 244);
            this.btnCat.Margin = new System.Windows.Forms.Padding(2);
            this.btnCat.Name = "btnCat";
            this.btnCat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCat.OnDisabledState.BorderRadius = 30;
            this.btnCat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCat.OnDisabledState.BorderThickness = 1;
            this.btnCat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCat.OnDisabledState.IconLeftImage = null;
            this.btnCat.OnDisabledState.IconRightImage = null;
            this.btnCat.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnCat.onHoverState.BorderRadius = 30;
            this.btnCat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCat.onHoverState.BorderThickness = 1;
            this.btnCat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCat.onHoverState.IconLeftImage = null;
            this.btnCat.onHoverState.IconRightImage = null;
            this.btnCat.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCat.OnIdleState.BorderRadius = 30;
            this.btnCat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCat.OnIdleState.BorderThickness = 1;
            this.btnCat.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnCat.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnCat.OnIdleState.IconLeftImage = null;
            this.btnCat.OnIdleState.IconRightImage = null;
            this.btnCat.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnCat.OnPressedState.BorderRadius = 30;
            this.btnCat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCat.OnPressedState.BorderThickness = 1;
            this.btnCat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnCat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCat.OnPressedState.IconLeftImage = null;
            this.btnCat.OnPressedState.IconRightImage = null;
            this.btnCat.Size = new System.Drawing.Size(109, 73);
            this.btnCat.TabIndex = 143;
            this.btnCat.TabStop = false;
            this.btnCat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCat.TextMarginLeft = 0;
            this.btnCat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCat.UseDefaultRadiusAndThickness = true;
            // 
            // btnTable
            // 
            this.btnTable.AllowAnimations = true;
            this.btnTable.AllowMouseEffects = true;
            this.btnTable.AllowToggling = false;
            this.btnTable.AnimationSpeed = 200;
            this.btnTable.AutoGenerateColors = false;
            this.btnTable.AutoRoundBorders = false;
            this.btnTable.AutoSizeLeftIcon = true;
            this.btnTable.AutoSizeRightIcon = true;
            this.btnTable.BackColor = System.Drawing.Color.Transparent;
            this.btnTable.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnTable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTable.BackgroundImage")));
            this.btnTable.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTable.ButtonText = "Table";
            this.btnTable.ButtonTextMarginLeft = 0;
            this.btnTable.ColorContrastOnClick = 45;
            this.btnTable.ColorContrastOnHover = 45;
            this.btnTable.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnTable.CustomizableEdges = borderEdges9;
            this.btnTable.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTable.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTable.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTable.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTable.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTable.Font = new System.Drawing.Font("#9Slide03 BoosterNextFYBlack", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTable.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnTable.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTable.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTable.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTable.IconMarginLeft = 11;
            this.btnTable.IconPadding = 10;
            this.btnTable.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTable.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTable.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTable.IconSize = 25;
            this.btnTable.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnTable.IdleBorderRadius = 30;
            this.btnTable.IdleBorderThickness = 1;
            this.btnTable.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnTable.IdleIconLeftImage = null;
            this.btnTable.IdleIconRightImage = null;
            this.btnTable.IndicateFocus = false;
            this.btnTable.Location = new System.Drawing.Point(644, 148);
            this.btnTable.Margin = new System.Windows.Forms.Padding(2);
            this.btnTable.Name = "btnTable";
            this.btnTable.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTable.OnDisabledState.BorderRadius = 30;
            this.btnTable.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTable.OnDisabledState.BorderThickness = 1;
            this.btnTable.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTable.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTable.OnDisabledState.IconLeftImage = null;
            this.btnTable.OnDisabledState.IconRightImage = null;
            this.btnTable.onHoverState.BorderColor = System.Drawing.Color.Chocolate;
            this.btnTable.onHoverState.BorderRadius = 30;
            this.btnTable.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTable.onHoverState.BorderThickness = 1;
            this.btnTable.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnTable.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTable.onHoverState.IconLeftImage = null;
            this.btnTable.onHoverState.IconRightImage = null;
            this.btnTable.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnTable.OnIdleState.BorderRadius = 30;
            this.btnTable.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTable.OnIdleState.BorderThickness = 1;
            this.btnTable.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(225)))));
            this.btnTable.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(143)))), ((int)(((byte)(94)))));
            this.btnTable.OnIdleState.IconLeftImage = null;
            this.btnTable.OnIdleState.IconRightImage = null;
            this.btnTable.OnPressedState.BorderColor = System.Drawing.Color.DarkRed;
            this.btnTable.OnPressedState.BorderRadius = 30;
            this.btnTable.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTable.OnPressedState.BorderThickness = 1;
            this.btnTable.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.btnTable.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTable.OnPressedState.IconLeftImage = null;
            this.btnTable.OnPressedState.IconRightImage = null;
            this.btnTable.Size = new System.Drawing.Size(109, 73);
            this.btnTable.TabIndex = 144;
            this.btnTable.TabStop = false;
            this.btnTable.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTable.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTable.TextMarginLeft = 0;
            this.btnTable.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTable.UseDefaultRadiusAndThickness = true;
            // 
            // Home
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(825, 499);
            this.Controls.Add(this.btnTable);
            this.Controls.Add(this.btnCat);
            this.Controls.Add(this.btnItems);
            this.Controls.Add(this.linkLBHello);
            this.Controls.Add(this.btnInvoice);
            this.Controls.Add(this.btnCustomer);
            this.Controls.Add(this.btnDrink);
            this.Controls.Add(this.btnFoods);
            this.Controls.Add(this.btnEmployee);
            this.Controls.Add(this.pictureBox14);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox9);
            this.Controls.Add(this.pictureBox13);
            this.Controls.Add(this.pictureBox11);
            this.Controls.Add(this.pictureBox10);
            this.Controls.Add(this.pictureBox8);
            this.Controls.Add(this.pictureBox7);
            this.Controls.Add(this.pictureBox6);
            this.Controls.Add(this.pictureBox5);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.pictureBox12);
            this.Controls.Add(this.btnUser);
            this.Controls.Add(this.lbHome);
            this.Controls.Add(this.logo);
            this.Controls.Add(this.linkLabel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Home";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Home";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Home_FormClosing);
            this.Load += new System.EventHandler(this.Home_Load);
            ((System.ComponentModel.ISupportInitialize)(this.logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox14)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.LinkLabel linkLabel1;
        private System.Windows.Forms.PictureBox logo;
        private System.Windows.Forms.Label lbHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUser;
        private System.Windows.Forms.PictureBox pictureBox11;
        private System.Windows.Forms.PictureBox pictureBox10;
        private System.Windows.Forms.PictureBox pictureBox8;
        private System.Windows.Forms.PictureBox pictureBox7;
        private System.Windows.Forms.PictureBox pictureBox6;
        private System.Windows.Forms.PictureBox pictureBox5;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox4;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox12;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox9;
        private System.Windows.Forms.PictureBox pictureBox13;
        private System.Windows.Forms.PictureBox pictureBox14;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployee;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFoods;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInvoice;
        private System.Windows.Forms.LinkLabel linkLBHello;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnItems;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTable;
    }
}